### ISSUE TITLE
ngrok too many connections

### ISSUE THREAD

**Issue by niwo77** [htr-tech/zphisher#105]
only "stay online" for like 2-3 minutes and after that when you try to entry it says:
![123055578_1316670595345520_2030704728415042833_n](https://user-images.githubusercontent.com/73561825/97641191-37b58380-1a3a-11eb-929e-4eb4d2757997.jpg)
(sorry if i made some mistakes writing this, i'm spanish.)

**Comment by htr-tech** [comment]
@niwo77 its because of ngroks free plan .. give link to only one victim at once

**Comment by niwo77** [comment]
oh, okay. thanks!
