### ISSUE TITLE
Ngrok was unable to Generate Link.. Try Again

### ISSUE THREAD

**Issue by Residentx91** [htr-tech/zphisher#107]
When I launch Ngrok without hotspot that sms appears

**Comment by ghostfighter50** [comment]
same

**Comment by anzilr** [comment]
**fix** 

Go to
### https://dashboard.ngrok.com/get-started/setup###

**Comment by anzilr** [comment]
Go to https://dashboard.ngrok.com/get-started/setup and download the package.

Create an account for auth token.

run 
```
unzip /path/to/ngrok.zip
```
```
./ngrok authtoken YOUR_TOKEN
```

```
./ngrok http http://127.0.0.1:5555
```

NOTE: follow this after localhost method

**Comment by anzilr** [comment]
@ghostfighter50 Go to https://dashboard.ngrok.com/get-started/setup and download the package.

Create an account for auth token.

run 
```
unzip /path/to/ngrok.zip
```
```
./ngrok authtoken YOUR_TOKEN
```

```
./ngrok http http://127.0.0.1:5555
```

# NOTE: follow this after or before localhost method in a seperate terminal.

**Comment by htr-tech** [comment]
> When I launch Ngrok without hotspot that sms appears

try twice
