### ISSUE TITLE
Zphisher

### ISSUE THREAD

**Issue by hacker392** [htr-tech/zphisher#113]
If I got someone access . Is it accessable to you to?

**Comment by htr-tech** [comment]
@hacker392 nope

**Comment by hacker392** [comment]
> @hacker392 nope

I tried to hack my friend with his permission but when i entered the id and password the browser show 'Too many attempts Try later" 
Why?

**Comment by htr-tech** [comment]
> > @hacker392 nope
> 
> I tried to hack my friend with his permission but when i entered the id and password the browser show 'Too many attempts Try later"
> Why?

give one link to one user max
