### ISSUE TITLE
The requested resource / was not found on this server.

### ISSUE THREAD

**Issue by abhitcr1** [htr-tech/zphisher#117]
I get the following error when I enter the link generated:
Not Found
The requested resource / was not found on this server.

I am attaching a screenshot of the same
![image](https://user-images.githubusercontent.com/55338164/98740601-55d39a00-23d1-11eb-9275-5d760fd19ccc.png)

**Comment by htr-tech** [comment]
@abhitcr1 make sure that you have keep the zphisher session opened & if you are root then trying with sudo 😩

**Comment by abhitcr1** [comment]
its working now
