### ISSUE TITLE
nice obfuscation bro

### ISSUE THREAD

**Issue by bionicBUG** [htr-tech/zphisher#12]
GNU license is a meme, isn't it?

**Comment by robbyoconnor** [comment]
![image](https://user-images.githubusercontent.com/23088/81483676-fc19c980-920d-11ea-9f13-6d7441f3a513.png)


This is not how you do Open Source.

**Comment by bengris32** [comment]
https://raw.githubusercontent.com/bengris32/htr-tech-deobfuscated/master/zphisher_src.sh
sure is bro

**Comment by robbyoconnor** [comment]
> https://raw.githubusercontent.com/bengris32/htr-tech-deobfuscated/master/zphisher_src.sh
> sure is bro

Oh yes, shows obfuscating bash is useless.

**Comment by robbyoconnor** [comment]
> https://raw.githubusercontent.com/bengris32/htr-tech-deobfuscated/master/zphisher_src.sh
> sure is bro

Oh yes, shows obfuscating bash is useless. Actually obfuscating, in general, is useless and trivial to remove and defeat in general

**Comment by htr-tech** [comment]
> > https://raw.githubusercontent.com/bengris32/htr-tech-deobfuscated/master/zphisher_src.sh
> > sure is bro
> 
> Oh yes, shows obfuscating bash is useless. Actually obfuscating, in general, is useless and trivial to remove and defeat in general

Bro Thats True :( I have obfuscated the code for those morons , who steal others code & just rename the script

**Comment by htr-tech** [comment]
> https://raw.githubusercontent.com/bengris32/htr-tech-deobfuscated/master/zphisher_src.sh
> sure is bro
> this is pro level obfuscation

ya , bash obfuscation is useless . anyone can decrypt it. But python deobfuscation is hard

**Comment by robbyoconnor** [comment]
@bengris32 don't give in

**Comment by htr-tech** [comment]
> @bengris32 don't give in

@robbyoconnor @bengris32  for your kind information , zphisher has been open sourced . I will soon all my tools open sourced

**Comment by robbyoconnor** [comment]
really?

**Comment by htr-tech** [comment]
> really?

ya . But can anyone teach me to decrypt python script ????

**Comment by htr-tech** [comment]
> GNU license is a meme, isn't it?

Tools have been Open sourced @bionicBUG 🤣🤣🤣🤣🤣

**Comment by Techno-Disaster** [comment]
Very pro level stuff here.

**Comment by robbyoconnor** [comment]
> > GNU license is a meme, isn't it?
> 
> Tools have been Open sourced @bionicBUG

![image](https://user-images.githubusercontent.com/23088/81513243-eaf7b800-92f4-11ea-93e3-4abbe41d59a6.png)

Really? Ever heard of indentation?
