### ISSUE TITLE
Port 80

### ISSUE THREAD

**Issue by Archie-456** [htr-tech/zphisher#123]
Is it possible to have it direct to port 80 instead of 5555? I want to encode the links, but when I send them, I have to send them as a link with the 5555 port.

My thought is if I could default it to port 80, it should come in as normal web traffic?

I am sending a facebook traditional login, but the link looks odd with an IP:port

**Comment by htr-tech** [comment]
@Archie-456 port 80 & 8080 is often used by many system softwares ... thats why i used 5555 .. but u can try . changing the port numbers into zphisher.sh
