### ISSUE TITLE
Failed to complete tunnel connection

### ISSUE THREAD

**Issue by drey0735** [htr-tech/zphisher#128]
The connection to https://eedba7687e9f.ngrok.io was successfully tunneled to your ngrok client, but the client failed to establish a connection to the local address 127.0.0.1:5555.

Make sure that a web service is running on 127.0.0.1:5555 and that it is a valid address.

The error encountered was: dial tcp 127.0.0.1:5555: getsockopt: connection refused

Thats when I tried the link on chrome . Ngrok .

**Comment by drey0735** [comment]
![Screenshot_20201130_230924_com android chrome](https://user-images.githubusercontent.com/75262962/100626733-22958280-3361-11eb-8fb5-d9b3e80cab19.jpg)

**Comment by drey0735** [comment]
![Screenshot_20201130_230929_com termux](https://user-images.githubusercontent.com/75262962/100626754-29bc9080-3361-11eb-98d4-00abff5fb29e.jpg)

**Comment by htr-tech** [comment]
@drey0735 you have to keep your termux session open

**Comment by htr-tech** [comment]
if you are root then try with root permission
