### ISSUE TITLE
error

### ISSUE THREAD

**Issue by noob0x01** [htr-tech/zphisher#13]
root@kali:~/zphisher# ./zphisher.sh
./zphisher.sh: line 10: $'\r': command not found
: invalid signal specification2
./zphisher.sh: line 12: $'\r': command not found
./zphisher.sh: line 13: syntax error near unexpected token `$'{\r''
'/zphisher.sh: line 13: `deps() {

**Comment by htr-tech** [comment]
@noob0x01 Fixed !
![image](https://user-images.githubusercontent.com/56682134/81533900-d9f88680-9388-11ea-8c9c-73498ce45282.png)
