### ISSUE TITLE
IT WORKS!

### ISSUE THREAD

**Issue by oam1551** [htr-tech/zphisher#130]
CAN SOMEONE PLEASE LET ME KNOW WHAT I AM DOING WRONG.
![Screen Shot 2020-12-05 at 8 51 46 PM](https://user-images.githubusercontent.com/75538070/101271883-d5882680-373b-11eb-95ba-2eb0068d4727.png)

**Comment by Zumaru711** [comment]
what are you doing explain further?

**Comment by htr-tech** [comment]
@oam1551 explain more 😩
