### ISSUE TITLE
zphisher installation

### ISSUE THREAD

**Issue by userundefine** [htr-tech/zphisher#131]
no command found for zphisher.sh and i installed ngrok manually but i dont know what to do next

**Comment by Zumaru711** [comment]
if its still not working try to install it again and make sure to first "cd zphisher" then "chmod +x zphisher.sh" then finnally "bash zphisher" hope this helps

**Comment by userundefine** [comment]
Am required to install packages manually. Unsupported package manager. What
do I do?

**Comment by htr-tech** [comment]
@userundefine try again with the commands from Readme

**Comment by AloneYarasa** [comment]
@htr-tech What is readme?

**Comment by AloneYarasa** [comment]
> @htr-tech Benioku nedir?

I have the same problem and I don't know if I will
