### ISSUE TITLE
Option 3 (Without Hotspot) Error 

### ISSUE THREAD

**Issue by Zumaru711** [htr-tech/zphisher#132]
I am unable to use option 3 but i have ngrok and i a clueless to why it is not working how do i fix it? do [i](url) need to use No-Root, Root, or Sudo plese help here is the error  

Version 2.1 Beta
 [01] LocalHost [Devs Only]
 [02] Ngrok.io [Hotspot Required]
 [03] Ngrok.io [Without Hotspot]

 [~] Select a Port Forwarding option: 3

 [~] Initializing... ( http://127.0.0.1:5555 )

 [~] Launching Ngrok Patched ...

[!]  Ngrok was unable to Generate Link.. Try Again..[!]

**Comment by htr-tech** [comment]
@Zumaru711 First of all extremely sorry for late response .. i was out for a few personal matters 😢 
I have solved that problem in a quick release .. I will soon update the phishing pages also ...
Now you can update the tool & try 😄 
Thanks ❤️
