### ISSUE TITLE
Generates an email instead of Ngrok link.

### ISSUE THREAD

**Issue by EbotRawley** [htr-tech/zphisher#133]
After following the right steps, hotspot always on, did everything right but it keeps generating a link that takes you to write an email.
I heard that I have to download zphisher 2.0. pls hw can I get it?

**Comment by htr-tech** [comment]
@EbotRawley copy the full link 
![image](https://user-images.githubusercontent.com/56682134/101980015-4d9aa300-3c8c-11eb-8dcb-69f2f9b27540.png)


i am updating zphisher ... new version will be online soon 😄

**Comment by EbotRawley** [comment]
@htr-tech I copied the full link, but still the same!
When I paste the link, the first path shows a link but the other part "/***" is just normal text.🤷
Am waiting for the update then 😅

**Comment by htr-tech** [comment]
@EbotRawley First of all extremely sorry for late response .. i was out for a few personal matters 😢 
I have solved that problem in a quick release .. I will soon update the phishing pages also ...
Now you can update the tool & try 😄 
Thanks ❤️
