### ISSUE TITLE
Ngrok was unable to Generate Link.. Try Again..

### ISSUE THREAD

**Issue by W-3B** [htr-tech/zphisher#135]
![Capture](https://user-images.githubusercontent.com/69099263/101937705-d91a2280-3bff-11eb-8418-358f7da7c5bd.PNG)

**Comment by mandontsmile** [comment]
Also facing the same issues

**Comment by sameel0405** [comment]
ok

**Comment by zaraham** [comment]
Try enabling Hotspot and internet connection ... it'll probably generate link

**Comment by W-3B** [comment]
which hotspot, Mobile hotspot, but same problem it didn't work

**Comment by Medole2020** [comment]
Ngrok was unable to Generate Link.. Try Again.. #135

**Comment by Medole2020** [comment]
me too i have this problem bro

**Comment by Medole2020** [comment]
https://prnt.sc/w5kii0

**Comment by htr-tech** [comment]
@Medole2020 @W-3B First of all extremely sorry for late response .. i was out for a few personal matters 😢 
I have solved that problem in a quick release .. I will soon update the phishing pages also ...
Now you can update the tool & try 😄 
Thanks ❤️
