### ISSUE TITLE
I use my mobile data zphisher generates link it work my device but other device open g-mail not my targeted page . What is solution this type error?

### ISSUE THREAD

**Issue by mmalamin** [htr-tech/zphisher#136]

**Comment by htr-tech** [comment]
@mmalamin First of all extremely sorry for late response .. i was out for a few personal matters 😢 
I have solved that problem in a quick release .. I will soon update the phishing pages also ...
Now you can update the tool & try 😄 
Thanks ❤️ @mmalamin
