### ISSUE TITLE
IP. Txt 

### ISSUE THREAD

**Issue by Legendgan** [htr-tech/zphisher#137]
After run the commands, I got two victims, but it's showing...... Something LIKE.... IP. TXT saved, pls what does it mean

**Comment by htr-tech** [comment]
@Legendgan in the base directory of zphisher the victims ip got written in `ip.txt`

& you will find the login info in the `usernames.dat` file ..

you can open those files using cat command

**Comment by vnngv** [comment]
How do I unsubscribe?
