### ISSUE TITLE
Couldn't resolve host: github.com

### ISSUE THREAD

**Issue by LilTrevor** [htr-tech/zphisher#138]

**Comment by LilTrevor** [comment]
I run it in iSH, and when I am write `git clone https://github.com/htr-tech/zphisher`, before this I write `apk update` and `apk add git openssh curl -y`

**Comment by RocketNinja15** [comment]
sounds like a firewall issue

**Comment by htr-tech** [comment]
@LilTrevor that must be internet / firewall issue 😩

**Comment by LilTrevor** [comment]
> @LilTrevor that must be internet / firewall issue 😩

thank you this is firewall issue, internet is good xDD
