### ISSUE TITLE
Ngrok

### ISSUE THREAD

**Issue by sinasayak** [htr-tech/zphisher#14]
Ngrok couldn't create link in termux

**Comment by htr-tech** [comment]
Turn on Hotspot & Try Again . To Keep The Link Active Setup Ngrok Authtoken

**Comment by nagesh-wq** [comment]
Nothing is working here.

**Comment by htr-tech** [comment]
@nagesh-wq   If you have root feature then try with root ! I have Tested zphisher on kali , ubuntu , parrot , termux . There is No error

**Comment by htr-tech** [comment]
@HackedByCATZ serveo is currently down 

& to use ngrok Turn on Hotspot & Try Again

**Comment by HackedByCATZ** [comment]
No i am on the PC and i use https://git-scm.com/ Git Ngrok.io dont work can you tell me why thx! :)

**Comment by htr-tech** [comment]
@HackedByCATZ zphisher is mainly developed for termux & linux

**Comment by HackedByCATZ** [comment]
Ok thx

**Comment by HackedByCATZ** [comment]
Can you do that for Git too? Because Kali doesn't work for me, I don't know why

**Comment by htr-tech** [comment]
@HackedByCATZ  use termux app

**Comment by HackedByCATZ** [comment]
But How i dont have andriod

**Comment by htr-tech** [comment]
@HackedByCATZ  use bluestacks

**Comment by HackedByCATZ** [comment]
ok

**Comment by HackedByCATZ** [comment]
![Screenshot (21)](https://user-images.githubusercontent.com/65786195/82726965-cf72b100-9ce7-11ea-9184-28b12ba6bc51.png)
 Ist this Right???

**Comment by htr-tech** [comment]
is there is hotspt option then use it . or try manual port forwarding . 
![image](https://user-images.githubusercontent.com/56682134/82727075-f641df00-9d09-11ea-8323-b3160263b88d.png)

**Comment by HackedByCATZ** [comment]
![Screenshot (22)](https://user-images.githubusercontent.com/65786195/82727190-4492b600-9ce9-11ea-8414-bd08d96655c2.png)

But for me it is so when I choose ngrok what is it ???

**Comment by HackedByCATZ** [comment]
Can you Help me?

**Comment by htr-tech** [comment]
Reinstall Termux & type `apt update && apt upgrade -y`  & try again

**Comment by HackedByCATZ** [comment]
ok
