### ISSUE TITLE
Ngrok was unable to Generate Link.. Try Again.

### ISSUE THREAD

**Issue by Medole2020** [htr-tech/zphisher#141]
what i can to do hlep me plz guys https://prnt.sc/w5kk11

**Comment by Medole2020** [comment]
![download](https://user-images.githubusercontent.com/76224305/102646739-01fd6300-417e-11eb-819a-564b6ff63ef2.png)

**Comment by htr-tech** [comment]
First of all extremely sorry for late response .. i was out for a few personal matters 😢 
I have solved that problem in a quick release .. I will soon update the phishing pages also ...
Now you can update the tool & try 😄 
Thanks ❤️ @Medole2020
