### ISSUE TITLE
[!]  Ngrok was unable to Generate Link.. Try Again..[!]

### ISSUE THREAD

**Issue by saugatasil** [htr-tech/zphisher#142]
[!]  Ngrok was unable to Generate Link.. Try Again..[!]
How to solve this ?

**Comment by htr-tech** [comment]
First of all extremely sorry for late response .. i was out for a few personal matters 😢 
I have solved that problem in a quick release .. I will soon update the phishing pages also ...
Now you can update the tool & try 😄 
Thanks ❤️

**Comment by Medole2020** [comment]
no bro it did not worked

**Comment by htr-tech** [comment]
@Medole2020 update zphisher tool 😩
