### ISSUE TITLE
link doesn't work 

### ISSUE THREAD

**Issue by iqubal420** [htr-tech/zphisher#143]
zphisher link work in my mobile,  but don't work other mobile .😢

**Comment by htr-tech** [comment]
@iqubal420 use ngrok ( option 2 or 3 )

**Comment by iqubal420** [comment]
![Screenshot_20201220-204544](https://user-images.githubusercontent.com/59547248/102720353-e2dd0d80-4304-11eb-8d30-44e0b0444ca9.png)

ভিক্টিমের মোবাইলে এটা আসে।

**Comment by htr-tech** [comment]
@iqubal420 ngrok er link highest 2 hour active thake 😢
