### ISSUE TITLE
Zphisher 

### ISSUE THREAD

**Issue by Sherydark8986** [htr-tech/zphisher#145]
[+] Tool Created by htr-tech (tahmid.rayat)       
 [~] Installing packages..
 [~] Downloading Ngrok..                              [~] Downloading Ngrok Patch..
                                                      [!] Error [!] Install Ngrok Manually.
~/zphisher $
This is my issue what i do with him

**Comment by htr-tech** [comment]
@Sherydark8986 host phishing pages on localhost [ option 1 ]

Download ngrok from ngrok.com... & forward the localhost port 5555 😩

**Comment by weewuxian** [comment]
URL 1 is not generate. Why?

**Comment by weewuxian** [comment]
URL 1 is not generate in zphisher tool why 
What i do?
I am very sad plzz help me sir
