### ISSUE TITLE
[!] Ngrok was unable to Generate Link.. Try Again..[!] #142

### ISSUE THREAD

**Issue by Medole2020** [htr-tech/zphisher#146]
[!] Ngrok was unable to Generate Link.. Try Again..[!] #142

**Comment by htr-tech** [comment]
@Medole2020 update the tool ... problem fixed

**Comment by Bish283** [comment]
How can i upfate the tool??

**Comment by htr-tech** [comment]
@Bish283 simply remove the tool by `rm -rf zphisher `  & then clone again 😩
