### ISSUE TITLE
Victim 

### ISSUE THREAD

**Issue by Sherydark8986** [htr-tech/zphisher#147]
Victim open but say dns no network no and problom of link send to victims

**Comment by Zer0C00lness** [comment]
Oh really

€€/\/\@¡\¡’-|?0

**Comment by Zer0C00lness** [comment]
So you can send to me

€€/\/\@¡\¡’-|?0

**Comment by Sherydark8986** [comment]
How can i u subscribe

**Comment by Sherydark8986** [comment]
What i send u just tell me clear

**Comment by htr-tech** [comment]
@Zer0C00lness you have to keep your terminal / termux session alive 😩

**Comment by Zer0C00lness** [comment]
Ok sweet thank you I smoke so much weed n shoot so much dope my short term sucks

**Comment by Zer0C00lness** [comment]
Thank you sen sai thank you happy new year

**Comment by Sherydark8986** [comment]
Ofline not available

**Comment by Zer0C00lness** [comment]
Well of course offline not available I'm just gon I'm just gonna shut upna oh man thank you

**Comment by Zer0C00lness** [comment]
Can we do that again thank you

**Comment by Zer0C00lness** [comment]
So actually in reality dude this will be the smartest and fastest way fuck keyboard

**Comment by Sherydark8986** [comment]
Tnxx

**Comment by Zer0C00lness** [comment]
Your welcome and thank you
