### ISSUE TITLE
Zphisher

### ISSUE THREAD

**Issue by begginer12283** [htr-tech/zphisher#148]
I followed every step but it is showing this ______      _     _     _                              |___  /     | |   (_)   | |                                / / _ __ | |__  _ ___| |__   ___ _ __                  / / | '_ \| '_ \| / __| '_ \ / _ \ '__|                / /__| |_) | | | | \__ \ | | |  __/ |                  /_____| .__/|_| |_|_|___/_| |_|\___|_|                        | |                                                     |_|               Version 2.1 Beta                                                                     [+] Tool Created by htr-tech (tahmid.rayat)                                                                   [~] Installing packages..                               [~] Downloading Ngrok..

Please help

**Comment by htr-tech** [comment]
@begginer12283 keep an active net connection
