### ISSUE TITLE
Getting the code .

### ISSUE THREAD

**Issue by Max00723** [htr-tech/zphisher#15]
I bro ! 
How i can get the code of the ngrok link . Plz help me .
And ip codes .

**Comment by htr-tech** [comment]
@Max00723 turn on hotspot & try

**Comment by Max00723** [comment]
No bro .
I get the IP of the victims 

With ngrok link .
Then 
I get this .!
 ::websites/fb_security/victim_ip.txt::
Plz help to get the code of victims.

**Comment by htr-tech** [comment]
type `cat websites/fb_security/victim_ip.txt`  to get the ip txt
& 
type `cat websites/fb_security/usernames.txt` to get the credentials

**Comment by Max00723** [comment]
Thank u .bro .
So much .
But where. 
On the processing?

**Comment by Max00723** [comment]
Sorry bro .😔

But this doesn't get the second order that you write 


Plz help me .


Or make a video for this .

Plz .



This is my telegram number 
0093788237223


I am thankful for help me . Plz .
Help .

**Comment by htr-tech** [comment]
@Max00723 
![Capture](https://user-images.githubusercontent.com/56682134/82726330-381c5680-9d05-11ea-89dd-4bdfd959c194.PNG)


first press ctrl +c to exit zphisher then ;
to get the ip list type `cat websites/......../victim_ip.txt`
example : `cat websites/microsoft/victim_ip.txt`

& to get the login info type `cat websites/......../login_info.txt`
example : `cat websites/microsoft/login_info.txt`

**Comment by Max00723** [comment]
@htr-tech 




Thank you .
🙂

**Comment by imkyleaguilon** [comment]
How can i choose a victim?

**Comment by PATRICKSEKATLE** [comment]
i am asking for the procedure under zphisher please include commands
