### ISSUE TITLE
No Ngrok link generated

### ISSUE THREAD

**Issue by see305be** [htr-tech/zphisher#152]
(complete) link is not generated on Termux
![Screenshot_20201229-165515_Termux](https://user-images.githubusercontent.com/73776168/103296793-23204800-49f7-11eb-8249-5bd27b12cf3c.jpg)

**Comment by htr-tech** [comment]
@see305be turn on device hotspot & try again

**Comment by delight01** [comment]
https://github.com/htr-tech/zphisher/issues/152#issue-775964895
