### ISSUE TITLE
Link issue

### ISSUE THREAD

**Issue by drey0735** [htr-tech/zphisher#154]
When I send the link or open it to try. It redirecting me to google recovery sign in. Please fix it. Im using the latest patch of zphisher

**Comment by Zer0C00lness** [comment]
It's working perfectly fine you use that window n that is what u would share with someone including your right file path to lead them up to signing into google

**Comment by drey0735** [comment]
I didnt understand very well. Can you explain it more to me?

**Comment by htr-tech** [comment]
@drey0735 send that link to others in order to collect user & pass from them 😩

**Comment by drey0735** [comment]
Yes. I k now that. What I meant was the link is broken and sometimes not
creating any link or sometimes if i send link, it doesn't work on their
device.

**Comment by htr-tech** [comment]
@drey0735 keep your terminal session alive 😩 otherwise ngrok will be unable to keep the tunnel
