### ISSUE TITLE
Failed to complete tunnel connection

### ISSUE THREAD

**Issue by GamingMetJayden** [htr-tech/zphisher#159]
```
 The connection to https://XXXXXXXXXXXX.ngrok.io was successfully tunneled to your ngrok client, but the client failed to establish a connection to the local address localhost:8080.

Make sure that a web service is running on localhost:8080 and that it is a valid address.

The error encountered was: dial tcp [::1]:8080: connect: connection refused 
```

**Comment by htr-tech** [comment]
@GamingMetJayden you can update the zphisher version & try again..

& if you are root then you have try with root permission 😄

**Comment by anonymouskingrs** [comment]
how do i update the zphisher?

> @GamingMetJayden você pode atualizar a versão do zphisher e tentar novamente ..
> 
> E se você é root, então você deve tentar com permissão de root 😄

how do i update the zphisher?

**Comment by htr-tech** [comment]
> how do i update the zphisher?
> 
> > @GamingMetJayden você pode atualizar a versão do zphisher e tentar novamente ..
> > E se você é root, então você deve tentar com permissão de root 😄
> 
> how do i update the zphisher?

cd zphisher
git pull origin


or delete zphisher dir

& clone again

**Comment by htr-tech** [comment]
maybe thats because of root user permission.. try with root if you are root user
