### ISSUE TITLE
Facebook page is broken.

### ISSUE THREAD

**Issue by kbtamang** [htr-tech/zphisher#16]
Please update the Facebook page in system. It appears that Facebook face is broken in here.

**Comment by htr-tech** [comment]
> Please update the Facebook page in system. It appears that Facebook face is broken in here.

Page Updated

**Comment by inge300101** [comment]
Facebook mobile banner is broken pls fix or tell us how to fix it

**Comment by MorganDavid4** [comment]
Tell me how to fix it

**Comment by htr-tech** [comment]
@MorganDavid4 just chang the logo src in mobile.html

**Comment by mod4xbox** [comment]
> @MorganDavid4 just chang the logo src in mobile.html

Hi!
Awesome tool. Can you point me where is this logo src exactly? I tried looking for it in mobile.html & in login.html and even went as far as digging into the CSS files... but to no avail.

Your help will be appreciated!
