### ISSUE TITLE
Link issue

### ISSUE THREAD

**Issue by Bish284** [htr-tech/zphisher#163]
When i try to generate the links the url 1 is empty and when i copy the url 2 and paste it in google it dont show me the phishing site but it does a simple search in google for free followers

https://user-images.githubusercontent.com/76913391/104297546-ae0b4300-54cb-11eb-92c4-0e3db843d380.mp4

**Comment by htr-tech** [comment]
@Bish284 when u turn your hotspot on .. the wifi will be stopped automatically .. 
![image](https://user-images.githubusercontent.com/56682134/104299700-bb3a2900-54ef-11eb-8acd-00b5b1467cd6.png)

so if you are using wifi then use option 3 .. that doesn't need hotspot

**Comment by Bish284** [comment]
Yes but look it doesn put me in the phishing site again 

https://user-images.githubusercontent.com/76913391/104301138-f6c4fb00-54cf-11eb-8d1f-18fc260b8549.mp4

**Comment by htr-tech** [comment]
😩 ah lol... then try manual method

1. host pages in localhost 
2. Download & setup ngrok manually
3. Forward the Localhost Port 😢

**Comment by htr-tech** [comment]
or i can host it on online :) if you want then ,,,

**Comment by htr-tech** [comment]
@Bish284 Go to This Link : [LINK](https://repl.it/@htrtech/zphisher)

tap on console
![image](https://user-images.githubusercontent.com/56682134/104303504-5c2ae300-54f4-11eb-82a2-aa8653cb0080.png)

then simply press the play button
![image](https://user-images.githubusercontent.com/56682134/104303581-7238a380-54f4-11eb-8064-a4ba0b8c746a.png)

![image](https://user-images.githubusercontent.com/56682134/104303641-8a102780-54f4-11eb-9629-ffd6b9ec1b16.png)
Create a Repl.it accout & fork if you want a private repl

**Comment by Bish284** [comment]
Thanks you so muchh but i have an another question, how can i see the old victims??

**Comment by htr-tech** [comment]
![image](https://user-images.githubusercontent.com/56682134/104307684-bda18080-54f9-11eb-8832-13c740c6b1e2.png)
![image](https://user-images.githubusercontent.com/56682134/104307758-d90c8b80-54f9-11eb-94b6-0dacd867f47b.png)

check the `usernames.dat` file

by typing `cat usernames.dat` or u can use any text editor

**Comment by Bish284** [comment]
Sorry again but do you have any way to download manually ngrok because i did it from youtube videos but still says reconnecting

**Comment by htr-tech** [comment]
@Bish284 dude turn on mobita data connection + Hotspot 

or use this ngrok patched version 

https://bin.equinox.io/a/e93TBaoFgZw/ngrok-2.2.8-linux-arm.zip

**Comment by liran5536** [comment]
i chose cloudflared and it show me 2 links but they dont work even if i try to open them with other computers
