### ISSUE TITLE
Incomplete Tunnel url

### ISSUE THREAD

**Issue by SamitHota** [htr-tech/zphisher#168]
After creating url it's showing blank in url1 field and wrong/incomplete url in url2 field, means it doesn't showing any domain extention 
![Screenshot_2021-01-22-10-05-44-59](https://user-images.githubusercontent.com/67710768/105447156-aac94180-5c99-11eb-8d78-cc4388be6d38.png)

**Comment by htr-tech** [comment]
@SamitHota  turn on hotspot & try ngrok with hotspot ..

or you can simply run zphisher on your browser : [Link](https://repl.it/@htrtech/zphisher-mirror#README.md)

**Comment by Issah-star** [comment]
Same problem

**Comment by htr-tech** [comment]
> Same problem

turn on hotspot & try ngrok with hotspot ..
or you can simply run zphisher on your browser : [Link](https://repl.it/@htrtech/zphisher-mirror#README.md)

**Comment by MaliciousJoker** [comment]
I've been struggling with this thing for a long time now

how do u run ngrok and only output the link

**Comment by htr-tech** [comment]
@MaliciousJoker run zphisher then select any phishing module .. after that turn on your device hotspot & from the port forwarding options use ngrok [ hotspot ]

**Comment by MaliciousJoker** [comment]
no like ive trying create a script like urs just for practice
i really admired ur script to wanted to improve my skill by making
something like it


problem is  i don't know how to run ngrok then output Only link

make a script that run ngrok and print only the ngrok link

**Comment by madcaat** [comment]
I get this message whenever i paste my ngrok link on broswer "ngrok gateway error 
The server returned an invalid or incomplete HTTP response" 
Please help

**Comment by htr-tech** [comment]
Checkout this short tutorial .. for ngrok without Hotspot...

https://drive.google.com/file/d/1nkhpj8MKRTqQbK1v3OuUJtaxcRdEp-M4/view?usp=sharing

**Comment by grenoxx** [comment]
Hello, I am the developer of LordPhish and I really liked your banners, where did you generate them? I would like to add a little extra banner in the next update ... Thanks for your attention

**Comment by htr-tech** [comment]
@grenoxx https://fsymbols.com/generators/carty/
