### ISSUE TITLE
facebook login page doesn't show properly, they are misaligned and flat without colors. 

### ISSUE THREAD

**Issue by premjit1998** [htr-tech/zphisher#170]

**Comment by htr-tech** [comment]
@premjit1998 bro all the pages are working 😩 check your internet connection 😩 


![Screenshot_2021-01-27 Facebook – log in or sign up(1)](https://user-images.githubusercontent.com/56682134/106021399-f68f4700-60ee-11eb-87bf-a4a9cc583b49.png)
![Screenshot_2021-01-27 Facebook – log in or sign up](https://user-images.githubusercontent.com/56682134/106021407-f8590a80-60ee-11eb-9803-5ab53d174303.png)

**Comment by premjit1998** [comment]
thanks for your reply but why this is happend with me is this on to apps to different types of pages
![Screenshot_20210128-100048](https://user-images.githubusercontent.com/72644801/106090594-97621e80-6150-11eb-8643-6e0996f5fc2d.png)
![Screenshot_20210128-100013](https://user-images.githubusercontent.com/72644801/106090599-9a5d0f00-6150-11eb-9b01-e780147313ef.png)

**Comment by htr-tech** [comment]
@premjit1998 maybe that's because of JavaScript or the internet connection 😩 

try enabling JavaScript 😩

**Comment by premjit1998** [comment]
Ok

**Comment by yesayasitumorang** [comment]
can i ask you something about termux ??i have a problem about that

Pada tanggal Kam, 28 Jan 2021 12.36, premjit1998 <notifications@github.com>
menulis:
