### ISSUE TITLE
Ngrok.io link problem

### ISSUE THREAD

**Issue by jwhdnta** [htr-tech/zphisher#174]
I have tried this program in termux for android application. The problem that I got is ngrok.io link is not generated well. You can look at the picture which I attached. What can I do to fix it? Cause it happen for version 2.1.
![SmartSelect_20210130-222928_Termux](https://user-images.githubusercontent.com/50068591/106360371-a3193500-634a-11eb-9c20-fab628092072.jpg)

**Comment by htr-tech** [comment]
@jwhdnta turn on your device hotspot & try again .. hope it works 👼

**Comment by jwhdnta** [comment]
I have try it too, but I got the same result like the picture that I attached before

**Comment by htr-tech** [comment]
@jwhdnta then try to use it from this link [LINK](https://repl.it/@htrtech/zphisher)

**Comment by jwhdnta** [comment]
Oke, thanks for the answer. It's working
