### ISSUE TITLE
ngrok without hotspot not working

### ISSUE THREAD

**Issue by jordonbinns** [htr-tech/zphisher#175]
Worked once yesterday but isnt working today, any ideas?

**Comment by htr-tech** [comment]
try a few more times .. 😩 if not then save a ngrok token & try again 💯

**Comment by jordonbinns** [comment]
Thanks for replying. I already saved an ngrok token from the beginning
tho.. So I just gotta try till it works?

**Comment by htr-tech** [comment]
@jordonbinns or you can just try using this  link [click here](https://repl.it/@htrtech/zphisher)

**Comment by jordonbinns** [comment]
It worked! Thanks a lot.
