### ISSUE TITLE
Tunnel Not Found

### ISSUE THREAD

**Issue by jebz69** [htr-tech/zphisher#177]
I'be been having issues with the link created through NGROK. The link pulls up on the pc I am using to create the link, but when trying to open on a mobile device it pulls up a white screen saying "tunnel not found" 
I've updated everything, my Connection is working, I'm out of ideas on how to fix this. Anyone have any idea what's going on with it?

**Comment by htr-tech** [comment]
@jebz69 you have to keep your terminal open ..

**Comment by jebz69** [comment]
My terminal is open. WiFi is connected. Internet works. Ping works as well. I'm thinking it's an ngrok issue or a port issue.

**Comment by htr-tech** [comment]
> My terminal is open. WiFi is connected. Internet works. Ping works as well. I'm thinking it's an ngrok issue or a port issue.

then try using it from this link : [CLICK HERE](https://repl.it/@htrtech/zphisher)

**Comment by manijattana464** [comment]
I have confusion

**Comment by htr-tech** [comment]
> I have confusion

yes ?

**Comment by Fortune212-hack** [comment]
Please how can i clone Nigerian Facebook?
