### ISSUE TITLE
Ngrok patch not working

### ISSUE THREAD

**Issue by amitsaini74** [htr-tech/zphisher#183]
Start without hotspot not working i think you should fix it

**Comment by htr-tech** [comment]
sometimes that doesn't work on some devices .. i have made e short solution .. better check it & tell me if you have any problem 


https://drive.google.com/file/d/1nkhpj8MKRTqQbK1v3OuUJtaxcRdEp-M4/view?usp=sharing

**Comment by htr-tech** [comment]
I have fixed these problems in latest update,,

try re-cloning the tool .. this time no hotspot is required !!!

rm -rf ~/zphisher
git clone https://github.com/htr-tech/zphisher.git
cd zphisher
bash zphisher.sh
use option 2 Ngrok 💯 if this works then plz let me know 😄
