### ISSUE TITLE
Write for us

### ISSUE THREAD

**Issue by thexwts** [htr-tech/zphisher#187]
I'm sorry for writing here but it was the only way to contact you,

You are good in the cybersecurity field? Then you can write for us about your own tool on GitHub and the use of it.
Your article will be published with your name and a link to your website and social media accounts if you want.
please reply to this Email:kalitutwrite @ gmail .com
Walid Salame
www. kalitut .com
Twitter: @xKaliSec

**Comment by htr-tech** [comment]
okay ... i will try 💘
