### ISSUE TITLE
Link not showing

### ISSUE THREAD

**Issue by Jerukpurut** [htr-tech/zphisher#188]
I think it has something to do with ngrok

**Comment by htr-tech** [comment]
@Jerukpurut  I have fixed these problems in latest update,,

try re-cloning the tool .. this time no hotspot is required !!!

- `rm -rf ~/zphisher`
- `git clone https://github.com/htr-tech/zphisher.git`
- `cd zphisher`
- `bash zphisher.sh`

use option 2 Ngrok 💯 if this works then plz let me know 😄

**Comment by dima20003** [comment]
How to reclone

**Comment by htr-tech** [comment]
> @Jerukpurut I have fixed these problems in latest update,,
> 
> try re-cloning the tool .. this time no hotspot is required !!!
> 
> * `rm -rf ~/zphisher`
> * `git clone https://github.com/htr-tech/zphisher.git`
> * `cd zphisher`
> * `bash zphisher.sh`
> 
> use option 2 Ngrok 💯 if this works then plz let me know 😄

@dima20003 follow the commands

**Comment by dima20003** [comment]
Thank You very much 🤩. Everything works very good.

**Comment by tropicaldk** [comment]
I don't understand it shows me url 1 but not 2
