### ISSUE TITLE
Tool one

### ISSUE THREAD

**Issue by NishaVirus** [htr-tech/zphisher#189]

**Comment by htr-tech** [comment]
?? 😕

**Comment by hello356765** [comment]
@htr-tech
How can I change the site name
Like google phish page name is gmail
How can I change the name to google
Please help
Sir 
Thanks

**Comment by htr-tech** [comment]
> @htr-tech
> How can I change the site name
> Like google phish page name is gmail
> How can I change the name to google
> Please help
> Sir
> Thanks

edit the phishing pages on `.sites` directory
