### ISSUE TITLE
error

### ISSUE THREAD

**Issue by usser-cmd** [htr-tech/zphisher#19]
told me error when i enter commend bash zphisher.sh everything is good but i dont see anything mean i thing chose anything and just write PHP is not installed!install it.what should i do i download it compeletli
![1](https://user-images.githubusercontent.com/66305751/83509553-df0ca980-a4e0-11ea-8e2d-b855d419726c.PNG)
what should i do i want use this

**Comment by htr-tech** [comment]
@usser-cmd install php & try

**Comment by usser-cmd** [comment]
@htr-tech  can you give the link php

**Comment by usser-cmd** [comment]
i need it thank for your help

**Comment by htr-tech** [comment]
try

apt install php 


i am not sure cause , i haven't use mingw before
