### ISSUE TITLE
Link not showing up

### ISSUE THREAD

**Issue by C0sm0s-Creat0r** [htr-tech/zphisher#190]
I had a look at the issues currently open, and tried re-cloning it. Yet I am still getting this problem.

Also is there anyway to attach my own ngrok account.

**Comment by htr-tech** [comment]
> I had a look at the issues currently open, and tried re-cloning it. Yet I am still getting this problem.
> 
> Also is there anyway to attach my own ngrok account.

which device are you using ?

if termux then type `apt install proot resolv-conf -y`
then try the newest build of zphisher ,... 
if link doesn't appear try with hotspot 😖 

to attach ngrok token copy the token 

`./~/zphisher/.server/ngrok authtoken <token>

**Comment by dima20003** [comment]
![Screenshot_20210301-123647~2.png](https://user-images.githubusercontent.com/56720856/109486104-21244500-7a8b-11eb-9731-9f9484c5063b.png)

**Comment by htr-tech** [comment]
@dima20003 remove the < > 😕

**Comment by C0sm0s-Creat0r** [comment]
I'm on macbook air. Which also means that the method to set the token isn't working.

**Comment by htr-tech** [comment]
> I'm on macbook air. Which also means that the method to set the token isn't working.

simple go to zphisher directory by excuting `cd zphisher`
then go to the `.server` folder ... there you will find ngrok excutable file..

then run ./ngrok authtoken <your token>

**Comment by C0sm0s-Creat0r** [comment]
> > I'm on macbook air. Which also means that the method to set the token isn't working.
> 
> simple go to zphisher directory by excuting `cd zphisher`
> then go to the `.server` folder ... there you will find ngrok excutable file..
> 
> then run `./ngrok authtoken <your token>`

I tried this previously as I believed that was how it worked. The output is. 'zsh: exec format error: ./ngrok'

**Comment by C0sm0s-Creat0r** [comment]
I managed to fix both things by building ngrok from the source into the .server folder.
