### ISSUE TITLE
Tunnel Connection not completet

### ISSUE THREAD

**Issue by Hellcat04** [htr-tech/zphisher#191]
Hey guys!
So im new with Linuy and i need your help.
I startet ngrok and created a server if i connect with that link everything works fine.
but if i then start zphisher and use the link that zphisher created i get this error. I also tried with changing the roules in network setting, but nothing works.
Please Help

this is the site that i get if i use zphishers link
and the other one if i use the ngrok link
![nadhsj](https://user-images.githubusercontent.com/79995444/109950921-617b0180-7cdd-11eb-90d8-e96b560e0c9a.JPG)
![nadhsj 2](https://user-images.githubusercontent.com/79995444/109950938-65a71f00-7cdd-11eb-9490-1a078163f7c5.JPG)

**Comment by htr-tech** [comment]
try with sudo 😕

**Comment by Hellcat04** [comment]
what do you mean with sudo


> try with sudo 😕

**Comment by Hellcat04** [comment]
> try with sudo 😕

i tried to run it with sudo instead of bash ist that what you meant?

**Comment by htr-tech** [comment]
> > try with sudo 😕
> 
> i tried to run it with sudo instead of bash ist that what you meant?

i said to run as `sudo bash zphisher.sh` 😕

**Comment by Hellcat04** [comment]
> > > try with sudo 😕
> > 
> > 
> > i tried to run it with sudo instead of bash ist that what you meant?
> 
> i said to run as `sudo bash zphisher.sh` 😕

now it worked thanks very much!
