### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by hello356765** [htr-tech/zphisher#196]
When I use mobile open the google new phishing page
The sign bottom is weird
How to solve this
Please help
Thanks everyone

**Comment by graysuit** [comment]
@hello356765 
Put screenshot here. 
This behavior not present in my case.

**Comment by htr-tech** [comment]
> When I use mobile open the google new phishing page
> The sign bottom is weird
> How to solve this
> Please help
> Thanks everyone

Put screenshot here.
This behavior not present in my case. (2) 🐒🐒

**Comment by cybernoob13123** [comment]
@htr-tech 
Sir how can I change linux ip address
To a specific number exactly
Such as 104.28.22.115
Please help
Important for me

**Comment by MaliciousJoker** [comment]
Hey man

You guys not recruiting or something?

Ive been learning and progressing and i think its time to take my skill to
the next level

Can i join y'all?

**Comment by htr-tech** [comment]
> @htr-tech
> Sir how can I change linux ip address
> To a specific number exactly
> Such as 104.28.22.115
> Please help
> Important for me

submit an issue on stackoverflow.. many experts will be answering you
