### ISSUE TITLE
Victim link

### ISSUE THREAD

**Issue by tricker3333** [htr-tech/zphisher#2]
While using serveo.net the victim link is blank
What to do plz tell me

**Comment by htr-tech** [comment]
Serveo is Down. Use Localhostrun or Ngrok. To use Ngrok First turn on Hotspot & Use it.

**Comment by RaviNani024** [comment]
Anyone please hack facebook

**Comment by RaviNani024** [comment]
Anyone please hack facebook

**Comment by RaviNani024** [comment]
My whatsapp no. 9705116807
If anyone know facebook hacking message me

**Comment by eddie69-hecker** [comment]
Why is my url 1 is blank and url 2 not working
