### ISSUE TITLE
Tunnel Not Found

### ISSUE THREAD

**Issue by jebz69** [htr-tech/zphisher#200]
I have tried everywhere to find a resolution to this issue. When using the link provided by Zphisher it brings up "Ngrok tunnel not found" I have updated kali linux and my wifi is working as it should. I cant seem to find a resolution for the link to work. Can anyone help please?

**Comment by htr-tech** [comment]
@jebz69 try using sudo & keep your terminal session alive 😐

**Comment by jebediahhhh** [comment]
Yes, even running as root and keeping the terminal open, this is still happening. Opening the link on another device should be bring up the page but it just brings up a page stating that the tunnel was not found.

**Comment by htr-tech** [comment]
@jebediahhhh then i would recommend you to use it on goole cloud shell

or [repl.it](https://repl.it/@htrtech/zphisher)

**Comment by htr-tech** [comment]
![image](https://user-images.githubusercontent.com/56682134/111114476-7da85980-858d-11eb-9dde-9de2f348cc96.png)

if this arrives then your ngrok connection must've shut down

**Comment by jebz69** [comment]
How do I start up my ngrok connection again?

**Comment by htr-tech** [comment]
> How do I start up my ngrok connection again? Other than ./ngrok http 80 or ./ngrok http 8080 because those links provided give the same outcome. A 502 error.

then i would recommend you to use it on google cloud shell

or [repl.it](https://repl.it/@htrtech/zphisher)  {2}

**Comment by theCYBERbro** [comment]
I have the same error when trying to open the link outside of the local network. 
Running `sudo ngrok http 8080` won't fix the problem.
I've also tried `sudo ngrok http 8080 --region eu` witch didn't work either.

Tested on Ubuntu 20.04.2 LTS

**Comment by htr-tech** [comment]
> I have the same error when trying to open the link outside of the local network.
> Running `sudo ngrok http 8080` won't fix the problem.
> I've also tried `sudo ngrok http 8080 --region eu` witch didn't work either.
> 
> Tested on Ubuntu 20.04.2 LTS

use from here https://repl.it/@htrtech/zphisher
