### ISSUE TITLE
issue 

### ISSUE THREAD

**Issue by R1K6N** [htr-tech/zphisher#201]
when zphisher generates a link i click on it on a computer it works but when i use my phone on safari it says could not find server

**Comment by htr-tech** [comment]
@R1K6N generate link with ngrok

**Comment by R1K6N** [comment]
I am but it is still not working

**Comment by htr-tech** [comment]
keep your terminal alive

**Comment by R1K6N** [comment]
how ?

**Comment by htr-tech** [comment]
ar you usin kali linux  or termux ?

**Comment by R1K6N** [comment]
kali linux

**Comment by htr-tech** [comment]
try with sudo

`sudo bash zphisher.sh`

**Comment by R1K6N** [comment]
ok thank you i will try and i will inform you if it worked

**Comment by R1K6N** [comment]
![D1D7238E-90A3-4E52-9ABC-134B8A860232](https://user-images.githubusercontent.com/80853567/111626414-a5e6c100-87f6-11eb-9e2b-2a32a344bbbf.jpeg)

it did not work

**Comment by R1K6N** [comment]
but it worked on my computer i need it to work on the phone

**Comment by htr-tech** [comment]
> but it worked on my computer i need it to work on the phone

uh .. try in another browser plz 😖

**Comment by htr-tech** [comment]
did you closed the terminal on your pc ?

**Comment by R1K6N** [comment]
the terminal is still on i will try it on another browser

**Comment by R1K6N** [comment]
it worked thank you ! (i’m still new i’ve had lali for a few days )
