### ISSUE TITLE
$'\r': command not found

### ISSUE THREAD

**Issue by PatrickMitchellUI** [htr-tech/zphisher#204]
Running KaliLinux "large" install on wsl with all deps installed manually

zphisher.sh: line 2: $'\r': command not found
zphisher.sh: line 7: $'\r': command not found
zphisher.sh: line 16: $'\r': command not found
zphisher.sh: line 17: $'\r': command not found
zphisher.sh: line 19: $'\r': command not found
zphisher.sh: line 20: $'\r': command not found
zphisher.sh: line 21: $'\r': command not found
zphisher.sh: line 94: $'\r': command not found
zphisher.sh: line 95: $'\r': command not found
zphisher.sh: line 102: $'\r': command not found
zphisher.sh: line 115: syntax error near unexpected token `$'{\r''
'phisher.sh: line 115: `exit_on_signal_SIGINT() {

**Comment by PatrickMitchellUI** [comment]
removing the linebreaks made those errors dissapear but program breaks at every new section eg: kill_pid()

**Comment by htr-tech** [comment]
`phisher.sh`

looks like you have tried to edit the script .. thats why linebreak occurs 😕 

clone the original script to avoid linebreaks
