### ISSUE TITLE
اینستاگرام 

### ISSUE THREAD

**Issue by amirmr47** [htr-tech/zphisher#21]

**Comment by Smartbizzy** [comment]
Please teach me the commands to install zphisher in my Termux

**Comment by htr-tech** [comment]
* `apt update`
* `apt install git python python2 -y`
* `git clone git://github.com/htr-tech/zphisher.git`
* `cd zphisher`
#### > Run : `bash zphisher.sh`

Turn device hotspot & try again

**Comment by Smartbizzy** [comment]
Thanks
