### ISSUE TITLE
facebook site broken

### ISSUE THREAD

**Issue by J35t3rOP** [htr-tech/zphisher#212]
facebook site broken

**Comment by htr-tech** [comment]
> facebook site broken

okay i will fix it 😄

**Comment by htr-tech** [comment]
done

**Comment by taamifunes** [comment]
How I used it? I don't understand 😭 can't install it, please help!!

**Comment by htr-tech** [comment]
> How I used it? I don't understand 😭 can't install it, please help!!

checkout the readme

**Comment by taamifunes** [comment]
> > How I used it? I don't understand 😭 can't install it, please help!!
> 
> checkout the readme

I have to download something special to be able to access the phishing pages? sorry, I don't speak much english and its difficult for me to install it

**Comment by yesayasitumorang** [comment]
Did you make the zphisher

Pada tanggal Jum, 9 Apr 2021 00.58, Tahmid Rayat ***@***.***>
menulis:
