### ISSUE TITLE
Error on victim device

### ISSUE THREAD

**Issue by Pythoniccoders** [htr-tech/zphisher#213]
Link is not opening on victim's device . It's showing "tunnel ngrok.io not found. Please help me😭. I'm so confused right now. Can anybody help me out?.

**Comment by htr-tech** [comment]
> Link is not opening on victim's device . It's showing "tunnel ngrok.io not found. Please help me😭. I'm so confused right now. Can anybody help me out?.

dont close your terminal/termux

**Comment by Pythoniccoders** [comment]
> > Link is not opening on victim's device . It's showing "tunnel ngrok.io not found. Please help me😭. I'm so confused right now. Can anybody help me out?.
> 
> dont close your terminal/termux

Ya I'm not closing it

**Comment by Pythoniccoders** [comment]
> > Link is not opening on victim's device . It's showing "tunnel ngrok.io not found. Please help me😭. I'm so confused right now. Can anybody help me out?.
> 
> dont close your terminal/termux

> > Link is not opening on victim's device . It's showing "tunnel ngrok.io not found. Please help me😭. I'm so confused right now. Can anybody help me out?.
> 
> dont close your terminal/termux

Do you have some other solution?

**Comment by htr-tech** [comment]
are you quitting the zphisher session ? `tunnel ngrok.io not found` this problem occurs when someone closes the zphisher session 👀

**Comment by Pythoniccoders** [comment]
> are you quitting the zphisher session ? `tunnel ngrok.io not found` this problem occurs when someone closes the zphisher session 👀

No, I'm not

**Comment by Pythoniccoders** [comment]
Can we talk personally. Like on insta or telegram.

**Comment by htr-tech** [comment]
> Can we talk personally. Like on insta or telegram.

Telegram : `H454N_T4hM1D`
