### ISSUE TITLE
Can I add ngrok authtoken on replit.com/@htrtech/zphisher and if yes, how?

### ISSUE THREAD

**Issue by noblica123** [htr-tech/zphisher#215]

**Comment by htr-tech** [comment]
if you want to add ngrok auth token then just simply go to `zphisher/.server` directory & excute

`./ngrok authtoken ***********`

**Comment by noblica123** [comment]
Sorry for stupid questions, but how do I exactly do that? Do I fork it and then somehow execute or how?

**Comment by htr-tech** [comment]
> Sorry for stupid questions, but how do I exactly do that? Do I fork it and then somehow execute or how?

in repl.it just type cd `.server` & then type `./ngrok authtoken ***********`

**Comment by noblica123** [comment]
Thanks for fast answers, I did it right. One more question, how can I add Instagram logo on instagram traditional page? Because logo is not showing

**Comment by noblica123** [comment]
What does ya mean? I don't know how to add instagram logo or is it possible so I'm asking you if you could tell me how to do it or if you could fix it or something, thanks!

**Comment by htr-tech** [comment]
ok i will update it soon

**Comment by noblica123** [comment]
That would be awesome, thanks

**Comment by noblica123** [comment]
Do you know when will you have time to do it?

**Comment by htr-tech** [comment]
Pages Fixed
