### ISSUE TITLE
No link 

### ISSUE THREAD

**Issue by amirreza-fb** [htr-tech/zphisher#219]
Hello, please help me
I used your tool before and it was not a problem, but today, when I wanted to use it, everything went to the web. In Ahar, it gave me a link to @ at the end, which when I searched, Google did not find a site, and I deleted @ and again I searched but did not find a site. Thank you for helping me solve my problem or if you can re-upload the old files of the tool, thank you.
`                                                                           
  ░▀▀█░█▀█░█░█░▀█▀░█▀▀░█░█░█▀▀░█▀▄                                         
  ░▄▀░░█▀▀░█▀█░░█░░▀▀█░█▀█░█▀▀░█▀▄                                         
  ░▀▀▀░▀░░░▀░▀░▀▀▀░▀▀▀░▀░▀░▀▀▀░▀░▀ 2.1                                     
                                                                           
[-] URL 1 :                                                                
                                                                           
[-] URL 2 : http://get-1000-followers-for-instagram@                       
                                                                           
[-] Waiting for Login Info, Ctrl + C to exit...^C      `

**Comment by dhanushkkarh** [comment]
same. facing same issue. i guess it has something to do with ngrok. tried resetting. no use

**Comment by playboy1212** [comment]
After getting a link what do i do? The link wont connect, but if someone click it an ip come up , what do i do with that ?

**Comment by htr-tech** [comment]
> Hello, please help me
> I used your tool before and it was not a problem, but today, when I wanted to use it, everything went to the web. In Ahar, it gave me a link to @ at the end, which when I searched, Google did not find a site, and I deleted @ and again I searched but did not find a site. Thank you for helping me solve my problem or if you can re-upload the old files of the tool, thank you.
> `
> ░▀▀█░█▀█░█░█░▀█▀░█▀▀░█░█░█▀▀░█▀▄
> ░▄▀░░█▀▀░█▀█░░█░░▀▀█░█▀█░█▀▀░█▀▄
> ░▀▀▀░▀░░░▀░▀░▀▀▀░▀▀▀░▀░▀░▀▀▀░▀░▀ 2.1
> 
> [-] URL 1 :
> 
> [-] URL 2 : http://get-1000-followers-for-instagram@
> 
> [-] Waiting for Login Info, Ctrl + C to exit...^C `

use from here - https://replit.com/@htrtech/zphisher

**Comment by htr-tech** [comment]
> After getting a link what do i do? The link wont connect, but if someone click it an ip come up , what do i do with that ?

the victim hasn't inputted any credentials yet !

**Comment by jashgro** [comment]
> > Hello, please help me
> > I used your tool before and it was not a problem, but today, when I wanted to use it, everything went to the web. In Ahar, it gave me a link to @ at the end, which when I searched, Google did not find a site, and I deleted @ and again I searched but did not find a site. Thank you for helping me solve my problem or if you can re-upload the old files of the tool, thank you.
> > `
> > ░▀▀█░█▀█░█░█░▀█▀░█▀▀░█░█░█▀▀░█▀▄
> > ░▄▀░░█▀▀░█▀█░░█░░▀▀█░█▀█░█▀▀░█▀▄
> > ░▀▀▀░▀░░░▀░▀░▀▀▀░▀▀▀░▀░▀░▀▀▀░▀░▀ 2.1
> > [-] URL 1 :
> > [-] URL 2 : http://get-1000-followers-for-instagram@
> > [-] Waiting for Login Info, Ctrl + C to exit...^C `
> 
> use from here - https://replit.com/@htrtech/zphisher

Thanks pro ♥️
