### ISSUE TITLE
Facebook page Logo broken

### ISSUE THREAD

**Issue by lulzsecind** [htr-tech/zphisher#22]
![IMG-20200616-WA0002](https://user-images.githubusercontent.com/60328672/84736759-2f493880-afc4-11ea-8cdc-e8c78632d0c0.jpg)
Please fix this broken Facebook logo!

**Comment by kevzy** [comment]
move to the face book directory and edit it you're self...its easy changing the logo on login.html file

**Comment by anikey78** [comment]
Sorry but my pc is not working

**Comment by mod4xbox** [comment]
Can't find the logo src in any of the files: login.html or mobile.html. Can you please point me in the right direction? I have the logo just need to paste the local/remote link where appropriate. Thanks

**Comment by htr-tech** [comment]
> Can't find the logo src in any of the files: login.html or mobile.html. Can you please point me in the right direction? I have the logo just need to paste the local/remote link where appropriate. Thanks

we will update the page soon thank you

**Comment by htr-tech** [comment]
page fixed .. update the tool
