### ISSUE TITLE
Hacking

### ISSUE THREAD

**Issue by adithyaakula3** [htr-tech/zphisher#227]

**Comment by htr-tech** [comment]
?

**Comment by owavictor21** [comment]
Salut chef
Pouvez vous m'aider à apprendre le piratage
Merci

**Comment by AnonymousDebug** [comment]
@owavictor21
> Salut chef
> Pouvez vous m'aider à apprendre le piratage
> Merci

Dear owavictor21,
You shouldn't create a new issue unless there really is a issue, and for learning hacking you need to learn the pre-requisites for the type of hacking you want to learn, then you can start learning it, some helpfull sources attached below.

[HackTheBoxAccademy](https://academy.hackthebox.eu)
[HackTheBox](https://hackthebox.eu)
[Hacker101](https://hacker101.com)
[NetworkChuck](https://networkchuck.com)
[Blog How to learn hacking guide for starters](https://www.swiftchat.io/blog/hacking-101-beginners-guide-to-hacking/)
