### ISSUE TITLE
mastercard and visa

### ISSUE THREAD

**Issue by darkwebrichgirl** [htr-tech/zphisher#23]
please create also mastercard and visa

**Comment by htr-tech** [comment]
not possible . if i then i will face many problems ..

**Comment by darkwebrichgirl** [comment]
can you send me pm on telegram ? i need this very much @berlinasupport

**Comment by darkwebrichgirl** [comment]
> not possible . if i then i will face many problems ..

can you send me pm on telegram ? i need this very much @berlinasupport
