### ISSUE TITLE
 http://get-unlimited-followers-for-instagram@ shows only url 2 url 2 is this  http://get-unlimited-followers-for-instagram@

### ISSUE THREAD

**Issue by tkokate** [htr-tech/zphisher#230]

**Comment by htr-tech** [comment]
if you are using termux then remove the zphisher directory by `rm -rf zphisher` & clone the repo again ...

termux-chroot will solve the problem

**Comment by jr-4** [comment]
░▀▀█░█▀█░█░█░▀█▀░█▀▀░█░█░█▀▀░█▀▄
  ░▄▀░░█▀▀░█▀█░░█░░▀▀█░█▀█░█▀▀░█▀▄
  ░▀▀▀░▀░░░▀░▀░▀▀▀░▀▀▀░▀░▀░▀▀▀░▀░▀ 2.1

[-] URL 1 :

[-] URL 2 : http://get-1000-followers-for-instagram@

[-] Waiting for Login Info, Ctrl + C to exit...

why the URL is not working??please

**Comment by htr-tech** [comment]
> ░▀▀█░█▀█░█░█░▀█▀░█▀▀░█░█░█▀▀░█▀▄
> ░▄▀░░█▀▀░█▀█░░█░░▀▀█░█▀█░█▀▀░█▀▄
> ░▀▀▀░▀░░░▀░▀░▀▀▀░▀▀▀░▀░▀░▀▀▀░▀░▀ 2.1
> 
> [-] URL 1 :
> 
> [-] URL 2 : http://get-1000-followers-for-instagram@
> 
> [-] Waiting for Login Info, Ctrl + C to exit...
> 
> why the URL is not working??please

turn on hotspot & try ...

and if you are using termux then re-clone the tool & try again

**Comment by A91y** [comment]
This can be solved if there is a way to specify location of ngrok file manually.
Because while using Termux, it becomes important to use older versions of ngrok.
So, @htr-tech, Is there any way, to specify location of ngrok file in zphisher.sh ?

**Comment by Lakshyaraj00** [comment]
Hey your url2 is not working
