### ISSUE TITLE
instagram and other php codes not working

### ISSUE THREAD

**Issue by eternalodball** [htr-tech/zphisher#232]
Your php codes are not working some of the websites 

_Facebook_ "**login.php**" works fine but problem is with _instagram_ and may be with other sites ..
problem is that it doesn't even create "usernames.txt" in case of instagram and so ngrok etc ... not working too
 
btwn :- I've already given it **chmod 777**

**Comment by htr-tech** [comment]
ugh,,,,,,,,,, 😐  issue was on the bottom.... if you are root user try with sudo 😐
