### ISSUE TITLE
Just a question 

### ISSUE THREAD

**Issue by chrisfal10** [htr-tech/zphisher#233]
Any tool to send the url in form of email with the templates

**Comment by htr-tech** [comment]
use webhosting with php mailer 🤔

**Comment by maxwellcasper** [comment]
What's up? Bro I'm thinking about adding my on scripts to the repo but it's somewhat tough, (lol).
**it would be nice it you can send me a Direct email or a message on hangouts, pls I would like you to guide me for I just start coding.**

Hit me up at Maxwell.p.casper@gmail.com thanks.
