### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by Scofield4147** [htr-tech/zphisher#235]
root@kali:/home/iicybersecurity# git clone https://github.com/htr-tech/zphisher
 Cloning into 'zphisher'...
 remote: Enumerating objects: 39, done.
 remote: Counting objects: 100% (39/39), done.
 remote: Compressing objects: 100% (38/38), done.
 remote: Total 873 (delta 17), reused 2 (delta 0), pack-reused 834
 Receiving objects: 100% (873/873), 9.69 MiB | 1.28 MiB/s, done.
 Resolving deltas: 100% (346/346), done.

**Comment by htr-tech** [comment]
now type 

`cd zphisher`
`bash zphisher.sh`

😖
