### ISSUE TITLE
problem when using port forwarding service ngrok.io

### ISSUE THREAD

**Issue by AwX-Ploit** [htr-tech/zphisher#239]
Jadi ceritanya waktu saya memakai alat zphisher dari github nya, pas awal mencoba memang bisa dipakai tidak ada masalah, tetapi setelah saya beberapa kali memakai nya, dan menggunakan Layanan penerusan port ngrok.io Itu tidak muncul tautan ngrok.io nya, cuma ada logo banner saja, pertama kali saya memakai tidak ada masalah,,,dan setelah saya hapus tools nya dan saya mengulang install tools nya lagi, dan pas saya coba lagi baru muncul tautan ngrok.io nya,, "kenapa kalau di pakai beberapa kali itu sering tidak muncul tautan ngrok.io nya?" Apakah ada jeda waktu?,,,mohon bantuan nya.. terimakasih

**Comment by htr-tech** [comment]
remove the directory & clone again ..
or try using termux-chroot

Details : https://wiki.termux.com/wiki/Bypassing_NAT#Using_Ngrok_client
Source : https://t.me/kterm/89

**Comment by AwX-Ploit** [comment]
Ok thanks, I'll try it

Pada tanggal Jum, 4 Jun 2021 00.33, Tahmid Rayat ***@***.***>
menulis:
