### ISSUE TITLE
Send link to victim: empty

### ISSUE THREAD

**Issue by pr0xylien** [htr-tech/zphisher#24]
When selecting NGROK or Serveo the process completes but leaves you without a link.  Same result when reinstalling and installing on a fresh system.

**Comment by kevzy** [comment]
you don't have ngrok api key

**Comment by juanjoayala01** [comment]
wheree do i put the ngrock API once i get it?

**Comment by kevzy** [comment]
./ngrok " api key " Press enter

**Comment by htr-tech** [comment]
turn on hotspot & try again . serveo is down . it works only for manual forwarding . host on localhost & manuual forward port 5555 with serveo
