### ISSUE TITLE
Ngrok links 

### ISSUE THREAD

**Issue by Blue8547** [htr-tech/zphisher#245]
Hello, I am currently having issue with the ngrok links. The problem is that only I can open them and the other people are getting error "Tunnel *link* not found". I tried to open the link with vpn to check if they are lying or something, but that wasn't the case. What should I do to fix that ? 
(Forgot to add that I used the tool before a couple of days and it was working just fine! Today I tried it again and it just broke for some reason.)
(I tried a couple of methods, but nothing fixed the issue) 
(Noticed that the problem is from me and not anything with ngrok :), but sadly I still don't know how to fix it)

**Comment by Antdram** [comment]
same problem ^^^^^^^

**Comment by Antdram** [comment]
need this fix asap or tool is useless

**Comment by Iamde** [comment]
Yeah reality

**Comment by professorberlin602** [comment]
Same problem

**Comment by Ajabkha** [comment]
Please help me ,send me ,ngrok all commands only

**Comment by htr-tech** [comment]
Use Cloudflared to tunnel
