### ISSUE TITLE
Failed to complete tunnel connection

### ISSUE THREAD

**Issue by almostmeandrei** [htr-tech/zphisher#249]
The connection to https://639644a9e672.ngrok.io was successfully tunneled to your ngrok client, but the client failed to establish a connection to the local address localhost:80.

Make sure that a web service is running on localhost:80 and that it is a valid address.

The error encountered was: dial tcp [::1]:80: connectex: No connection could be made because the target machine actively refused it.

WHAT DOES IT MEAN?

**Comment by NITINKUMARSAINI** [comment]
Same problem 😭😭

**Comment by htr-tech** [comment]
> The connection to https://639644a9e672.ngrok.io was successfully tunneled to your ngrok client, but the client failed to establish a connection to the local address localhost:80.
> 
> Make sure that a web service is running on localhost:80 and that it is a valid address.
> 
> The error encountered was: dial tcp [::1]:80: connectex: No connection could be made because the target machine actively refused it.
> 
> WHAT DOES IT MEAN?

if your are root user then try with root permission..there was a problem with your php server
