### ISSUE TITLE
Link already in use

### ISSUE THREAD

**Issue by suriano998** [htr-tech/zphisher#25]
i recently exited my termux session while had a link open and noe i cant create a new link and the old one is offline, it says:
Warning: remote port forwarding failed for listen port 80
{"domain": "u0_a302-c4ed1495.localhost.run", "listen_port": 80, "status": "error", "error_code": "DomainInUse", "message": "u0_a302-c4ed1495.localhost.run is already in use, try a different domain"}

**Comment by suriano998** [comment]
hoe i cam change domain?

**Comment by htr-tech** [comment]
@suriano998  bro thats the problem of localhost.run . First host phishing page using localhost [01] 

& then in new window type `ssh -R 80:localhost:5555 ssh.localhost.run` for random link

& for custom link type `ssh -R localhost:80:localhost:8080 random-link@ssh.localhost.run`

**Comment by htr-tech** [comment]
best option is ngrok or localxpose

**Comment by suriano998** [comment]
thank you btw i love ur work

**Comment by suriano998** [comment]
> @suriano998 bro thats the problem of localhost.run . First host phishing page using localhost [01]
> 
> & then in new window type `ssh -R 80:localhost:5555 ssh.localhost.run` for random link
> 
> & for custom link type `ssh -R localhost:80:localhost:8080 random-link@ssh.localhost.run`

dosesnt work after typing that and starting up zphisher its still the same link
