### ISSUE TITLE
Some Websites Not Working 

### ISSUE THREAD

**Issue by Python-star774** [htr-tech/zphisher#261]
Some of the websites are not found such as Facebook, Google and Netflix. The only one that I've tried that works is Twitch. Pls, help!

**Comment by htr-tech** [comment]
Facebook, Google and Netflix pages are working .. 

Try after Re-cloning Zphisher ..

![image](https://user-images.githubusercontent.com/56682134/126209632-cf029324-c0ae-4d97-8457-2510aad39a21.png)
![image](https://user-images.githubusercontent.com/56682134/126209679-a95f51de-671b-459b-9036-0a53c671ad45.png)

**Comment by Python-star774** [comment]
Thanks! The real reason websites weren't working was because I had my antivirus turned on and it would block the web pages...

**Comment by MorganDavid4** [comment]
How can I get the software to hack in zphisher?
