### ISSUE TITLE
How do i clone and install zphisher?

### ISSUE THREAD

**Issue by Nolimit888** [htr-tech/zphisher#263]
How do i clone and install zphisher? 
Any help?

**Comment by htr-tech** [comment]
Use the following Commands 

$ `apt install git -y`
$ `git clone git://github.com/htr-tech/zphisher.git`
$ `cd zphisher`
$ `bash zphisher.sh`

**Comment by Faisal8899** [comment]
Ok👌

في جمعة، ٢٣ يوليو، ٢٠٢١ في ٨:٥٥ ص، كتب Tahmid Rayat <
***@***.***>:
