### ISSUE TITLE
NGROK not working......

### ISSUE THREAD

**Issue by mrh98814** [htr-tech/zphisher#271]
I'm facing same issue in other tools that use ngrok ......the link is only working when victim is using same wifi network...please fix it soon..it was just working fine few days ago ..i've been looking for solution since 3 days ..I tried unistalling the tool and reinstalling it.,,I tried re installing ngrok file as well but it didn't worked......I used mobile data and turned on hotspot..That didn't worked either...Please fix this asap otherwise This tool will be useless...

**Comment by DownFury** [comment]
same here :(

**Comment by aizaz321** [comment]
NGROk problem issue in all tools
