### ISSUE TITLE
NGROK

### ISSUE THREAD

**Issue by sizz1** [htr-tech/zphisher#274]
Repair Ngrok pls

**Comment by himanshudhingra03** [comment]
Link is not generating right?

**Comment by bindashish** [comment]
Ok but use Chrome code

**Comment by himanshudhingra03** [comment]
Which code?

**Comment by Sirius-Black4** [comment]
Why isnt it working??

**Comment by himanshudhingra03** [comment]
I don't know my link is not generating from last 3 days 
I have reinstall everything please sugget if you know

**Comment by afnan-rax** [comment]
> Fixed #281 
> 
> #### Ngrok Link not Showing issue have been fixed.
> Simply remove zphisher using & reclone again to Solve the Problem
> `rm -rf zphiser`
> `git clone git://github.com/htr-tech/zphisher.git`
> `cd zphisher `
> `bash zphisher.sh`
> 

Brother Im try this 
But not fixed 😐

**Comment by htr-tech** [comment]
Try ngrok's alternative : https://github.com/htr-tech/zphisher/issues/306

**Comment by Scorpiandelt** [comment]
> I don't know my link is not generating from last 3 days I have reinstall everything please sugget if you know

Bro could you teach me yo open rxce hack
