### ISSUE TITLE
link

### ISSUE THREAD

**Issue by leontoe** [htr-tech/zphisher#280]
i can get the link to work when i open it in Linux but if i try to use the link on google it will come up with tunnel not found is there away to fix this ?

**Comment by leontoe** [comment]
yes i do keep the zphisher open but the link will only work when i open it on the web browser thats on Linux if i try to open it on google it comes up with tunnel not found what am i doing wrong ?

**Comment by htr-tech** [comment]
can you provide some screen record or screenshots ?

**Comment by LilCoding** [comment]
getting same issue, ngrok link will only work on the network on which zphisher is running. maybe an issue with ngrok service.
