### ISSUE TITLE
[Fix] Ngrok Link not Showing

### ISSUE THREAD

**Issue by htr-tech** [htr-tech/zphisher#281]
#### Ngrok Link not Showing issue have been fixed.
Simply remove zphisher using & reclone again to Solve the Problem
`rm -rf zphiser`
`git clone git://github.com/htr-tech/zphisher.git`
`cd zphisher `
`bash zphisher.sh`

### EDIT : 
Tunnel Not Found is an issue with ngrok..hope they will fix it soon .. 
ngrok links are now working on local network only

### Try the alternative : #306

**ZPHISHER RELEASE 2.2**
**NGROK's alternative has been added**

Simply remove zphisher using & reclone again to Solve the Problem
`rm -rf zphiser`
`git clone git://github.com/htr-tech/zphisher.git`
`cd zphisher`
`bash zphisher.sh`

Then in the Port Forwarding option Use Option 3 Cloudflared ..

**Comment by Katkee29** [comment]
they still didnt fixed this

**Comment by godless98** [comment]
shiti fake

**Comment by htr-tech** [comment]
You all Can Use Portmap for Port forwarding

**Comment by htr-tech** [comment]
306

**Comment by htr-tech** [comment]
**ZPHISHER RELEASE 2.2**
**NGROK's alternative has been added**

Simply remove zphisher using & reclone again to Solve the Problem
`rm -rf zphiser`
`git clone git://github.com/htr-tech/zphisher.git`
`cd zphisher`
`bash zphisher.sh`

Then in the Port Forwarding option Use Option 3 Cloudflared ..

**Comment by Heugfu** [comment]
Uninstalll termux and install again and repeat the process

**Comment by Boskatapa** [comment]
Ngrok?? Not foud!
