### ISSUE TITLE
Ngrok.io Tunnel not found

### ISSUE THREAD

**Issue by NIRVANIAN472821** [htr-tech/zphisher#286]
**Link Generated =**
[-] URL 1 : https://7960-34-80-65-193.ngrok.io
[-] URL 2 : http://blue-verified-badge-for-facebook-free@7960-34-80-65-193.ngrok.io

**Error Acquired (ngrok site location):**
Tunnel 7960-34-80-65-193.ngrok.io not found

**Output and documentation:**

_-- Phishing site preview (html source code) isn't showing/rendering properly._ 
![Ngrok phishing site Preview](https://user-images.githubusercontent.com/80667677/131290706-c4671832-a36e-4e6b-bfad-eaebe03e1323.png)
![Ngrok site Source code](https://user-images.githubusercontent.com/80667677/131290818-fd8f2686-669c-4c6a-aba9-b478e698a2c7.png)

_-- The victim's IP address is still displayed on the terminal, indicating that the connection is still active._
![IP address AQR](https://user-images.githubusercontent.com/80667677/131291855-1905912a-5c97-45bc-9fbe-27bc4cc3cd29.jpg)

**_#END#_**

**Comment by Imperialrecker** [comment]
I got same issue. After researching, and testing I found out it was something wrong with this zphisher. My ngrok works perfectly on another python script

**Comment by NIRVANIAN472821** [comment]
@Imperialrecker Yes, it could be a zphisher connection or configuration issue with the ngrok server. I'm hoping it can be fixed as soon as possible.

**Comment by htr-tech** [comment]
its an issue with the ngrok server

**Comment by NIRVANIAN472821** [comment]
Oh, I see. I hope it gets resolved as soon as possible. I desperately need this fantastic creation of yours for my Phishing Awareness Presentation.

Thank you for letting us know Sir @htr-tech ❤.

**Comment by NIRVANIAN472821** [comment]
> Oh, I see. I hope it gets resolved as soon as possible. I desperately need this fantastic creation of yours for my Phishing Awareness Presentation.
> 
> Thank you for letting us know Sir @htr-tech ❤.

By the way sir, is there a workaround or a temporary fix for this type of error?

**Comment by htr-tech** [comment]
> > Oh, I see. I hope it gets resolved as soon as possible. I desperately need this fantastic creation of yours for my Phishing Awareness Presentation.
> > Thank you for letting us know Sir @htr-tech heart.
> 
> By the way sir, is there a workaround or a temporary fix for this type of error?

use other port forwarding sites (localhost.run) etc

Or simply upload the phishing pages to web server

**Comment by NIRVANIAN472821** [comment]
> > > Oh, I see. I hope it gets resolved as soon as possible. I desperately need this fantastic creation of yours for my Phishing Awareness Presentation.
> > > Thank you for letting us know Sir @htr-tech heart.
> > 
> > 
> > By the way sir, is there a workaround or a temporary fix for this type of error?
> 
> use other port forwarding sites (localhost.run) etc
> 
> Or simply upload the phishing pages to web server

Oh, i see. I'll just upload the files into a web server, i'll give credits. Thanks again sir ❤.

**Comment by hunxjunedo** [comment]
same issue

**Comment by NIRVANIAN472821** [comment]
> same issue

Mr. @hunxjunedo , Welp, It can't be helped. But you can use any of this alternatives: (As stated above)



> 
> use other port forwarding sites (localhost.run) etc
> 
> Or simply upload the phishing pages to web server

**Comment by NIRVANIAN472821** [comment]
Sir @htr-tech , May i know how should i properly upload and configure the files on a Website?

**Comment by NIRVANIAN472821** [comment]
And by the way, i think this issue should be marked as a Bug and pinned so other users will see it easily.

**Comment by itsjoeyzeng** [comment]
> > > Oh, I see. I hope it gets resolved as soon as possible. I desperately need this fantastic creation of yours for my Phishing Awareness Presentation.
> > > Thank you for letting us know Sir @htr-tech heart.
> > 
> > 
> > By the way sir, is there a workaround or a temporary fix for this type of error?
> 
> use other port forwarding sites (localhost.run) etc
> 
> Or simply upload the phishing pages to web server

localhost.run works pretty nice. The only problem is it changes the random URL every few hours. I am supposed to deliver a phishing attack for a school assignment, can you please briefly describe how we can upload the script and run it on a web server? Thanks!

**Comment by NIRVANIAN472821** [comment]
@itsjoeyzeng Same problem xD (except the localhost part), gonna run it on a website. Hopes i get some clue on how to properly setup and upload it on the webserver.

**Comment by itsjoeyzeng** [comment]
> @itsjoeyzeng Same problem xD (except the localhost part), gonna run it on a website. Hopes i get some clue on how to properly setup and upload it on the webserver.

@htr-tech @NIRVANIAN472821, ya, I upload zphisher via FTP to my web hosing but have no idea how to run it lol... if you get it working, please let me know

**Comment by NIRVANIAN472821** [comment]
> > @itsjoeyzeng Same problem xD (except the localhost part), gonna run it on a website. Hopes i get some clue on how to properly setup and upload it on the webserver.
> 
> @htr-tech @NIRVANIAN472821, ya, I upload zphisher via FTP to my web hosing but have no idea how to run it lol... if you get it working, please let me know

@itsjoeyzeng Will do. Hopefully i got some guide on how to do it.

**Comment by htr-tech** [comment]
#306

**Comment by NIRVANIAN472821** [comment]
> check the alternative #306

Not as good as ngrok, may trigger security blocking on most web browser. But it's a great alternative. Thanks, i appreciate it.

**Comment by NIRVANIAN472821** [comment]
Btw, how do i render the phishing files on my own website? (The site files)

**Comment by htr-tech** [comment]
> Btw, how do i render the phishing files on my own website? (The site files)

Simply upload the ip.php & files from the site folder inside `.sites` directory to your websites htdocs folder

**Comment by NIRVANIAN472821** [comment]
> Simply upload the ip.php & files from the site folder inside `.sites` directory to your websites htdocs folder

I see, will do. Thanks a lot!

**Comment by NIRVANIAN472821** [comment]
#306 (Issue is fixed) **Use Cloudflare as an alternative of Ngrok. [PORT FORWARDING]**

**Comment by Princessshane** [comment]
**_Good afternoon mr. @htr-tech , can you help me with this:_**
![2021-10-12 (7)](https://user-images.githubusercontent.com/88836098/136897904-726e19fd-8f7d-4e9f-9428-2b6ad87a2ab4.png)
![2021-10-12 (8)](https://user-images.githubusercontent.com/88836098/136897912-1825c9bf-f5e8-4714-8f93-366835a062d6.png)

login.php isn't working, and btw how do you avoid this
![Screenshot 2021-10-12 134104](https://user-images.githubusercontent.com/88836098/136898075-c379abd0-a076-44d2-ace0-cb44caf1042f.png)

I've followed all of the steps and enables ssl but browsers are still blocking my site while they don't block ngrok or cloudflare phishing sites.

**Comment by aminzikryy** [comment]
> **Link Generated =** [-] URL 1 : https://7960-34-80-65-193.ngrok.io [-] URL 2 : http://blue-verified-badge-for-facebook-free@7960-34-80-65-193.ngrok.io
> 
> **Error Acquired (ngrok site location):** Tunnel 7960-34-80-65-193.ngrok.io not found
> 
> **Output and documentation:**
> 
> _-- Phishing site preview (html source code) isn't showing/rendering properly._ ![Ngrok phishing site Preview](https://user-images.githubusercontent.com/80667677/131290706-c4671832-a36e-4e6b-bfad-eaebe03e1323.png) ![Ngrok site Source code](https://user-images.githubusercontent.com/80667677/131290818-fd8f2686-669c-4c6a-aba9-b478e698a2c7.png)
> 
> _-- The victim's IP address is still displayed on the terminal, indicating that the connection is still active._ ![IP address AQR](https://user-images.githubusercontent.com/80667677/131291855-1905912a-5c97-45bc-9fbe-27bc4cc3cd29.jpg)
> 
> **_#END#_**

same issue bro, i dont know why it not work in 2022

**Comment by aminzikryy** [comment]
choose localhost, it work

**Comment by Zunaira-Malik** [comment]
> 

have you tried a local host with public IP?
