### ISSUE TITLE
Link is only working till my network

### ISSUE THREAD

**Issue by hunxjunedo** [htr-tech/zphisher#288]
Hi sir, the link that this tool creates through Ngrok seems to be created from my own IP address as it shows it inside the URL, plus it only appears fine till my end, when I open it with a VPN or something, it shows Ngrok tunnel not found, please fix..

**Comment by Ajabkha** [comment]
Turn on your hotspot

**Comment by htr-tech** [comment]
#286 its an issue with the ngrok server

**Comment by hunxjunedo** [comment]
but is there a solution for hotspot for my Linux Desktop ? I have Ubuntu

**Comment by jitesh-eng** [comment]
yes i was face same problem in my link in pc my link show me this type of error
"Tunnel 821a-157-36-90-160.ngrok.io not found"

please help
