### ISSUE TITLE
This is a PURE offensive tool

### ISSUE THREAD

**Issue by JafarAkhondali** [htr-tech/zphisher#289]
A knife may be used for both good and evil, but a nuclear bomb can never be good!
To me, this tool is purely useful in offensive programs. Where is the educational part of submitting a form data to a phishing site? Even a 9 years old kid can understand what happens on a phishing page, I see no educational part in this project.
Don't try to escape the negative aspects of this project by using "This Tool is made for educational purpose only"

worth to mention:
https://syncedreview.com/2020/02/24/yolo-creator-says-he-stopped-cv-research-due-to-ethical-concerns/

**Comment by c0ntxt** [comment]
Educational purposes for cyber security. Pretty sure someone can learn something from it.

**Comment by JafarAkhondali** [comment]
there are 1000 better and easier ways to demonstrate a phishing page rather than creating an automated tool with Ngrok and templates for all social media services. This is not a special value in this cyber security tool.

**Comment by AstroOrbis** [comment]
Well, I learnt form data from this, so cha cha real smooth

**Comment by Nybbl3** [comment]
lol this jafar guy made a credit card stealing software using open cv and says it for educational purpose and then ranting on this legit tool used for pentesting

**Comment by JafarAkhondali** [comment]
@Nybbl3 are you kidding me ? 🤣 These credit cards use dynamic password (sth like OTP) there is no way you can steal money just by seeing a card. Also that project was made as a homework for university that's why I noted this is for ACADEMIC, which means it's not a production tool.

**Comment by AstroOrbis** [comment]
_sniff sniff_
I smell hypocriticism

**Comment by htr-tech** [comment]
FBI OPEN UP! 😐
