### ISSUE TITLE
Norgok is not working well I must put on vpn for it to work on other country and after it generate the link after 6mins it will not me working again pls find a solution

### ISSUE THREAD

**Issue by Ejobeh** [htr-tech/zphisher#293]

**Comment by hunxjunedo** [comment]
I have a pretty similar issue, it works on my Network but it shows tunnel not found on the URL if opened with a VPN.

**Comment by htr-tech** [comment]
**ZPHISHER RELEASE 2.2**
**NGROK's alternative has been added**

Simply remove zphisher using & reclone again to Solve the Problem
`rm -rf zphiser`
`git clone git://github.com/htr-tech/zphisher.git`
`cd zphisher`
`bash zphisher.sh`

Then in the Port Forwarding option Use Option 3 Cloudflared ..
