### ISSUE TITLE
Phising site only works on my network.

### ISSUE THREAD

**Issue by Katkee29** [htr-tech/zphisher#297]
I tried this tool on my best friend ( with his permission of course ) i sent him both links but none of them worked, it only works on my network. I dont have any VPN turned on or anything. Thanks forward.

**Comment by armaanmomin** [comment]
Same is the issue with me as well. It produces the link but it doesn't work on any other device. How to let it work on other devices as well. Please elaborate if any procedure is present. I had even checked ngrok, which is working correctly.

**Comment by armaanmomin** [comment]
![IMG_20210902_132336498](https://user-images.githubusercontent.com/89896466/131805182-188dc270-1303-495a-ba3e-39bf26f7152b.jpg)


![Screenshot_20210902-132437~2](https://user-images.githubusercontent.com/89896466/131805200-de34cfde-db49-413a-a9a9-bf9494df1161.png)

One is from PC and one is from mobile phone on different network. Request you to reply soon.

**Comment by Katkee29** [comment]
Yes, same thing happens to me

**Comment by Katkee29** [comment]
> Please elaborate if any procedure is present

Same thing with me

**Comment by Katkee29** [comment]
> ![IMG_20210902_132336498](https://user-images.githubusercontent.com/89896466/131805182-188dc270-1303-495a-ba3e-39bf26f7152b.jpg)
> 
> ![Screenshot_20210902-132437~2](https://user-images.githubusercontent.com/89896466/131805200-de34cfde-db49-413a-a9a9-bf9494df1161.png)
> 
> One is from PC and one is from mobile phone on different network. Request you to reply soon.

Is there any fix to this?

**Comment by htr-tech** [comment]
#281 This is ngrok's issue

**Comment by armaanmomin** [comment]
![IMG_20210902_134026088.jpg](https://user-images.githubusercontent.com/89896466/131807359-d1325598-f43f-4715-93c6-4e7e00c92211.jpg)


Even checked my ngrok session after closing the zphisher terminal. It seems to be working fine.

**Comment by armaanmomin** [comment]
This is what comes after I check the link.

Please check if anything can be done.

![IMG_20210902_134232212.jpg](https://user-images.githubusercontent.com/89896466/131807759-884d122a-ec1c-4d04-b47c-fd638f3e38cb.jpg)

**Comment by Katkee29** [comment]
> This is what comes after I check the link.
> 
> Please check if anything can be done.
> 
> ![IMG_20210902_134232212.jpg](https://user-images.githubusercontent.com/89896466/131807759-884d122a-ec1c-4d04-b47c-fd638f3e38cb.jpg)

Owner of this tool said that its bug with ngrok servers they only work on local network hope they will fix it soon #281

**Comment by hunxjunedo** [comment]
I am facing the same issue

**Comment by Juninhoww2** [comment]
same issue here

**Comment by Kamikazi-Tech** [comment]
This, I believe, is intentional. The developer just wants you to learn the process, not achieve the results

**Comment by ommie-more** [comment]
> results

You got it right may be

**Comment by Katkee29** [comment]
any fix or anything please?

**Comment by lasus-coder** [comment]
hi, @Katkee29 may i ask you what software are you using on your pc?

**Comment by ogadimelvin** [comment]
TERMUX

**Comment by lasus-coder** [comment]
@ogadimelvin download link?

**Comment by lasus-coder** [comment]
@ogadimelvin how do i get it on windows?

**Comment by ogadimelvin** [comment]
Install

**Comment by lasus-coder** [comment]
@ogadimelvin where and how tho. Please im new to all of this trying to learn.

**Comment by Devas252** [comment]
Same issue
The link is only working on my network only...
I tried to test on my friend's account with his permission but the link is not working on other phone

**Comment by NIRVANIAN472821** [comment]
#286

**Comment by htr-tech** [comment]
**ZPHISHER RELEASE 2.2**
**NGROK's alternative has been added**

Simply remove zphisher using & reclone again to Solve the Problem
`rm -rf zphiser`
`git clone git://github.com/htr-tech/zphisher.git`
`cd zphisher`
`bash zphisher.sh`

Then in the Port Forwarding option Use Option 3 Cloudflared ..

**Comment by armaanmomin** [comment]
> **ZPHISHER RELEASE 2.2**
> **NGROK's alternative has been added**
> 
> Simply remove zphisher using & reclone again to Solve the Problem
> `rm -rf zphiser`
> `git clone git://github.com/htr-tech/zphisher.git`
> `cd zphisher`
> `bash zphisher.sh`
> 
> Then in the Port Forwarding option Use Option 3 Cloudflared ..

It Is Working....I hope it continues to be.

**Comment by rifatkhan1119** [comment]
ZPHISHER RELEASE 2.2
NGROK's alternative has been added

Simply remove zphisher using & reclone again to Solve the Problem
