### ISSUE TITLE
[Suggestion] Add the Discord login page

### ISSUE THREAD

**Issue by AstroOrbis** [htr-tech/zphisher#298]
I dunno, I just really like the UI and I would like to be able to have a copy of that page :3

**Comment by Juninhoww2** [comment]
Yeah good one!

**Comment by Sitiaro** [comment]
Discord needs an auth token whilst logging in. It'll also give you an ip warning and will ask you to check your email to confirm the ip. Adding a discord page will only expose your ip to the victim and you won't be able to gain access to his account, irrespective of what you try. This is prob the dumbest suggestion ever.

**Comment by AstroOrbis** [comment]
Well, no. You can log in using username and password, and get a token from that. The token can also be created and forwarded to discord.
Also NGROK exists, you don't need to expose your IP, lmao

**Comment by ogadimelvin** [comment]
How do you mean.?

**Comment by AstroOrbis** [comment]
https://ngrok.com/

**Comment by LevansTHXN** [comment]
Maybe your ip will be exposed to the victim / target if you use localhost or your own apache server etc. Like that. You can use ngrok and there are also 2-3 alternatives for ngrok too. 🙂
