### ISSUE TITLE
About norgok

### ISSUE THREAD

**Issue by Ejobeh** [htr-tech/zphisher#299]
You people should do something about the issues please or give us a reply let know what up

**Comment by AstroOrbis** [comment]
It's out of our control, its an NGROK issue, not ours.

**Comment by htr-tech** [comment]
#306

**Comment by htr-tech** [comment]
**ZPHISHER RELEASE 2.2**
**NGROK's alternative has been added**

Simply remove zphisher using & reclone again to Solve the Problem
`rm -rf zphiser`
`git clone git://github.com/htr-tech/zphisher.git`
`cd zphisher`
`bash zphisher.sh`

Then in the Port Forwarding option Use Option 3 Cloudflared ..
