### ISSUE TITLE
Tunnel Not Found 🥺

### ISSUE THREAD

**Issue by m-society-0-0** [htr-tech/zphisher#303]
Bhai ye problem bhot jyada a rhi hai .. kya kare

**Comment by jitesh-eng** [comment]
some as my link show me  this type of error 
"Tunnel 821a-157-36-90-160.ngrok.io not found"

**Comment by Shivambott** [comment]
Yes bro...can anyone help plzz..

**Comment by Shivambott** [comment]
Developers...????

**Comment by galib7112** [comment]
its an issue with the ngrok server. so wait until they fix it.

**Comment by htr-tech** [comment]
#281 😞

**Comment by NIRVANIAN472821** [comment]
#286 Unfortunately, still got no fix.

**Comment by Taziq07** [comment]
Bro same problem is here 😌 
Tunnel not found

**Comment by htr-tech** [comment]
Use Portmap

**Comment by Taziq07** [comment]
Woh kaisai use krtai hai bhai

**Comment by htr-tech** [comment]
#306

**Comment by SerieuxHope** [comment]
> Ngrok Alternative : #306
Can you please explain how can one use it in Termux on Android? Thanks!

**Comment by htr-tech** [comment]
> > Ngrok Alternative : #306
> > Can you please explain how can one use it in Termux on Android? Thanks!

follow the steps on android .. it will work #306

**Comment by SerieuxHope** [comment]
> > > Ngrok Alternative : #306
> > > Can you please explain how can one use it in Termux on Android? Thanks!
> 
> follow the steps on android .. it will work #306

Cool! Thanks!

**Comment by htr-tech** [comment]
ZPHISHER RELEASE 2.2
NGROK's alternative has been added

Simply remove zphisher using & reclone again to Solve the Problem
rm -rf zphiser
git clone git://github.com/htr-tech/zphisher.git
cd zphisher
bash zphisher.sh

**Comment by 9thang798er** [comment]
![image](https://user-images.githubusercontent.com/90493924/134347260-13637b9f-3f25-410e-9112-7b3f17fe4e4e.png)
please help me!

**Comment by htr-tech** [comment]
> ![image](https://user-images.githubusercontent.com/90493924/134347260-13637b9f-3f25-410e-9112-7b3f17fe4e4e.png)
> please help me!

if yuo are root user then try using root .. don't open too any sessions..
