### ISSUE TITLE
Link is not woking on other devices 

### ISSUE THREAD

**Issue by Devas252** [htr-tech/zphisher#307]
The link is only working on my network only...
I tried to test on my friend's account with his permission but the link is not working on other devices

**Comment by htr-tech** [comment]
**ZPHISHER RELEASE 2.2**
**NGROK's alternative has been added**

Simply remove zphisher using & reclone again to Solve the Problem
`rm -rf zphiser`
`git clone git://github.com/htr-tech/zphisher.git`
`cd zphisher`
`bash zphisher.sh`

**Comment by Devas252** [comment]
Thankyou, it worked
