### ISSUE TITLE
url problem

### ISSUE THREAD

**Issue by Spider0069** [htr-tech/zphisher#309]
1. frist of i didnt get frisrt url (ngrok link which one we can send to victim)
2. once he do work but again same problem.
3. No data found.

**Comment by htr-tech** [comment]
ZPHISHER RELEASE 2.2
NGROK's alternative has been added

Simply remove zphisher using & reclone again to Solve the Problem
rm -rf zphiser
git clone git://github.com/htr-tech/zphisher.git
cd zphisher
bash zphisher.sh

**Comment by hunxjunedo** [comment]
It still does not show the link with Cloudflared..

**Comment by bullkeo1** [comment]
Even cloudflared, It shows the bad link .

**Comment by htr-tech** [comment]
> It still does not show the link with Cloudflared..

do `./.server/cloudflared -h` & see if the binary runs on your device or not

**Comment by bullkeo1** [comment]
It shows this line when I use cloudflared : grep: .cld.log: No such file or directory

**Comment by htr-tech** [comment]
> It shows this line when I use cloudflared : grep: .cld.log: No such file or directory

thats because the binary doesn't meet your device arc... type `uname -a` & find out your device architecture,,

then go to this link & download the binary  https://github.com/cloudflare/cloudflared/releases/latest

& replace it with `.server/cloudflared`

**Comment by bullkeo1** [comment]
> > It shows this line when I use cloudflared : grep: .cld.log: No such file or directory
> 
> thats because the binary doesn't meet your device arc... type `uname -a` & find out your device architecture,,
> 
> then go to this link & download the binary https://github.com/cloudflare/cloudflared/releases/latest
> 
> & replace it with `.server/cloudflared`

Darwin Ivan-Macbookpro.local 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64.

I chose "cloudflared-Darwin-AMD64". Is it right ?
Please show me what I have to do next ? 
Thanks a lot.

**Comment by htr-tech** [comment]
> > > It shows this line when I use cloudflared : grep: .cld.log: No such file or directory
> > 
> > 
> > thats because the binary doesn't meet your device arc... type `uname -a` & find out your device architecture,,
> > then go to this link & download the binary https://github.com/cloudflare/cloudflared/releases/latest
> > & replace it with `.server/cloudflared`
> 
> Darwin Ivan-Macbookpro.local 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64.
> 
> I chose "cloudflared-Darwin-AMD64". Is it right ?
> Please show me what I have to do next ?
> Thanks a lot.

& give executable perm,, `chmod 777 cloudflared`
& then move it to .server/cloudflared

**Comment by bullkeo1** [comment]
I resolved problem with cloudflared but other problem with php occurs : 

Warning: file_put_contents(usernames.txt): failed to open stream: Permission denied in /Users/bullkeo/Downloads/Github_zphisher/zphisher/.server/www/login.php on line 3

Warning: Cannot modify header information - headers already sent by (output started at /Users/bullkeo/Downloads/Github_zphisher/zphisher/.server/www/login.php:3) in /Users/bullkeo/Downloads/Github_zphisher/zphisher/.server/www/login.php on line 4

Please help !
