### ISSUE TITLE
Warning Deceptive site ahead

### ISSUE THREAD

**Issue by bullkeo1** [htr-tech/zphisher#318]
The link works. Unfortunately, it occurs the red warning for the victims to access. 

"Attackers on lawyers-packet-groove-ill.trycloudflare.com may trick you into doing something dangerous like installing software or revealing your personal information (for example, passwords, phone numbers, or credit cards). Learn more"

Can we fix this issue ?

**Comment by htr-tech** [comment]
chrome blocks this types of tunneling sites ..we can do nothing about these.. you can use vps to avoid that
