### ISSUE TITLE
Unable to locate package openssh

### ISSUE THREAD

**Issue by saim721** [htr-tech/zphisher#32]
i face this error after phishing google new page

**Comment by htr-tech** [comment]
which device do u use?

**Comment by saim721** [comment]
I am using Kali Linux i386 2020.2

**Comment by saim721** [comment]
Pc

**Comment by htr-tech** [comment]
you have to use this command 

apt-get install git curl php ssh wget -y

**Comment by kevzy** [comment]
htr-tech your tool is really cool not only is it easy to use but...it made me understand a little about how websites work ...php ,html ...
I can modify it to any phishing site I want

**Comment by m1234567890creator** [comment]
I faced problems while installing openssh on android (termux) it shows package not available also I face problem with depends

**Comment by htr-tech** [comment]
@m1234567890creator  use this command

`pkg update && pkg upgrade -y && pkg install git curl openssh php wget -y`

**Comment by m1234567890creator** [comment]
I tried it Always shows fix broken and depends issues

**Comment by htr-tech** [comment]
@m1234567890creator then reinstall termux apk

**Comment by m1234567890creator** [comment]
From last 4 days it install everything more than 100 times I dosen't work

**Comment by m1234567890creator** [comment]
Sorry this autocorrect sucks

**Comment by kevzy** [comment]
try pkg install open-ssh... 
I had the same issue back in the day and the command worked for me

**Comment by m1234567890creator** [comment]
> try pkg install open-ssh... 
> I had the same issue back in the day and the command worked for me

Not working

**Comment by m1234567890creator** [comment]
> @m1234567890creator  use this command
> 
> `pkg update && pkg upgrade -y && pkg install git curl openssh php wget -y`

Initially it shows command line working but then at last it shows unable to locate package what should I do ?

**Comment by htr-tech** [comment]
i think there is a prblm in your termux app .. If it can't locate package then create an issue on termux dist

**Comment by m1234567890creator** [comment]
> i think there is a prblm in your termux app .. If it can't locate package then create an issue on termux dist

It actually shows following packages have unmet dependencies

**Comment by htr-tech** [comment]
create an issue on termux dist
