### ISSUE TITLE
Can u add a 2fa page

### ISSUE THREAD

**Issue by ARanonymous** [htr-tech/zphisher#321]
The tool is great but if u would add a 2fa page it would be alot better it specially for Instagram and google

**Comment by roskosboskos** [comment]
Yeah, that would make it perfect ! Thanks 👍

**Comment by htr-tech** [comment]
I don't have any plan for that ... use Advphish
https://github.com/Ignitetch/AdvPhishing

**Comment by ARanonymous** [comment]
I tried it but it doesn't generate any link

**Comment by Jamescorwell45** [comment]
advphishing is broke the ngrok link with it is broke you cant use it

**Comment by ARanonymous** [comment]
AdvPhishing works u just have to find what port the tool opens on then open a separate terminal and use ngrok to generate a link
