### ISSUE TITLE
Error: Install Cloudflared Manually

### ISSUE THREAD

**Issue by pixeltheman** [htr-tech/zphisher#322]
I get an error during setup that fails to install cloudflared, and prompts me to install it manually. How do I install cloudflared manually?

**Comment by htr-tech** [comment]
which device you are using ?

**Comment by pixeltheman** [comment]
Kali linux x86_64

**Comment by htr-tech** [comment]
if kali it should be installed automatically 🙄 

however Go to this page : https://github.com/cloudflare/cloudflared/releases/tag/2021.9.1

ar download the binary file & move it to `.zphisher/.server/cloudflared`

& give executable permission..

**Comment by hackpekka** [comment]
Same error. On termux andoird it says install ngrok manually so I add # to install ngrok but then it shows this error: error occurred install cloudflared manually

**Comment by htr-tech** [comment]
> Same error. On termux andoird it says install ngrok manually so I add # to install ngrok but then it shows this error: error occurred install cloudflared manually

it needs an active internet connection to download the binary files.... commenting out lines is not a solution

**Comment by htr-tech** [comment]
download the right files for your architecture & replace it under `.server` directory

[#L265](https://github.com/htr-tech/zphisher/blob/c711e56378741b102625c13504a1f6c365dce2e9/zphisher.sh#L265) may be helpful
