### ISSUE TITLE
Cloudflare link not send fb and insta .. and ... Ngrok server not work ... Please update ...

### ISSUE THREAD

**Issue by m-society-0-0** [htr-tech/zphisher#325]
Kuch kijiyega sir ... Ngrok me ptani kya ho rha hai ... Cloudflare link fb or insta detect krra hai .. kya kare sir ... bahut pareshan agye hai ...

**Comment by htr-tech** [comment]
use hosting then 👀

**Comment by himanshudhingra03** [comment]
How to use it?

**Comment by Maheshwar52** [comment]
I have recently written a article about zphisher tool can anyone give your suggestions please.
https://techbuzz544.blogspot.com/2021/10/how-to-create-phishing-website-using.html
