### ISSUE TITLE
Qualcuno gentile 

### ISSUE THREAD

**Issue by Gf21vip** [htr-tech/zphisher#332]
C'è qualcuno molto gentile da seguirmi passo passo nella procedura per creare phishing

**Comment by htr-tech** [comment]
english please... 


for installation process follow the README

**Comment by czonta96** [comment]
Con questo tool non ci metti niente, non serve neanche essere un hacker per usarlo perché è facile
Per spuntarla quando fai phishing devi essere solamente bravo a convincere la gente a fare il login ma diventa sempre più difficile
Più la gente subisce questo genere di attacco, più la consapevolezza aumenta e quindi ancora più difficile spuntarla.

Se non ti firmano il login non puoi farci niente. Devi essere solo bravo a convincerli ad entrare. Per farlo devi crearti una PEC certificata e spammare a centinaia su centinaia di indirizzi e-mail e sperare che qualche pollo ci caschi.

Sul lato tecnico ho ben poco da dirti perché questo tool fa praticamente tutto. Per eludere i sistemi di sicurezza anti-phishing di Google e di qualunque antivirus hosta la tua pagina su raspe.id. Si tratta di un proxy pubblico che aggiunge alla pagina un certificato di sicurezza valido offerto da cPanel.inc e terminazione TLS 1.3 (0 access encryption)

**Comment by czonta96** [comment]
Se sei su Windows installati VirtualBox e Kali Linux perché questo tool è un macello da configurare su Windows, è possibile ovviamente perchè da attaccante ritengo che niente sia impossibile, ma se si trova una scorciatoia è meglio

Windows non è un sistema operativo inteso per l'hacking e la sicurezza offensiva, quindi ti consiglio caldamente di installare un sottosistema Linux a meno che non vuoi metterti una notte intera a scontrarti con un terminale che restituisce un errore dopo l'altro
