### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by Gf21vip** [htr-tech/zphisher#333]
the program git is not installed. install it by executing pkg install git

I installed it but it always gives me the same error, can someone help me?

**Comment by htr-tech** [comment]
> the program git is not installed. install it by executing pkg install git
> 
> I installed it but it always gives me the same error, can someone help me?

provide screenshots

**Comment by yasinst1004** [comment]
I can open the phishing link on my pc but not on my phone. why is this and how can i fix it?

**Comment by htr-tech** [comment]
> I can open the phishing link on my pc but not on my phone. why is this and how can i fix it?

Try using ngrok or cloudflared

**Comment by yasinst1004** [comment]
I tried it with cloudflared and it didnt work and i didnt understood the point of ngrok. I mean it seems like your "victim" needs an ngrok account or did i missunderstand something?

**Comment by yasinst1004** [comment]
> > I can open the phishing link on my pc but not on my phone. why is this and how can i fix it?
> 
> Try using ngrok or cloudflared

I tried it with cloudflared and it didnt work and i didnt understood the point of ngrok. I mean it seems like your "victim" needs an ngrok account or did i missunderstand something?

**Comment by htr-tech** [comment]
> I tried it with cloudflared and it didnt work on phone either 

your cloudflared link was not generated or what happened with it ?

**Comment by yasinst1004** [comment]
> > I tried it with cloudflared and it didnt work on phone either 
> 
> 
> 
> your cloudflared link was not generated or what happened with it ?

When i used cloudflared it was the exact same problem as with localhost. Means that i can open the link on my PC but not on my phone.

**Comment by yasinst1004** [comment]
> > I tried it with cloudflared and it didnt work on phone either
> 
> your cloudflared link was not generated or what happened with it ?

Bro nvm it worked out of nowehre. Like i tried it again with cloudflared and now it opens on phone too.
thank you bro for helping

**Comment by yasinst1004** [comment]
> > I tried it with cloudflared and it didnt work on phone either
> 
> your cloudflared link was not generated or what happened with it ?

but i have another question: just theoretically im in germany and use windows and have kali installed on it. Now if i hack a password from another person can the police somehow find out that i did this? Cause that would be 3 years in prison if they find out that i did this. if you know let me know pls.

**Comment by htr-tech** [comment]
> > > I tried it with cloudflared and it didnt work on phone either
> > 
> > 
> > your cloudflared link was not generated or what happened with it ?
> 
> but i have another question: just theoretically im in germany and use windows and have kali installed on it. Now if i hack a password from another person can the police somehow find out that i did this? Cause that would be 3 years in prison if they find out that i did this. if you know let me know pls.

Government can track you ..never use this for non-ethical purpose :3 

Checkout the Disclaimer First : https://github.com/htr-tech/zphisher#disclaimer

**Comment by yasinst1004** [comment]
> Government can track you ..never use this for non-ethical purpose :3 
> 
> 
> 
> Checkout the Disclaimer First : [disclaimer](https://github.com/htr-tech/zphisher/blob/master/README.md#disclaimer)


Thank you for helping me, i wont do it.
