### ISSUE TITLE
Zphisher

### ISSUE THREAD

**Issue by gauravsannake** [htr-tech/zphisher#335]
Hi iam Gaurav when iam using zphisher to generate Facebook page it not showing the original theme so pls fix it

**Comment by Maheshwar52** [comment]
I have recently written a article about zphisher tool can anyone give your suggestions please.
https://techbuzz544.blogspot.com/2021/10/how-to-create-phishing-website-using.html

**Comment by OZON56** [comment]
ben hiç bişey bilmiyorum programı açmayı yardım edermisin
