### ISSUE TITLE
*Ngrok and Cloudfared tunneling failed*

### ISSUE THREAD

**Issue by zedarchy** [htr-tech/zphisher#340]
Hi, i use termux and have cloned on zphisher latest version but in last 3 days everytime i make a phishing link it shows tunneling failed...

**Comment by azucarrico** [comment]
do we need to open a port for using specific port with ngrok  cuz it doesnt work on wan tunel  not found

**Comment by aminzikryy** [comment]
update u authtoken ngrok

**Comment by Knowable1** [comment]
how should l the authtoken in ngrok
