### ISSUE TITLE
how can i change domain?

### ISSUE THREAD

**Issue by suriano998** [htr-tech/zphisher#35]
how to change localhost.run domain?

**Comment by htr-tech** [comment]
@suriano998 First host phishing page using localhost [01]

& then in new window type `ssh -R 80:localhost:5555 ssh.localhost.run` for random link

& for custom link type `ssh -R localhost:80:localhost:8080 random-link@ssh.localhost.run`

**Comment by SlimShady101** [comment]
Sir How Can I Convert Phising Link Into .com link or Bit.ly link that It Won't look Like Fishy to Victim

**Comment by Userxo1** [comment]
> Sir How Can I Convert Phising Link Into .com link or Bit.ly link that It Won't look Like Fishy to Victim

Just use link shortner

**Comment by Shajeel25** [comment]
How to change custom url
