### ISSUE TITLE
Possible to replace one of the sites with your own??

### ISSUE THREAD

**Issue by Jamescorwell45** [htr-tech/zphisher#350]

**Comment by Jamescorwell45** [comment]
i have code for another website i wanted to add and replace isit possible?

**Comment by ChillVibesMushroom** [comment]
> i have code for another website i wanted to add and replace isit possible?

did you figure out where they're at try sudo nano bash to check and see if there is a directory we can visit

**Comment by ChillVibesMushroom** [comment]
/zphisher/.sites

**Comment by htr-tech** [comment]
add it on `.sites` directory..

or simply host using php / apache
