### ISSUE TITLE
URL 1 is not showing in cloudflared 

### ISSUE THREAD

**Issue by anonymous0305** [htr-tech/zphisher#354]
URL 1 is not showing in cloudflared, not showing for any template,.

what to do ?

![Screenshot 2021-11-03 190222](https://user-images.githubusercontent.com/79696906/140069577-8be6df88-32c3-4820-a027-968527054a05.jpg)
?

**Comment by milanvishwakarma** [comment]
Same problem dude

**Comment by rudrarathor12** [comment]
yes same problem please resolve this

**Comment by greycorps** [comment]
Same. Links worked once and ever since it just shows "permission denied" and they don't work.

**Comment by htr-tech** [comment]
try using sudo ...

**Comment by usedfork** [comment]
Using sudo didn't do anything.

**Comment by Ivar-the-boneles** [comment]
Try using 

> $ home
> $ chmod +x zphisher

**Comment by anonymous0305** [comment]
no sir its not working

**Comment by anonymous0305** [comment]
i tested in both kali 2021.4a and parrot 4.11.3 but same problem persist. i dont know if im doing same mistake or package problem. but since developer releases cloudflare  update it worked perfect and after some months it stop working.

**Comment by Engineer156** [comment]
try sudo bash zphisher
