### ISSUE TITLE
YAR PLEASE GOOGLE KA LOGIN PAGE UPDATE KARDOOOOO

### ISSUE THREAD

**Issue by hunxjunedo** [htr-tech/zphisher#355]
please update the GOOGLE LOGIN PAGEE

**Comment by oaosdpo** [comment]
try using this and then put phishing code in it to make it useful and then a redirect 

https://github.com/couldbejake/Coogle


it basically has all the animations and css and progress bar and matches today's login screen. all it needs is a phishing code

**Comment by Alygnt** [comment]
Try https://github.com/Alygnt/NPhisher or https://github.com/Alygnt/LPhisher You might get what you want
