### ISSUE TITLE
Permission 🧘

### ISSUE THREAD

**Issue by Teekay-X** [htr-tech/zphisher#356]
Hi sir im new to GitHub but not new on coding so can i plz get the permission to edit the script plz🙏🙏 🙏 i just need a project to work on sir 🙏🙏 plz plz im begging you  i won't ruin anything 🙏

**Comment by msr8** [comment]
fork the repo

**Comment by Teekay-X** [comment]
I wanna contribute 🙏🙏

**Comment by bindashish** [comment]
ok

**Comment by msr8** [comment]
ok

**Comment by htr-tech** [comment]
Fork it & modify ...
