### ISSUE TITLE
Connection Reset

### ISSUE THREAD

**Issue by KssGamerEdits** [htr-tech/zphisher#36]
[~] Select a Port (Default: 5555 ): 8080

 [~] Initializing...(localhost:8080)

 [~] Launching LocalHostRun ..

 [~] Ctrl + C to view Login Info.Press it After the Victim Opened It.

kex_exchange_identification: read: Connection reset by peer
Connection reset by 107.22.191.251 port 22

**Comment by htr-tech** [comment]
use ngrok ...
