### ISSUE TITLE
[!] Error occured, Install Ngrok manually.

### ISSUE THREAD

**Issue by wasdeded** [htr-tech/zphisher#360]
when i type in 

$ bash zphisher.sh

 i get this 

$ bash zphisher.sh
zphisher.sh: line 141: pidof: command not found
zphisher.sh: line 144: pidof: command not found
zphisher.sh: line 147: pidof: command not found

[+] Installing required packages...

[+] Installing package : wget
Unable to locate an executable at "/Library/Java/JavaVirtualMachines/jdk1.8.0_261.jdk/Contents/Home/bin/apt" (-1)

[+] Installing ngrok...

[!] Error occured, Install Ngrok manually.

it says its installed and i tried to reinstall it but same error message.

read something about having to give excutable permission (chmod 777 ngrok)
and move the excutable file into .server directory

but dont know how? im new to all this

**Comment by MatCstl** [comment]
Hey man,
Like the introduction say u have to install : "php wget curl git" before running the bash.

Try to run this following command : `apt-get install php wget curl git` git and re-run the script.
and make sure all of yours packages are updated by typing this 2 commands : `apt-get update` & `apt-get upgrade`

Hope that your problem is solved after trying this ;)


(Sorry for my English i'm French

**Comment by landryddddd** [comment]
même problème, pouvez vous m'aidez ? j'ai suivie vos conseilles je n'ai toujours pas reussie

**Comment by htr-tech** [comment]
> when i type in
> 
> $ bash zphisher.sh
> 
> i get this
> 
> $ bash zphisher.sh zphisher.sh: line 141: pidof: command not found zphisher.sh: line 144: pidof: command not found zphisher.sh: line 147: pidof: command not found
> 
> [+] Installing required packages...
> 
> [+] Installing package : wget Unable to locate an executable at "/Library/Java/JavaVirtualMachines/jdk1.8.0_261.jdk/Contents/Home/bin/apt" (-1)
> 
> [+] Installing ngrok...
> 
> [!] Error occured, Install Ngrok manually.
> 
> it says its installed and i tried to reinstall it but same error message.
> 
> read something about having to give excutable permission (chmod 777 ngrok) and move the excutable file into .server directory
> 
> but dont know how? im new to all this

"pidof" not found... which distro are you using ?

**Comment by azlan-syed** [comment]
mine one is stuck on installing ngrok

**Comment by htr-tech** [comment]
> mine one is stuck on installing ngrok

Keep an active internet connection..it is downloding ngrok in the background

**Comment by htr-tech** [comment]
> *me leaving it downloading ngrok for a half an hour BRO HELLLLLLLLLPPPPPPPPPP

Then Skip Ngrok ..
just go to zphisher directory 

op
open zphisher.sh using any text editor
put an # at the beginning of 759 line

```
# install_ngrok
install_cloudflared
main_menu
```

**Comment by azlan-syed** [comment]
> when i type in
> 
> $ bash zphisher.sh
> 
> i get this
> 
> $ bash zphisher.sh zphisher.sh: line 141: pidof: command not found zphisher.sh: line 144: pidof: command not found zphisher.sh: line 147: pidof: command not found
> 
> [+] Installing required packages...
> 
> [+] Installing package : wget Unable to locate an executable at "/Library/Java/JavaVirtualMachines/jdk1.8.0_261.jdk/Contents/Home/bin/apt" (-1)
> 
> [+] Installing ngrok...
> 
> [!] Error occured, Install Ngrok manually.
> 
> it says its installed and i tried to reinstall it but same error message.
> 
> read something about having to give excutable permission (chmod 777 ngrok) and move the excutable file into .server directory
> 
> but dont know how? im new to all this

i don't get it try sudo ./zphisher.sh

**Comment by azlan-syed** [comment]
ok

**Comment by mehranarya** [comment]
How to simulate. I am a beginner.

**Comment by firastrabe** [comment]
Firas Trabelsi
Le jeu. 10 févr. 2022 à 05:16, mehranarya ***@***.***> a
écrit :

**Comment by firastrabe** [comment]
Le jeu. 10 févr. 2022 à 05:16, mehranarya ***@***.***> a
écrit :

**Comment by Devang122** [comment]
> > when i type in
> > $ bash zphisher.sh
> > i get this
> > $ bash zphisher.sh zphisher.sh: line 141: pidof: command not found zphisher.sh: line 144: pidof: command not found zphisher.sh: line 147: pidof: command not found
> > [+] Installing required packages...
> > [+] Installing package : wget Unable to locate an executable at "/Library/Java/JavaVirtualMachines/jdk1.8.0_261.jdk/Contents/Home/bin/apt" (-1)
> > [+] Installing ngrok...
> > [!] Error occured, Install Ngrok manually.
> > it says its installed and i tried to reinstall it but same error message.
> > read something about having to give excutable permission (chmod 777 ngrok) and move the excutable file into .server directory
> > but dont know how? im new to all this
> 
> "pidof" not found... which distro are you using ?

I have same problem of ngrok tried the above solution but it is not solved
