### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by baeb13** [htr-tech/zphisher#361]
Do you have the windows setup for Zphisher?
i need the windows setup

**Comment by 1RaY-1** [comment]
No, but you can try to install Wndows Subsystem for Linux (WSL), then in microsoft store install any Linux distro (for example ubuntu), launch it, setup and you can download and run zphisher from your linux terminal inside windows.

This should help you: https://www.windowscentral.com/install-windows-subsystem-linux-windows-10

But  notice that WSL is not available for all Windows versions.

**Comment by htr-tech** [comment]
You can install it in linux distro via wsl as mentioned above or using vmware
