### ISSUE TITLE
J'AI TOUT ESSAYER IMPOSSIBLE A INSTALLER

### ISSUE THREAD

**Issue by landryddddd** [htr-tech/zphisher#362]
zphisher.sh: line 141: pidof: command not found
zphisher.sh: line 144: pidof: command not found
zphisher.sh: line 147: pidof: command not found

[+] Installing required packages...

[+] Installing package : wget
Unable to locate an executable at "/Library/Java/JavaVirtualMachines/jdk-11.0.13.jdk/Contents/Home/bin/apt" (-1)

[+] Installing ngrok...

[!] Error occured, Install Ngrok manually.

Aidez moi svp j'ai vraiment essayer de faire de mon mieux mais impossible à installer. J'ai écouter chaque conseille donner sur internet toujours une couille quelque part c'est dommage .

Je précise je suis DÉBUTANT surtout dans ce qui touche le terminal je suis sur mac os

**Comment by htr-tech** [comment]
For now zphisher is for linux only . 😕 try using any linux distro
