### ISSUE TITLE
The link that generated is blank when opened.

### ISSUE THREAD

**Issue by adriantoto** [htr-tech/zphisher#368]
the link that generated (cloudflare or ngrok) is blank when opened, any solution of this situation?

**Comment by htr-tech** [comment]
did you closed your session on linux / termux ?

**Comment by Timodo22** [comment]
me2

**Comment by adriantoto** [comment]
> did you closed your session on linux / termux ?

no, the Linux session is still ongoing.

**Comment by htr-tech** [comment]
If you are a root user ..then try using root

**Comment by czonta96** [comment]
Both servers are using a severe abusing protocol against phishing
Use localhost.run by typing in your terminal "ssh -R 80:localhost:8080 localhost.run" to tunnel your connection
Server's admin on localhost.run seem they don't care at all about script kiddies, you can abuse them.
