### ISSUE TITLE
Facebook traditional login page destroyed

### ISSUE THREAD

**Issue by marmabiswas123** [htr-tech/zphisher#369]
After the update in zphisher the traditional login page of facebook is just showing the html format not the css .
![Screenshot_20211128-083158](https://user-images.githubusercontent.com/76593303/143727204-f160a3bb-6b63-4837-815e-976e10fbff63.png)

**Comment by KasRoudra** [comment]
Try this [fork of zphisher](https://github.com/KasRoudra/zphisher)

**Comment by htr-tech** [comment]
Now try by updating zphisher #365
