### ISSUE TITLE
Ngrok not working for others only me please help

### ISSUE THREAD

**Issue by Feten1001** [htr-tech/zphisher#37]
Okay so when I choose ngrok it gives me a link I type it in correctly checked it 3 times and it works for me, but when I send to my friend it does not work I tried another friend it don't work just says that weird stuff tunnelling error when the enter website they typed it it'll correctly, I tried putting on mobile data on tried turning off and it worked on the Linux Choices shellphish but then the account taking shellphish down it only seems to work for any device in my house but not anywhere els ???? I'm on Termux btw using Android

**Comment by Smartbizzy** [comment]
Use local host

**Comment by Feten1001** [comment]
@Smartbizzy local host when I use that it just says localhost then 4 numbers I put 8080 is there a picific one to use well anyway I entered the website it told me to send to victim localhost.8080 nothing happens now what do I do

**Comment by Smartbizzy** [comment]
Use 5555 default

**Comment by Feten1001** [comment]
@Smartbizzy okay so I said use port 5555 the default one and it says successfully hosted at http://localhost:5555 then I entered the site http://localhost:5555/ and still nothin happend please help me

**Comment by Smartbizzy** [comment]
Delete your Termux and install another one from play store

**Comment by Smartbizzy** [comment]
After that run zphisher again and do it again.
Note your victim must enter there login details in the provided link before
you receive there details.

**Comment by Feten1001** [comment]
@Smartbizzy are you sure nothing won't be deleted like any files and plus when I delet and re download do I enter anything into Termux for example update or install anything like git or whatever thanks for this

**Comment by Smartbizzy** [comment]
Am sorry.
You have to start from the beginning.
Apt update && upgrade.
That's the only solution and again did you switch on your hotspot in the
processe

**Comment by Smartbizzy** [comment]
Learning termux have cost me more than 50$ buying data to start from the
beginning anytime I make mistakes

**Comment by Feten1001** [comment]
@Smartbizzy oh yeah I turned on hotspot before all this never worked and turned off opened again never worked well I uninstalled Termux installed it again I typed Apt update && upgrade them I typed cd then ls and then nothing's there

**Comment by Smartbizzy** [comment]
apt update
apt install git python python2 -y
git clone git://github.com/htr-tech/zphisher.git
cd zphisher

**Comment by Feten1001** [comment]
Ok I installed Zphisher again and chose Snapchat choose ngrok gave me a link which was https://2a1c75cc226c.ngrok.io

I entered it in on my phone Snapchat website comes up for me but can you try and see if it works for you just type anything in login just like test and test but I don't think it'll work because it's only working for people on my network can use site but can u see if it opens for you it should say on my side victim found user test password test I'll text if it don't work here it is 

https://2a1c75cc226c.ngrok.io

**Comment by Smartbizzy** [comment]
Are you a Nigerian 🇳🇬

**Comment by Feten1001** [comment]
@Smartbizzy did Snapchat come up for you?

**Comment by Smartbizzy** [comment]
Am not on Snapchat.
Use Facebook

**Comment by Smartbizzy** [comment]
No.
It said fatal error

**Comment by Feten1001** [comment]
@Smartbizzy no I'm UK British and plus you see what I mean for others it says fatal error do i need to type something in Termux app to fix the feral error for others

**Comment by Smartbizzy** [comment]
If you are on WhatsApp text me.
+2348145363693

**Comment by Feten1001** [comment]
I havnt got WhatsApp erm I got Snapchat then I can text and snap you what's happing what's your snapchat username

**Comment by Feten1001** [comment]
@Smartbizzy  What's ur snapchat name

**Comment by Smartbizzy** [comment]
Smart bizzy

**Comment by Feten1001** [comment]
That's ur name what's ur username it can't have any spaces in @Smartbizzy

**Comment by Feten1001** [comment]
@Smartbizzy did you do a tutorial? Thx

**Comment by Smartbizzy** [comment]
Please download a WhatsApp app and register.
After that save my number +2348145363693  chat me up or drop your number.
Snapchat is not fast in sharing all my this tutorial videos fast. Please
register now for a better conversation or drop your phone number here let
me chat you.

**Comment by Smartbizzy** [comment]
Are you there

**Comment by Feten1001** [comment]
@Smartbizzy okay one second
