### ISSUE TITLE
Serveo & Ngrok doesn’t give the link 

### ISSUE THREAD

**Issue by laszl0o** [htr-tech/zphisher#38]
Can you please explain what I need to do with hotspot? Do I need to turn it on? Do I need to leave it, or use it?

**Comment by htr-tech** [comment]
@laszl0o serveo is down !! turn on hotspot & try ngrok & try again .. you will get that link 😄

**Comment by bullkeo1** [comment]
I tried hundreds times but cannot get the link with ngrok. Please tell me what I have to do with ngrok ? Do I have to install  something else like docker ?
