### ISSUE TITLE
hi i want to present this pishing tool can you please explain .sh file in youtube video

### ISSUE THREAD

**Issue by shigri007** [htr-tech/zphisher#395]
hey bro please explain the bash script in hindi or english in youtube video I will be very thankful to you

**Comment by htr-tech** [comment]
you mean how to write bash/shell script ?

**Comment by shigri007** [comment]
yes i wanted to know that what your each line of code is doing  i have to present it to my professor and i am unable to understand the code bro

**Comment by czonta96** [comment]
Bash is not worth to learn even if this tool is completely written in bash
If u want to make solid work look for Python

**Comment by htr-tech** [comment]
> yes i wanted to know that what your each line of code is doing i have to present it to my professor and i am unable to understand the code bro

Read the manual https://www.gnu.org/software/bash/manual/bash.html
