### ISSUE TITLE
help

### ISSUE THREAD

**Issue by mc-cna** [htr-tech/zphisher#397]
in line 412 say error .cld.log no such file or directory how can i fix it?

![image](https://user-images.githubusercontent.com/74782980/148427347-b7f21ffb-8d25-40e6-bbfb-8dd09bc29d5e.jpg)
![image](https://user-images.githubusercontent.com/74782980/148427435-9115fd61-b0cf-44da-b344-ee9839016a5e.jpg)

**Comment by htr-tech** [comment]
run using sudo -,-

**Comment by Racergh** [comment]
Did you solve it? Im working on mac and have the same problem

**Comment by arul637** [comment]
I am using windows operating system I dont know how to install zphisher or any hacking my tools and i dont know how to start learning hacking, if you know what is first thing to learn for ethical hacking basic which tool is first to learn, please help me. My mail id is (sarulkumaran.21042004@gmail.com)

**Comment by Kakahsa** [comment]
I using termux
