### ISSUE TITLE
Big Fan 😍😍

### ISSUE THREAD

**Issue by masterjavaofficial** [htr-tech/zphisher#398]
0b01001101010010000110011100110011010011010111101001011001001101010100111001111010010010010111100101001101010001000101101001101000010011100110110101011001001100100100111001000100010110010011010101001101011010100100000100110010010011100101010001011010011010010100111001111010010100010011001101001110010101000100100101110111010011100110101001001101001100100100111101000100010110010011010101001110011110100100000100110010010011010101010001100011001101010100110101101010010000010011001001001101010101000110001101111010010011100110101001100111001100110100111001000100010110010011000101001110011011010101010101111001000010100101101001010100010010100110110001001101011010100100000100110010010110100100010001011001011110000100111001101101010101010011001001001110010101000100100101110111010011100110101001000101001100110100110101000100010110100110110001001110011010100101010100110011010011010110101001001001011101110100111001101010010110010011001001001101011010100100101001101101010011100110110101010001001100100100111001010100011000110111101001001110011110100100110100110010010011100101010001011010011011000100111001101010011000110011001001001110010101000110001101111001010011010110101001000001001100100100110101111010010110010011010000001010010011100110101001101011001100110100110101000100010110010111100001001101011010100100000100110011010011100100010001011001001101000100111001101010010101010011001001011001011010100101100100110001010011010110101001000001001100100101100101010100010110100110110101001110011010100101000100110010010011110101010001001001011101110100111001101010010001010011001001011010010001000110001101111001010011100110101001010101011110010100110101000100010110010011000101001110011011010100100100110011010011100100010001011001011110000100110101101010010000010011001001011001011010100101101001101100010011100110110101011001001100100000101001001101011110100101101001101001010011010110101001000001001100100100111001000100010110010011010101001110011110100101000100110010010011100101010001011010011011000100110101101101010101010111100101011010010101000100100101110111010011100110101001010101001100100101100101101010011000110011000001001110011110100101010101111001010011010100010001011001001100000100111001101101010110010011001101001101011010100101101001101001010011100110101001000101001100110100110101101010010010010111011101001110011010100100110100110010010011110100010001011001001101010100111001101101010011010011001001011010011010100100101001101100000010100100110101101101010101010111100101011010010101000100100101110111010011100100011101010101001100000100110101101010010011100110100001001101011010100100000100110001010011100100010001011001001100010100111001101101010011010011001001001110010101000101100100110011010011100111101001001001001100100100110101010100010110100110101101001101011010100100000100110010010011010111101001011001001101000100111001101010010001010011001001011001011110100101100101111000010011100110101001101011011110010100110101000100010110100110110001001110011010100100010100110010010011110100010001001001011101110100111001111010010010010011110100001010

**Comment by htr-tech** [comment]
@masterjavaofficial personal issue 😥😓

```MHg3NjYxNzUyMDYxNkQ2MTcyMjA3MzZGNjIyMDZCNjk3Mzc1MjA2NDY5NzM2MTYyNkM2NTIwNkI2RjcyNjEyMDJFMkUyMDMzMkYzNDIwNkQ2MTczNjgyMDY1NzIyMDYxNjc2NTIwNjE2Mzc0Njk3NjY1MjA2ODZGNzQ2NTIwNzA2MTcyNjI2RjIwNkU2MTIwNkQ2MTc5NjI2NTIwM0EyMjI5```

**Comment by masterjavaofficial** [comment]
> @masterjavaofficial personal issue 😥😓
> 
> `MHg3NjYxNzUyMDYxNkQ2MTcyMjA3MzZGNjIyMDZCNjk3Mzc1MjA2NDY5NzM2MTYyNkM2NTIwNkI2RjcyNjEyMDJFMkUyMDMzMkYzNDIwNkQ2MTczNjgyMDY1NzIyMDYxNjc2NTIwNjE2Mzc0Njk3NjY1MjA2ODZGNzQ2NTIwNzA2MTcyNjI2RjIwNkU2MTIwNkQ2MTc5NjI2NTIwM0EyMjI5`

MGIwMDExMDAwMDAxMTExMDAwMDAxMTAxMTAwMTEwMDAxMDAwMTEwMTEwMDAxMTAxMDEwMDExMDEx
MDAxMTAwMTAxMDAxMTAwMTAwMDExMDAwMDAwMTEwMTExMDAxMTAwMDAwMDExMDExMDAxMTAwMTEw
MDAxMTAxMTEwMDExMDAxMDAwMTEwMTEwMDAxMTAwMDEwMDExMDExMTAwMTEwMDExMDAxMTAxMTAw
MDExMTAwMDAwMTEwMTExMDAxMTAxMDEwMDExMDExMDAxMTAwMTAxMDAxMTAxMTAwMDExMDAwMTAw
MTEwMTExMDAxMTAwMTAwMDExMDAxMDAwMTEwMDAwMDAxMTAxMTAwMTEwMDAxMDAwMTEwMTEwMDAx
MTEwMDAwMDExMDExMTAwMTEwMTAxMDAxMTAxMTAwMDExMDAxMDAwMTEwMDEwMDAxMTAwMDAwMDEx
MDExMTAwMTEwMDAwMDAxMTAxMTEwMDExMDAxMDAwMTEwMTEwMDAxMTAxMDEwMDExMDExMTAwMTEw
MDExMDAxMTAxMTEwMDExMDAxMTAwMTEwMTExMDAxMTAxMDEwMDExMDExMTAwMTEwMDEwMDAxMTAx
MTAwMDExMDEwMTAwMTEwMDEwMDAxMTAwMDAwMDExMDExMDAwMTEwMDEwMDAxMTAxMTEwMDExMDEw
MTAwMTEwMTEwMDExMDAwMDEwMDExMDExMDAwMTExMDAwMDAxMTAxMTAwMDExMTAwMTAwMTEwMDEx
MDExMDAxMTAwMDExMDAxMTAxMTAwMTEwMDAxMTAwMTAwMDExMDAwMDAwMTEwMTEwMDAxMTAwMTAw
MDExMDExMTAwMTEwMDEwMDAxMTAxMTAwMDExMTAwMTAwMTEwMTEwMDExMDAwMTEwMDExMDExMDAx
MTAwMDExMDAxMTAxMTAwMDExMTAwMTAwMTEwMTEwMDAxMTAwMDEwMDExMDExMDAxMTAwMTAxMDAx
MTAxMTEwMDExMDEwMDAwMTEwMDEwMDExMDAxMDEwMDExMDAxMDAxMTAwMTAxMDAxMTAwMTAwMDEx
MDAwMDAwMTEwMDExMDExMDAwMDEwMDExMDExMDAxMTAwMTEwMDAxMTAwMTAwMDExMDAwMDAwMTEw
MTEwMDAxMTAwMTAwMDExMDExMTAwMTEwMTAwMDAxMTAxMTEwMDExMDExMTAwMTEwMDEwMDAxMTAw
MDAwMDExMDExMDAwMTEwMDAxMDAxMTAxMTEwMDExMDAwMDAwMTEwMTEwMDExMDAxMDEwMDExMDEx
MDAwMTEwMTAxMDAxMTAxMTEwMDExMDAxMDAwMTEwMDEwMDAxMTAwMDAwMDExMDExMTAxMTAwMDAx
MDAxMTAxMTEwMDExMDAwMDAwMTEwMTEwMDAxMTEwMDAwMDExMDExMDAwMTExMDAxMDAxMTAxMTEw
MDExMDAxMTAwMTEwMTEwMDAxMTEwMDAwMDExMDExMDAwMTEwMTAxMDAxMTAxMTEwMDExMDAxMDAw
MTEwMDEwMDAxMTAwMDAwMDExMDExMDAxMTAwMTAxMDAxMTAxMTAwMDExMTAwMTAwMTEwMTExMDAx
MTEwMDEwMDExMDExMDAwMTEwMDAxMDAxMTAwMTAwMDExMDAwMDAwMTEwMTEwMDAxMTAxMDEwMDEx
MDExMDAxMTAwMDEwMDAxMTAxMTEwMDExMDEwMDAwMTEwMTExMDAxMTAxMDEwMDExMDAxMDAwMTEw
MDAwMDAxMTAxMTEwMDExMDAxMTAwMTEwMTEwMDExMDAxMTAwMDExMDExMDAxMTAwMTAwMDAxMTAx
MTAwMTEwMDExMDAwMTEwMTExMDAxMTAwMTEwMDExMDExMTAwMTEwMDExMDAxMTAxMTAwMDExMDAw
MTAwMTEwMTExMDAxMTEwMDEwMDExMDAxMDAwMTEwMDAwMDAxMTAxMTEwMDExMDAwMDAwMTEwMTEw
MDExMDAxMTAwMDExMDExMTAwMTEwMDEwMDAxMTAxMTEwMDExMDAxMTAwMTEwMTEwMDAxMTEwMDEw
MDExMDAxMDAxMTAwMTAxMDAxMTAwMTAwMTEwMDEwMTAwMTEwMDEwMDAxMTAwMDAwMDExMDExMDAx
MTAwMDEwMDAxMTAxMTAwMDExMTAwMTAwMTEwMTExMDAxMTAwMTEwMDExMDExMTAwMTEwMTAxMDAx
MTAxMTAwMDExMDEwMDAwMTEwMTEwMDAxMTEwMDEwMDExMDExMDAxMTAwMTAxMDAxMTAwMTAwMDEx
MDAwMDAwMTEwMTEwMDAxMTAwMDEwMDExMDExMDAwMTEwMTExMDAxMTAxMTAwMDExMDEwMTAwMTEw
MDEwMDAxMTAwMDAwMDExMDExMDAwMTEwMDExMDAxMTAxMTAwMTEwMDAxMTAwMTEwMTEwMDExMDAx
MTAwMDExMDExMDAxMTAwMTAxMDAxMTAxMTAwMDExMDEwMTAwMTEwMDEwMDAxMTAwMDAwMDExMDEx
MDAxMTAwMDEwMDAxMTAxMTAwMTEwMDExMDAwMTEwMTExMDAxMTAwMTAwMDExMDExMDAwMTEwMDEx
MDAxMTAxMTAwMDExMTAwMDAwMTEwMTEwMDAxMTEwMDEwMDExMDExMDAxMTAwMDExMDAxMTAxMTAw
MDExMDAwMTAwMTEwMTEwMDExMDAxMDAwMDExMDAxMDAwMTEwMDAwMDAxMTAxMTAwMDExMDEwMTAw
MTEwMTEwMDExMDAwMTAwMDExMDExMTAwMTEwMTAwMDAxMTAxMTAwMDExMDAwMTAwMTEwMDEwMDAx
MTAwMDAwMDExMDExMTAwMTEwMDAwMDAxMTAxMTAwMDExMTAwMDAwMTEwMTEwMDAxMTEwMDEwMDEx
MDExMTAwMTEwMDExMDAxMTAxMTAwMDExMTAwMTAwMTEwMTEwMDExMDAxMDEwMDExMDExMDAwMTEw
MTExMDAxMTAwMTAwMDExMDAwMDAwMTEwMTExMDAxMTAwMDAwMDExMDExMDAwMTEwMDAxMDAxMTAx
MTAwMDExMDExMTAwMTEwMTEwMDAxMTAxMDEwMDExMDAxMDAwMTEwMDAwMDAxMTAxMTAwMDExMDAx
MDAwMTEwMTEwMDAxMTAwMDEwMDExMDExMDAxMTAwMTAxMDAxMTAxMTAwMDExMDAwMTAwMTEwMTEx
MDAxMTAxMDAwMDExMDExMDAwMTEwMTAxMDAxMTAwMTAwMDExMDAwMDAwMTEwMTEwMDAxMTAxMDEw
MDExMDExMTAwMTEwMDEwMDAxMTAxMTEwMDExMDAwMDAwMTEwMTEwMDExMDAxMTAwMDExMDExMTAw
MTEwMDEwMDAxMTAwMTAwMDExMDAwMDAwMTEwMTExMDAxMTAwMTAwMDExMDExMDAwMTEwMTAxMDAx
MTAxMTAwMTEwMDEwMDAwMTEwMTEwMDExMDAxMTAwMDExMDExMTAwMTEwMTEwMDAxMTAxMTAwMDEx
MDEwMTAwMTEwMDEwMDAxMTAwMDAwMDExMDExMDAxMTAwMDEwMDAxMTAxMTAwMTEwMDExMDAwMTEw
MTExMDAxMTAwMTAwMDExMDExMDAwMTEwMTAxMDAxMTAwMTAwMDExMDAwMDAwMTEwMTEwMDAxMTAx
MDAwMDExMDExMDAwMTExMDAxMDAxMTAxMTEwMDExMDAxMTAwMTEwMTEwMDAxMTEwMDEwMDExMDEx
MDAxMTAwMDExMDAxMTAxMTAwMDExMDAwMTAwMTEwMTEwMDExMDAxMDAwMDExMDAxMDAxMTAwMTAx
MDAxMTAwMTAwMTEwMDEwMTAwMTEwMDEwMDAxMTAwMDAwMDExMDExMDAwMTEwMTAxMDAxMTAxMTAw
MTEwMDAxMDAwMTEwMTEwMDAxMTEwMDAwMDExMDExMDAxMTAwMTEwMDAxMTAxMTAwMTEwMDEwMTAw
MTEwMDEwMDAxMTAwMDAwMDExMDExMDAwMTEwMDAxMDAxMTAxMTAwMDExMDAxMDAwMTEwMTEwMDAx
MTAwMDEwMDExMDExMTAwMTEwMDEwMDAxMTAwMTAwMDExMDAwMDAwMTEwMTEwMDAxMTAwMTEwMDEx
MDExMDAxMTAwMDExMDAxMTAxMTAwMTEwMDExMDAwMTEwMTEwMDExMDAxMDEwMDExMDExMDAwMTEw
MTAxMDAxMTAwMTAwMDExMDAwMDAwMTEwMTEwMDExMDAwMTAwMDExMDExMDAxMTAwMTEwMDAxMTAx
MTEwMDExMDAxMDAwMTEwMTEwMDAxMTAxMDEwMDExMDAxMDAwMTEwMDAwMDAxMTAxMTEwMDExMDAx
MTAwMTEwMTExMDAxMTAxMDAwMDExMDExMDAwMTEwMDAxMDAxMTAxMTEwMDExMDAxMDAwMTEwMTEx
MDAxMTAxMDAwMDExMDAxMDAwMTEwMDAwMDAxMTAxMTAwMDExMDEwMDAwMTEwMTEwMDAxMTEwMDEw
MDExMDExMTAwMTEwMDExMDAxMTAxMTAwMDExMTAwMTAwMTEwMDEwMDAxMTAwMDAwMDExMDExMDAw
MTEwMDEwMDAxMTAxMTEwMDExMDEwMTAwMTEwMTExMDAxMTAxMDAwMDExMDAxMDAwMTEwMDAwMDAx
MTAwMTAwMDExMDAwMDAwMTEwMDAxMDExMDAwMTEwMDExMDEwMDAwMTExMDAxMDAxMTAxMTAwMTEw
MDEwMTAwMTEwMTExMDAxMTAwMTEwMDExMDExMTAwMTEwMTAwMDAxMTAxMTAwMDExMDAwMTAwMTEw
MTEwMDExMDAwMTEwMDExMDExMDAxMTAwMDExMDAxMTAxMTAwMDExMTAwMTAwMTEwMTEwMDExMDAx
MDEwMDExMDExMDAwMTEwMTExMDAxMTAwMTAwMDExMDAwMDAwMTEwMTEwMDExMDAxMDEwMDExMDEx
MDAwMTEwMTExMDAxMTAxMTEwMDExMDAxMDAwMTEwMTEwMDExMDAxMTAwMDExMDExMDAxMTAwMDEw
MDAxMTAwMTAwMTEwMDEwMTAwMTEwMDEwMDExMDAxMDEwMDExMDAxMDAxMTAwMTAxMDAxMTAwMTAw
MDExMDAwMDAwMTEwMDAxMDExMDAxMDAwMDExMDAxMDAwMTEwMDAwMDAxMTAxMTAwMDExMDEwMTAw
MTEwMDEwMDAxMTAwMDAwMDExMDExMDAwMTEwMTAxMDAxMTAxMTEwMDExMDAxMTAwMTEwMTEwMDAx
MTEwMDAwMDExMDExMDAwMTEwMTAxMDAxMTAwMTAwMDExMDAwMDAwMTEwMTExMDAxMTAxMDAwMDEx
MDExMDAwMTExMDAwMDAxMTAxMTAwMDExMDEwMTAwMTEwMTEwMDExMDAxMDAwMDExMDExMDAwMTEw
MTAxMDAxMTAwMTAwMDExMDAwMDAwMTEwMTEwMDAxMTAwMDEwMDExMDExMDAwMTEwMDExMDAxMTAx
MTAwMDExMTAwMDAwMTEwMTEwMDAxMTAxMDEwMDExMDAxMDAwMTEwMDAwMDAxMTAwMTEwMDExMDAx
MTAwMTEwMDExMDAxMTAwMDAwMDExMDAxMDAwMTEwMDAwMDAxMTAxMTAwMTEwMDEwMDAwMTEwMTEw
MDAxMTEwMDEwMDExMDExMDAxMTAwMTAxMDAxMTAwMTAwMDExMDAwMDAwMTEwMTEwMDAxMTAxMDEw
MDExMDExMTAwMTEwMDEwMDAxMTAwMTAwMDExMDAwMDAwMTEwMTEwMDExMDAxMDAwMDExMDExMDAx
MTAwMTEwMDAxMTAxMTEwMDExMDEwMDAwMTEwMTEwMDExMDAxMTAwMDExMDAxMDAwMTEwMDAwMDAx
MTAwMTEwMTEwMDAwMTAwMTEwMDEwMDAxMTEwMDA=

**Comment by masterjavaofficial** [comment]
0b01001101010010000110011101111001010011100101010001001101001100100100110101111010010001010111100101001110010101000100110100110010010011010111101001001101011110010100111001010100010011010011001001001101011110100100110101111001010011100101010001001101001100100100110101111010011001110111100101001110010101000100110100110010010011010111101001000101011110010100111001010100010011010111100101001101011110100100000101111001010011100101010001001101001100100100111001101010010110010111100101001110010101000100110100110010010011010111101001101011011110010100111001010100010011010011001101001101011110100101000101111001000010100100111001010100010011010011001001001101011110100100010101111001010011100101010001001101011110010100110101111010010000010111100101001110010101000100110101111010010011010111101001001101011110010100111001010100010011010111101001001101011110100100000101111001010011100101010001001101011110010100110101111010010000010111100101001110010101000100110100110010010011100110101001010001011110010100111001010100010011010011001001001101011110100110101101111001010011100101010001001101001100100100111001101010010101010111100101001110010101000100110101111001010011010111101001000001011110010100111001010100010011010011001000001010010011010111101001010101011110010100111001010100010011010011001101001101011110100100100101111001010011100101010001001101011110010100110101111010010000010111100101001110010101000100110100110010010011100110101001010001011110010100111001010100010011010011001001001110011010100101100101111001010011100101010001001101001100110100110101111010010100010111100101001110010101000100110100110010010011100110101001011001011110010100111001010100010011010111100101001101011110100100000101111001010011100101010001001101001100100100110101111010010001010111100101001110010101000100110100110011010011010111101001010001011110010000101001001110010101000100110100110010010011100110101001001001011110010100111001010100010011010011001001001101011110100100010101111001010011100101010001001101001100100100110101111010011010110111100101001110010101000100110101111001010011010111101001000001011110010100111001010100010011010011001101001101011110100101000101111001010011100101010001001101001100100100110101111010011001110111100101001110010101000100110100110010010011010111101001000101011110010100111001010100010011010011001001001110011010100100100101111001010011100101010001001101001100100100110101111010010001010111100101001110010101000100110100110011000010100100110101111010010010010111100101001110010101000100110101111001010011010111101001000001011110010100111001010100010011010011001101001101011110100100000101111001010011100101010001001101001100100100111001101010010110010111100101001110010101000100110100110011010011010111101001001001011110010100111001010100010011010111100101001101011110100100000101111001010011100101010001001101001100100100111001101010010110010111100101001110010101000100110101111001010011010111101001000001011110010100111001010100010011010011001001001101011110100110011101111001010011100101010001001101001100100100111001101010010110010111100100001010010011100101010001001101001100100100110101111010011010110111100101001110010101000100110100110011010011010111101001001101011110010100111001010100010011010011001001001101011110100101010101111001010011100101010001001101011110010100111001101010010101010111100101001110010101000100110101111001010011100110101001010101011110010100111001010100010011010111100101001101011110100100000101111001010011100101010001001101001100100100110101111010010010010111100101001110010101000100110100110011010011010111101001010101011110010100111001010100010011010011001101001101011110100101000101111001010011100101010001001101011110010000101001001101011110100100000101111001010011100101010001001101001100100100110101111010010101010111100101001110010101000100110100110010010011100110101001001001011110010100111001010100010011010011001001001101011110100110011101111001010011100101010001001101001100100100111001101010010110010111100101001110010101000100110100110010010011100110101001010101011110010100111001010100010011010111100101001101011110100100000101111001010011100101010001001101001100100100111001101010010101010111100101001110010101000100110100110010010011010111101001100011011110010100111001010100010011010011001101001101011110100100100101111001000010100100111001010100010011010011001001001110011010100101100101111001010011100101010001001101001100100100111001101010010010010111100101001110010101000100110101111001010011010111101001000001011110010100111001010100010011010011001001001101011110100101000101111001010011100101010001001101001100100100110101111010011010110111100101001110010101000100110100110011010011010111101001101011011110010100111001010100010011010011001001001101011110100100010101111001010011100101010001001101011110010100110101111010010000010111100101001110010101000100110100110010010011010111101001100111011110010100111001010100010011010011001000001010010011100110101001011001011110010100111001010100010011010011001101001101011110100100110101111001010011100101010001001101001100110100110101111010010100010111100101001110010101000100110101111001010011010111101001000001011110010100111001010100010011010011001001001110011010100100100101111001010011100101010001001101001100100100111001101010010110010111100101001110010101000100110100110011010011010111101001001001011110010100111001010100010011010011001001001110011010100100110101111001010011100101010001001101001100100100110101111010010101010111100101001110010101000100110101111001010011010111101001000001011110010000101001001110010101000100110100110010010011010111101001010101011110010100111001010100010011010011001001001101011110100110101101111001010011100101010001001101011110010100110101111010010000010111100101001110010101000100110100110011010011010111101001000001011110010100111001010100010011010011001101001101011110100100100101111001010011100101010001001101001100100100111001101010010110010111100101001110010101000100110100110010010011010111101001001001011110010100111001010100010011010011001001001110011010100100110101111001010011100101010001001101001100100100110101111010010101010111100101001110010101000100110100110010000010100100111001101010010100010111100101001110010101000100110101111001010011010111101001000001011110010100111001010100010011010011001001001110011010100100100101111001010011100101010001001101001100100100110101111010010101010111100101001110010101000100110100110010010011100110101001010101011110010100111001010100010011010111101001001110011010100101100101111001010011100101010001001101011110100100111001101010010110010011110100001010

![IMG_20220108_194010](https://user-images.githubusercontent.com/78401450/148646347-3b19c69b-77d3-4f86-8f2b-7c0f5baadc6b.jpg)

**Comment by htr-tech** [comment]
Account create kore token add koren ..

Ngrok er new version release er por theke old excutable er download speed onk kom pacchi ... nahole cloudflared use koren

**Comment by MERAJ774** [comment]
Hi

**Comment by MERAJ774** [comment]
![Uploading Screenshot_2022_0108_194836.jpg…]()
