### ISSUE TITLE
Edit Instagram Login 

### ISSUE THREAD

**Issue by xHeaveny** [htr-tech/zphisher#399]
![image](https://user-images.githubusercontent.com/69117321/148942618-a1761c18-9a4e-46e9-b0c0-b63927a1f31d.png) real site
![image](https://user-images.githubusercontent.com/69117321/148942637-c0e12f9c-6aef-4d18-811b-cfc10f604b90.png) zphishers site

The bottom with © 2022 Instagram from Meta is the important thing

**Comment by Shanley7** [comment]
Instagram account. abdifatah shanle7 
Wnt . Password.

**Comment by Bebebole** [comment]
edit the page with inspect element

**Comment by mendo0202** [comment]
Gulleremas

**Comment by mendo0202** [comment]
> ![image](https://user-images.githubusercontent.com/69117321/148942618-a1761c18-9a4e-46e9-b0c0-b63927a1f31d.png) real site ![image](https://user-images.githubusercontent.com/69117321/148942637-c0e12f9c-6aef-4d18-811b-cfc10f604b90.png) zphishers site
> 
> The bottom with © 2022 Instagram from Meta is the important thing

Gulleremas

**Comment by mendo0202** [comment]
Gulleremas

**Comment by mendo0202** [comment]
Gulleremas

**Comment by AliMilani** [comment]
## I created a new Instagram fake page 

https://user-images.githubusercontent.com/59066012/144991748-66c4045d-a8be-4bfb-90e2-2c32e3826ae8.mp4

## repo:
https://github.com/AliMilani/fake-instagram
@htr-tech

**Comment by htr-tech** [comment]
@AliMilani sheeesh 🎉 you can make a PR if you want... 
or else I will add that with proper credits... ( if you permit )

**Comment by htr-tech** [comment]
Sheeesh 🚀  [c54b939](https://github.com/htr-tech/zphisher/commit/c54b9395961626a40a64470db0f9abbbc7772136)
