### ISSUE TITLE
Issue with zphisher

### ISSUE THREAD

**Issue by akash-alu** [htr-tech/zphisher#4]
I'm trying to use zphisher for Instagram login page from past 8days trying a lot but something wrong.  I don't get website for victim "send the link to victim" there's no link it's blank  @htr-tech tahmid.rayat
![Screenshot_20200310-173937](https://user-images.githubusercontent.com/61458539/76311606-58886780-62f7-11ea-963c-8cb67cab40e9.png)

**Comment by htr-tech** [comment]
bro serveo is down ! Use Localhostrun or Ngrok

**Comment by Vintage-Extal** [comment]
Bro turn your WiFi on and use ngrok
