### ISSUE TITLE
Link problem

### ISSUE THREAD

**Issue by Albizy1** [htr-tech/zphisher#405]
Can't see the first link both on ngrok and cloudflare, and on both of them the second link give me a link finishing with @ and it isn't a valid link
![Schermata 2022-01-16 alle 17 10 11](https://user-images.githubusercontent.com/97843779/149668102-cb8d73fb-7c06-41c7-b2f3-422ea027ff83.png)
.
have already tried with sudo.

**Comment by krishpranav** [comment]
## try this methods:
- turn on the hotspot and run the script file (or)
- start the ngrok server manually

**Comment by xHeaveny** [comment]
you also can see the link in the logs normally

**Comment by Albizy1** [comment]
Working, thanks!!!!

Alessio Rebaudo
