### ISSUE TITLE
Zphisher

### ISSUE THREAD

**Issue by Parth9374** [htr-tech/zphisher#408]
When I clone it, it shows the program git is not installed. Install it by executing.
Pls help me in this.

**Comment by htr-tech** [comment]
first install git .

**Comment by Parth9374** [comment]
Now show unable to locate git

**Comment by krishpranav** [comment]
are you in linux or termux??

**Comment by krishpranav** [comment]
termux:
```
$ apt update
$ apt install git
```

linux:
```
$ sudo apt-get update
$ sudo apt-get install git
```
