### ISSUE TITLE
links wont generate on cloudflared!

### ISSUE THREAD

**Issue by TheOfficallPSVITA** [htr-tech/zphisher#409]
1 link line is empty and second one is also fked up. 
![Screenshot_2022-01-20_21_02_00](https://user-images.githubusercontent.com/54714510/150414178-61098bf9-9924-4370-8d06-20f21cf26a40.png)

**Comment by htr-tech** [comment]
are you running the script with sudo (root) permission ??

if not then run using sudo

**Comment by Smartykalyan** [comment]
Yes, I run the command with root permission still url 1 is not generating ? Please help me !!

**Comment by rameshwarTiwari1** [comment]
Same Issue please slove it

**Comment by arul637** [comment]
I am using windows operating system. I dont know how to install zphisher or any hacking my tools and i dont know how to start learning hacking, if you know what is first thing to learn for ethical hacking basic which tool is first to learn, please help me. My mail id is (sarulkumaran.21042004@gmail.com)

**Comment by Smartykalyan** [comment]
> Same Issue please slove it

Bro just remove the previous pakages and reinstall it again it works perfect and don't forget to use the sudo to run
