### ISSUE TITLE
Host Service links not showing

### ISSUE THREAD

**Issue by Vanceagher** [htr-tech/zphisher#41]
It just says "Send the link to the victim: "

**Comment by andr3s-retr0** [comment]
Is the serveo.net option?

**Comment by Vanceagher** [comment]
No, only LocalHost seems to work, for now I'm using NexPhisher.

**Comment by htr-tech** [comment]
use ngrok & turn on hotspot & try

**Comment by Henotech** [comment]
Nexphisher is not showing link

**Comment by htr-tech** [comment]
> Nexphisher is not showing link

I have updated that .. try after recloning
