### ISSUE TITLE
Only generates URL 2(not working)

### ISSUE THREAD

**Issue by phantomTermuxx** [htr-tech/zphisher#411]
It only generates url 2 which does not Work I have tried turning on hotspot and doing it But it doesnt work I think This might be a bug.![Screenshot_2022-01-25-19-14-26-85.jpg](https://user-images.githubusercontent.com/98404113/150993189-5d91ffa2-ce5e-4f0c-838e-b97fbc27f721.jpg)

**Comment by olegg789** [comment]
i have the same problem

**Comment by htr-tech** [comment]
if you are using android then turn on hotspot & try cloudflared

![image](https://user-images.githubusercontent.com/56682134/151284499-f848c358-a670-47b1-aafb-0cf9f1c6cea7.png)

**Comment by phantomTermuxx** [comment]
I DID turn hotspot on AND it was cloudflared a lot of other people are having the same problem it might be a bug

**Comment by Sanjivkuma** [comment]
Hey
