### ISSUE TITLE
URL 1 is not generating even using sudo command

### ISSUE THREAD

**Issue by Smartykalyan** [htr-tech/zphisher#414]
I first it works fine, After a day the url 1 is not showing even with cloudflare and ngrok

**Comment by rameshwarTiwari1** [comment]
yes I ahve same issue. when I installed zphisher first time it works fine after some hours is not working . it showing error in zphisher.sh line number 442 cloufare error

**Comment by Smartykalyan** [comment]
> yes I ahve same issue. when I installed zphisher first time it works fine after some hours is not working . it showing error in zphisher.sh line number 412 cloudflare error

Bro, my issue was solved unexpectedly. I removed all the packages and files of zphisher and then reinstall it again and now I gave root access to terminal and used sudo to run the zphisher.sh ====== Boom.... Now it's working perfect
