### ISSUE TITLE
Login Google su cellulari

### ISSUE THREAD

**Issue by Robbyfess** [htr-tech/zphisher#416]
Buonasera stavo provando zphisher e ho un problema
In pratica quando creo una pagina phishing di google su pc va perfettamente ma se provo ad aprire il link sul telefono non si apre, mi dice che è impossibile raggiungere il sito. Qualcuno sa come risolvere?

**Comment by Robbyfess** [comment]
Ho pensato potesse essere perché google riconosce che potrebbe essere una pagina di phishing quindi ho provato a cercare qualche sito su cui poter hostare il link ma non ne ho trovati voi avete idee?

**Comment by htr-tech** [comment]
try using cloudflared option & english please...
