### ISSUE TITLE
Websites not working 

### ISSUE THREAD

**Issue by ToddIsGod** [htr-tech/zphisher#427]
whenever i go to a link that i have setup using the zphisher, it just says something along the lines of "page not found" i have tested this on a few browsers, chrome, tor, firefox and brave, it doesnt seem to be working, anything i can do to fix this?

**Comment by hernandezkj97** [comment]
What port are you using?

**Comment by Bossjy** [comment]
whenever i go to a link that i have setup using the zphisher, it just says something along the lines of "page not found" i have tested this on a few browsers, chrome, tor, firefox and brave, it doesnt seem to be working, anything i can do to fix this?

**Comment by htr-tech** [comment]
did you closed the session ? 🤔  keep the session running

**Comment by Bossjy** [comment]
No I didn't close the section,
And what do you mean by port

**Comment by hernandezkj97** [comment]
The port is the page they are providing, I'm using Cloudflare right now, and it's working
