### ISSUE TITLE
Fb Login Page

### ISSUE THREAD

**Issue by Sicoman45** [htr-tech/zphisher#442]
Please update the Facebook page in system. It appears that Facebook face is broken in here.

**Comment by transyhoan** [comment]
Ồ

**Comment by Sicoman45** [comment]
Sir there is an problem fb page is not showing as a real page.The fb login
page just showing html structure all the css style is ended I don't know
why am I facing this problem please fix it🤕
I hope you will understand my English language because I am so week in
English subject 😁
