### ISSUE TITLE
Stuck in downloading ngrok

### ISSUE THREAD

**Issue by Natri123** [htr-tech/zphisher#443]
Hey l, can someone help me?
I'm stuck in installing ngrok, I install ngrok before downloading this tool.
Is there any way to skip this?

**Comment by Spellingis** [comment]
Me too its quite annoying using WSL2

**Comment by d1muny0** [comment]
if you are using Termux from Playstore you will get that error. get Termux from Fdroid it will fix the error.

**Comment by Spellingis** [comment]
I fixed it you need to uninstall zphisher then I reinstalled it then it worked
