### ISSUE TITLE
zphisher on Replit

### ISSUE THREAD

**Issue by sreinj** [htr-tech/zphisher#446]
after the step on what to use

host / 
ngrok / 
cloudflared /

the code/screen refreshes to replit homepage

![image](https://user-images.githubusercontent.com/74122186/155578289-82922c51-8d02-4fb6-a89e-02a3d2ee2766.png)

**Comment by 456428** [comment]
Yes super

**Comment by 456428** [comment]
Super

**Comment by htr-tech** [comment]
You Can Use this [REPL](https://replit.com/@htrtech/zphisher-repl)

Or just create a repl.it account & Import zphisher using the git url
