### ISSUE TITLE
[+] Installing ngrok...

[!] Error occured, Install Ngrok manually.
zphisher.sh: line 134: tput: command not found
zphisher.sh: line 135: tput: command not found

### ISSUE THREAD

**Issue by DarkKiller8456** [htr-tech/zphisher#449]
[+] Installing ngrok...

[!] Error occured, Install Ngrok manually.
zphisher.sh: line 134: tput: command not found
zphisher.sh: line 135: tput: command not found

How to fix this

**Comment by MSANDAN** [comment]
how do I fix this
[!] Error occured, Install Ngrok manually.
zphisher.sh: line 134: tput: command not found
zphisher.sh: line 135: tput: command not found
