### ISSUE TITLE
Cloudflared URL is missing?

### ISSUE THREAD

**Issue by alvissk50** [htr-tech/zphisher#456]
![image](https://user-images.githubusercontent.com/64791852/156965494-b98c830f-d2b2-469d-8500-1cba2ccfea8f.png)
I can't copy or access full URL when I try to use cloudflare. It just work on my local. Who did get the same case as mine? I need a help

**Comment by d1muny0** [comment]
mine too

**Comment by d1muny0** [comment]
I fixed mine, the problem is my wifi connection so I tried to use mobile data and the link was fixed

**Comment by Magissk** [comment]
> I fixed mine, the problem is my wifi connection so I tried to use mobile data and the link was fixed

Did the link connected via mobile data and copied to the victim and it worked?

**Comment by htr-tech** [comment]
yes it will...turn on mobile data + hotspot & try

**Comment by KrishnaSharma000** [comment]
I had the same problem . I was using zphisher tool in kali linux on virtual machine. I just established a vpn connection and ran the zphisher tool again and then it worked fine.
