### ISSUE TITLE
the link is not generating with Ngrok.io

### ISSUE THREAD

**Issue by fadelss** [htr-tech/zphisher#462]
Hi I did try to remove the program and reinstall it 
but without any luck  I did use the root but same noting is generating 
![10](https://user-images.githubusercontent.com/76804170/158003263-e45c6e07-2a6d-4739-b734-36918e1721d7.PNG)
![20](https://user-images.githubusercontent.com/76804170/158003267-f6c2c5f7-26b3-4a24-a16f-7e7354de10b0.PNG)
![30](https://user-images.githubusercontent.com/76804170/158003268-73d3fb22-ab35-4a16-8d09-c3c68a186833.PNG)
![50](https://user-images.githubusercontent.com/76804170/158003270-c8456da1-166a-48c3-9237-3475af9edaa8.PNG)

**Comment by htr-tech** [comment]
use cloudflared ( option 3)

**Comment by Joezzy07** [comment]
> 

how to get the instagram code bro

**Comment by htr-tech** [comment]
what ? explain please🧐
