### ISSUE TITLE
ON PC the links are not working can somebody help?

### ISSUE THREAD

**Issue by LOGOXX123** [htr-tech/zphisher#463]
i used cloudfare ngok with instagram faecbook Yahoo..... and the sites didnt work.

here a picture
https://user-images.githubusercontent.com/83647839/158070607-6f6f6077-0863-434f-b8ea-e4ad1bafdc81.png

Hope get a Answer and could it then fix.

**Comment by Sakib722** [comment]
The link send to the  victim should be opened by him then only it will work

**Comment by LOGOXX123** [comment]
> 

Yes i open then a new tab and put the link in and on the end is a @ if i delete it its a site but not working and with @ is not a site

**Comment by akku-cpu** [comment]
Linki is showings host error

**Comment by LOGOXX123** [comment]
> Linki is showings host error

Ye without @ its host error ig
