### ISSUE TITLE
Ngrok not working

### ISSUE THREAD

**Issue by nadesho3er** [htr-tech/zphisher#466]
Not showing victim link
![Uploading Screenshot_20220314_223534.jpg…]()

**Comment by Tkashu** [comment]
> 
> Not showing victim link
> ![Uploading Screenshot_20220314_223534.jpg…]()
> 

Yes not working

**Comment by Magissk** [comment]
Which of the options are working?

**Comment by htr-tech** [comment]
Use Cloudflared ( Option 3 )

Turn on device hotspot before that

**Comment by programcoder369** [comment]
> 
> Not showing victim link
> ![Uploading Screenshot_20220314_223534.jpg…]()
> 

install ngrock by bash zphisher.sh, after cloning into zphisher
