### ISSUE TITLE
Request for a discord account

### ISSUE THREAD

**Issue by Gamerique** [htr-tech/zphisher#470]
Please also add a discord page in the list of phishing page. Discord Nitro page🙏🙏

**Comment by Krovikan-Vamp** [comment]
I can see what I can do...

**Comment by AliMilani** [comment]
I create the discord fake page :)

https://user-images.githubusercontent.com/59066012/161009554-eddaede1-35d9-4086-88e3-af98f2545638.mp4



If you want to add it
I put it in https://github.com/AliMilani/fake-discord
@htr-tech

**Comment by htr-tech** [comment]
> Thanks Htr-Tech/Zphisher sir, On behalf of accepting request of adding discord page I am so very thankful for your time and support.

Its not me who created the page...its @[AliMilani](https://github.com/AliMilani)

**Comment by Gamerique** [comment]
Okk sure... But I have just a doubt!

Will that Discord phishing page made by @AliMilani be added to Zphisher??

Please!

**Comment by Gamerique** [comment]
> I create the discord fake page :)
> 
> https://user-images.githubusercontent.com/59066012/161009554-eddaede1-35d9-4086-88e3-af98f2545638.mp4
> 
> 
> 
> If you want to add it
> I put it in https://github.com/AliMilani/fake-discord
> @htr-tech 

Thanks a lot @AliMilani ! Love u from heart❣️❣️

**Comment by Krovikan-Vamp** [comment]
@AliMilani Why not make a PR?

**Comment by htr-tech** [comment]
> added

Added 🚀

**Comment by Gamerique** [comment]
Awesome, thanks a lot brother!!❣️
@TahmidRayat
