### ISSUE TITLE
link not working

### ISSUE THREAD

**Issue by grodioz** [htr-tech/zphisher#471]
after I select a port forwarding service, I get this:
"Setting up server...                                                     
cp: cannot remove '.server/www/index.php': Permission denied                 
cp: cannot remove '.server/www/login.php': Permission denied                 
cp: cannot remove '.server/www/users.php': Permission denied                 
cp: cannot remove '.server/www/ip.php': Permission denied "

then it generates a url 2 but url 1 stays blank, the url 2 isn't working. this wasn't an issue before! what do I need to do?

**Comment by htr-tech** [comment]
run using sudo...
