### ISSUE TITLE
Link doesn´t work

### ISSUE THREAD

**Issue by thomymz** [htr-tech/zphisher#472]
![image](https://user-images.githubusercontent.com/102012199/159362376-58d8de3d-3731-4dc6-9c43-ad8e2c718340.png)

**Comment by thomymz** [comment]
![image](https://user-images.githubusercontent.com/102012199/159362558-5b967d5a-0328-4ce8-86f8-cf6175d2e716.png)

**Comment by thomymz** [comment]
I used cloudflare

**Comment by htr-tech** [comment]
did you closed the terminal ? 🙄

**Comment by thomymz** [comment]
didn´t

**Comment by thomymz** [comment]
Tried with hotspot, vpn and still not working

**Comment by htr-tech** [comment]
if you are a root user then run with sudo 🤖 it should work fine
