### ISSUE TITLE
CloudFlare don’t work

### ISSUE THREAD

**Issue by hentaim** [htr-tech/zphisher#478]
after creating the link it doesn't work
![EB224FB4-16F9-4ED5-9196-29A2DB5CC4D7](https://user-images.githubusercontent.com/68517545/160383771-52c64a23-b835-4be3-a8ca-b0517c854c30.png)
![Uploading 415BFFC4-CCD8-4E0F-9CAF-17C72C365C6A.png…]()

**Comment by htr-tech** [comment]
try again please.... check if the php server has started or not

**Comment by Pepex213** [comment]
me too

**Comment by htr-tech** [comment]
sometimes it happens with cloudflare..try using again or use a different tunneling option.
