### ISSUE TITLE
Telegram not found

### ISSUE THREAD

**Issue by LEGENDXOP** [htr-tech/zphisher#481]
Hey where is telegram clone page???

**Comment by htr-tech** [comment]
Telegram Login Depends on OTP ...
**zphisher** doesn't have the functionality for bypassing **OTP** ... that's why not added...
You can try advphishing by Ignitetch .... I think that has Telegram support...

**Comment by LEGENDXOP** [comment]
Okay thanks

**Comment by AliMilani** [comment]
> Hey where is telegram clone page???

It is possible
but is a little different from other fake pages
I created a fake telegram web that send localstorage data
And then you can easily use localstorage

**Comment by AliMilani** [comment]
@htr-tech 

Watch this 

https://user-images.githubusercontent.com/59066012/161075234-060d65eb-5852-4cb2-b8da-f5b2eed73b0b.mp4

**Comment by LEGENDXOP** [comment]
> @htr-tech
> 
>  fake-telegram.mp4

Which tool bro

**Comment by AliMilani** [comment]
> > @htr-tech
> > fake-telegram.mp4
> 
> Which tool bro

https://github.com/AliMilani/fake-telegram

**Comment by LEGENDXOP** [comment]
> @htr-tech
> 
>  fake-telegram.mp4

U have tutorial how to use this tool?
