### ISSUE TITLE
both ngrok and cloudfared not working

### ISSUE THREAD

**Issue by VietnameseWeeb** [htr-tech/zphisher#486]
For some reason both ngrok and cloudfared not working :(
(I'm using repl.it to run zphisher btw)
![IMG_20220402_142907](https://user-images.githubusercontent.com/78286451/161372274-a2e89aa9-7fee-4cf0-a44d-e73b2a49f3fe.jpg)
![IMG_20220402_142956](https://user-images.githubusercontent.com/78286451/161372276-fac83305-f9ed-487f-bd38-31e47afdf1d1.jpg)

**Comment by htr-tech** [comment]
I think thats on issue on the repl php server 🐛

You can still use zphisher on google cloud shell ( [Link](https://shell.cloud.google.com/?show=ide%2Cterminal) )

Or use it on your machine

**Comment by VietnameseWeeb** [comment]
Hmm 🤔 ok, thank for the advice 👍
