### ISSUE TITLE
On CTRL + C -- shuts down SSH service on local machine

### ISSUE THREAD

**Issue by slayt12** [htr-tech/zphisher#49]
[~] Initializing...(localhost:80)
 [~] Launching Serveo ..
 [~] Send the link to victim :
 [~] Waiting for Login Info, Ctrl + C to exit.
^C

Remote side unexpectedly closed network connection

Running on both Ubuntu 20.04 and Kali

**Comment by mmadams3370** [comment]
What would i do now ?

**Comment by htr-tech** [comment]
ok .. use nexphisher . that has ctrl+c catcher option . i wiil soon release zphisher next version

https://github.com/htr-tech/nexphisher

**Comment by Smartbizzy** [comment]
Please how will I install Ubuntu in my Termux and the uses please.

**Comment by htr-tech** [comment]
@Smartbizzy  https://play.google.com/store/apps/details?id=exa.lnx.a&hl=en
