### ISSUE TITLE
My zphisher links wont work

### ISSUE THREAD

**Issue by cozrex** [htr-tech/zphisher#494]
![Capture](https://user-images.githubusercontent.com/32781784/162887054-8a7ed870-1885-49ef-a07a-d576cb1ae27d.JPG)
It gives me the same error for all the links!!! I have read around and people say if im using root then well boot in root but i dont know how to do that!!!

**Comment by htr-tech** [comment]
just run `sudo zphisher.sh`


{first clear the basics of linux before using it....}

**Comment by cozrex** [comment]
i finally figured it out last night i updated to the gui and for somereason that gave me priveledge to do sudo su which in turn worked haha can you close that github i dont have access from my phone

Sent from my iPhone

On Apr 12, 2022, at 9:41 AM, Tahmid Rayat ***@***.***> wrote:

﻿

just run sudo zphisher.sh

{first clear the basics of linux before using it....}
