### ISSUE TITLE
ERR_NGROK_6022 ISSUE

### ISSUE THREAD

**Issue by minhle1507** [htr-tech/zphisher#495]
### Describe the bug

Hi, I have a page screen  look like below

Is it still working ?

![image](https://user-images.githubusercontent.com/73882052/163223731-56fc41f9-d2d8-4b00-9871-b0ebfa4e97d4.png)

**Comment by minhle1507** [comment]
same with https://replit.com/@htrtech/zphisher-repl

**Comment by htr-tech** [comment]
first create a free account on ngrok.com then copy the _ngrok token_
then type `./.server/ngrok authtoken <your-token>` after that try using it again...

If you don't want this hassle simply use option 3 (cloudflared)
