### ISSUE TITLE
Custom Mode

### ISSUE THREAD

**Issue by Dreadox** [htr-tech/zphisher#496]
### Describe the solution you'd like

Hello guys. Is there a way to add a custom page ? Like, crypto.com or something else. Im trying to add a custom website, but it doesnt work, it is redirecting me to Discord

**Comment by htr-tech** [comment]
First copy your template to the `.sites` directory

then add an input just like [#L756](https://github.com/htr-tech/zphisher/blob/master/zphisher.sh#L756)
#
### example :
Copy the files inside `.sites/crypto` folder... add the following lines after [#L759](https://github.com/htr-tech/zphisher/blob/master/zphisher.sh#L759)

```
35)
	website="crypto"
	mask='http://get-crypto-free'
	tunnel_menu;;
```

**Comment by Dreadox** [comment]
Ok, i will try right now. And also, what if i have my own website template ? Should i do the same thing ?

**Comment by Dreadox** [comment]
Oh wait, i dont have any .sites folder here. Im in zphisher folder, but nothing about .sites , only few files

**Comment by Dreadox** [comment]
And in zphisher.sh, i already have 

35)
			website="WALLET"
			mask='http://verifyyourwallet.com/'
			tunnel_menu;;

**Comment by Dreadox** [comment]
As i can see, the repo from github got some folders such as .sites , .img, but when i clone it, i receive only some files :D

**Comment by htr-tech** [comment]
> As i can see, the repo from github got some folders such as .sites , .img, but when i clone it, i receive only some files :D

type `ls -a` in order to list all files & directories ... 🚀

**Comment by Dreadox** [comment]
Yes, but in home/zphisher, i dont see .sites . So i can add the site. And other thing, when im using this tool, when i type the ip, the website is working for me. But not for other people. Tried with my friends, and they cant see anything

**Comment by Dreadox** [comment]
![image](https://user-images.githubusercontent.com/80052559/163434519-0d5263ec-6926-44de-b896-1f911f652edc.png)

This is what i have in Zphisher folder

**Comment by Dreadox** [comment]
Oh, okey, i found it. Now, all i have to do is to put my website files, right ? And then adding the option, right ? Is there a possible way to use https instead http ? So he can see that the website got SSL Certificate and it is trusty ?

**Comment by Dreadox** [comment]
And the last question sir, because you're a genius. Lets say i already have a website, for scamming. Is there a way to track the login credentials through that website ?

**Comment by htr-tech** [comment]
> And the last question sir, because you're a genius. Lets say i already have a website, for scamming. Is there a way to track the login credentials through that website ?

ugh.... I prefer to use it for ethical purpose...

anyway understand how phishing pages work ( capture the credentials ,, you will get your answer )

**Comment by htr-tech** [comment]
> Oh, okey, i found it. Now, all i have to do is to put my website files, right ? And then adding the option, right ? Is there a possible way to use https instead http ? So he can see that the website got SSL Certificate and it is trusty ?

upload to own webhosting with proper domain & ssl

**Comment by Dreadox** [comment]
> Owner

It is for ethical purpose, no worries, im not gonna hack anybody :D I just want to learn. The thing is , i have the website, but when i put the credentials, i dont receive anything. I receive the credentials only if im using the ip as link

**Comment by htr-tech** [comment]
`if you copy paste the files from zphisher... there should be a txt file that contains the creds`

**Comment by Dreadox** [comment]
Yeah i know, but i want to use my website, in order to gain the credentials

**Comment by htr-tech** [comment]
upload the files directly to your web.....

**Comment by Dreadox** [comment]
Well, the thing is , i cloned a scamming website, got the index.html and other things. The base of that webpage is that, when somebody enters his credentials, the owner will receive the credentials via E-mail. I want to receive them via linux console. So i need to put, somehow, the files from the webpage, in that zphisher app, and clone and entire page

**Comment by htr-tech** [comment]
well, thats not related to zphisher... if you want to add new things...you can (open source)...
but I can't help much in that case

you can change the `action=` in that page in order to redirect it to php /other files
