### ISSUE TITLE
Error occured, Install Ngrok manually.

### ISSUE THREAD

**Issue by Jo-2004** [htr-tech/zphisher#497]
### Which environment you are using ?

Termux / Android

### Describe the bug

Keeps saying Error occured, Install Ngrok manually. This is the first time its happening to me 
![Screenshot_20220413-193301_Termux](https://user-images.githubusercontent.com/103575108/163238072-61811dea-248b-4baa-a9f7-e037bd46f0a5.jpg)

### Provide log output [Optional]

```shell
[+] Installing ngrok...

[!] Error occured, Install Ngrok manually.
```

**Comment by htr-tech** [comment]
Maybe your internet was unstable ? reclone & try again

if it doesn't work download ngrok binary of your device architecture & replace it on `.server` directory
