### ISSUE TITLE
Does it check the entered values ?

### ISSUE THREAD

**Issue by minanagehsalalma** [htr-tech/zphisher#5]

**Comment by htr-tech** [comment]
### No it just checks the ip , useragent , username & Password

**Comment by minanagehsalalma** [comment]
> No it just checks the ip , useragent , username & Password

Dude this isn't checking !
This loging - storing - recording - catching  !

I meant verifying the user/pass is correct or not before letting the victim proceed to the next page just like how a really page works !!

@htr-tech

**Comment by htr-tech** [comment]
@minanagehsalalma Bro its a phishing page so user/pass is correct or not is not a matter :)

**Comment by minanagehsalalma** [comment]
> Bro its a phishing page so user/pass is correct or not is not a matter

@htr-tech 
Are you kidding me ? It  matters it all what matters .... if this doesn't matter then nothing really matter about the tool !!
