### ISSUE TITLE
Ngrok.io doesn't sent any link (WSL)

### ISSUE THREAD

**Issue by bondaww** [htr-tech/zphisher#50]
<img width="285" alt="Untitled" src="https://user-images.githubusercontent.com/69083389/89116789-133f1f00-d4be-11ea-951d-063adac26036.png">

I'm using from WSL. And, everytime I use ngrok or serveo, it doesn't give me any link. 
Ubuntu Version- 20.04
Zphisher V2.0

**Comment by MoisesTapia** [comment]
@bondaww run with root acces 
$ sudo bash zphisher.sh

**Comment by htr-tech** [comment]
Turn on device Hotspot & try again .. links will appear !!

**Comment by bondaww** [comment]
> Turn on device Hotspot & try again .. links will appear !!

Still not showing!
