### ISSUE TITLE
tahmid, ami n00b xaba (dev of dh hb), asha korsi chinso.. tomar sathe ektu contact kora lagto.. kintu sobkichu thekei offline dekhtasi..

### ISSUE THREAD

**Issue by tempaccforissue** [htr-tech/zphisher#502]
### Describe the bug

parle ektu eitay knock diyo.. ager id disable: https://www.facebook.com/profile.php?id=100079471097379

**Comment by htr-tech** [comment]
Hii **MJ** (YAS) ,

`Q3VycmVudGx5IG9mZmxpbmUgZnJvbSBhbGwgc29jaWFsLi4uKG9ubHkgbWF0cml4KS4uLlBNIG9uIFRHIEJvdCAoQnJpZ2VkIHRvIE1hdHJpeCkgOiBAQ2F0ekRNYm90Cg==`

**Comment by tempaccforissue** [comment]
@htr-tech 😑🐸🐥
