### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by yrndtk** [htr-tech/zphisher#506]
![Screenshot_20220426-035920_Firefox Focus.jpg](https://user-images.githubusercontent.com/104317790/165263990-2e2f1609-cc7b-4a09-842d-6cd7c7034f74.jpg)

**Comment by htr-tech** [comment]
did the first link appear ? if not then the url is not generated

**Comment by yrndtk** [comment]
Sorry im a newbie i thought i was on the most up to date Termux lol

**Comment by yrndtk** [comment]
Can the url be sent to more than one person ?

**Comment by htr-tech** [comment]
Use the link generated from cloudflared.,.
