### ISSUE TITLE
Localhost.run Not Working

### ISSUE THREAD

**Issue by Vanceagher** [htr-tech/zphisher#51]
Here is the error

`u0_a1050@ssh.localhost.run: Permission denied (publickey).`

**Comment by poyanayeri** [comment]
> 
> 
> Here is the error
> 
> `u0_a1050@ssh.localhost.run: Permission denied (publickey).`

Have the same problem :(

**Comment by poyanayeri** [comment]
> 
> 
> Here is the error
> 
> `u0_a1050@ssh.localhost.run: Permission denied (publickey).`

You need to Generate a SSH key and add it to your ssh-agent.
Follow the steps in below link .

[https://docs.github.com/en/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent](url)

**Comment by htr-tech** [comment]
yap . or use ngrok
