### ISSUE TITLE
Not really a problem, good job guys!

### ISSUE THREAD

**Issue by gayfalcon** [htr-tech/zphisher#511]
### Is your proposal related to a problem?

Hello there!

I've been enjoying this tool for quite a while now and I finally got the chance to put it to good use.
My company wants to do a "self audit" and we're wondering if it's possible to use our own company domain to create the phishing attack? Any suggestions would mean gold! 

To creators:

I can prove that I'll do it legitimately, so any guides would be great! 

### Describe the solution you'd like

We'd like to know how to use our own domain with this tool.

**Comment by htr-tech** [comment]
you can upload the templates to web hosting or configure the domain using any web server

**Comment by gayfalcon** [comment]
Thank you for the answer!

However, I'm still not sure how to make the web server use the full functionality and retrieve the credentials.

Could you please point me to the right direction?

**Comment by htr-tech** [comment]
Just upload the files inside the `.sites` folder to your hosting..

https://www.hostinger.com/tutorials/website/how-to-upload-your-website
https://www.digitalocean.com/community/tutorials/how-to-set-up-apache-virtual-hosts-on-ubuntu-16-04

**Comment by gayfalcon** [comment]
Thanks,

This helped a lot and we already achieved great results with it! 

Thank you again and keep up the good work!
