### ISSUE TITLE
Intagram Login button is desactivated 

### ISSUE THREAD

**Issue by otman-dev** [htr-tech/zphisher#517]
### Which environment you are using ?

Kali linux

### Describe the bug

all works well instagram and facebook tested but the login button in instagram page is desactivated when the link is succesfully generated please fix it fast !! <3 full support

### Provide log output [Optional]
the button html tag has a desactivaterd argument with no values i guess that souldn't be there or should be setted to false

**Comment by htr-tech** [comment]
According to instagram's [security tips](https://help.instagram.com/369001149843369) password must contain at least 6 digits..

![image](https://user-images.githubusercontent.com/56682134/168155976-dbe8850e-ccc0-45c0-8da4-499554dcf017.png)

After typing 6 digits the button works..

**Comment by otman-dev** [comment]
bless you <3
