### ISSUE TITLE
My packages don't install automatically

### ISSUE THREAD

**Issue by atlasahhaaa** [htr-tech/zphisher#525]
When i run zphisher my packages don't install automatically

**Comment by 1RaY-1** [comment]
Can you tell what packages or better, show a screenshot?

**Comment by nw3e** [comment]
> When i run zphisher my packages don't install automatically

what os are you on

**Comment by Nfglotus666** [comment]
same

**Comment by htr-tech** [comment]
> same

which operating system you are using ?

**Comment by Nfglotus666** [comment]
nvm i fixed it
