### ISSUE TITLE
Dont give link 

### ISSUE THREAD

**Issue by Prhm021** [htr-tech/zphisher#53]
Hi this is don't work for me! Why?!
When i chose Instagram and ngrok dont give me link to send victim!!!🤕

**Comment by Veiro1234q** [comment]
Same problem

**Comment by htr-tech** [comment]
@Veiro1234q @Prhm021  turn on hotspot & try again

**Comment by Prhm021** [comment]
> @Veiro1234q @Prhm021  turn on hotspot & try again
> 
> 

Thank you so much❤
