### ISSUE TITLE
Link does not work

### ISSUE THREAD

**Issue by Mid0ree** [htr-tech/zphisher#537]
### Which environment you are using ?

Linux / Desktop

### Describe the bug

Some error message I dont understand at the top when link is generated
grep: .cld.log: No such file or directory

Link 1 does not generate, link 2 generates but doesnt lead anywhere. Example of link 2: http://get-discord-nitro-free@
when I put this into my browser to see if it works, it says "Site cannot be reached, check if there is a typo"

grep: .cld.log: No such file or directory

[-] URL 1 :

[-] URL 2 : http://get-discord-nitro-free@

[-] Waiting for Login Info, Ctrl + C to exit...

**Comment by Hazzy234** [comment]
Same

**Comment by kree-star** [comment]
guys..i think i found the solution...everytime your zphisher doesn't show any functioning link, delete a hidden file in zphisher folder...the file name is .cld.log ..... and restart the terminal... i hope this helps you..cheers

**Comment by htr-tech** [comment]
Try using sudo (root permission)

**Comment by krisdowis** [comment]
You haven't set up ngrok on your machine that's why
