### ISSUE TITLE
Facebook had a new theme

### ISSUE THREAD

**Issue by vobao2005** [htr-tech/zphisher#54]
m.facebook.com

**Comment by htr-tech** [comment]
i will update a few days later ... if you can make phishing page then create a pr

**Comment by vobao2005** [comment]
> i will update a few days later ... if you can make phishing page then create a pr

I tried buy the login button is not work, but mbasic.facebook.com is well
Detail: http://vonb.rf.gd/Manager.php

**Comment by htr-tech** [comment]
@vobao2005  nothing works
