### ISSUE TITLE
Cld.log

### ISSUE THREAD

**Issue by Santy-Gz** [htr-tech/zphisher#540]
### Describe the bug

![Screenshot_20220626_001641_com termux](https://user-images.githubusercontent.com/69918140/175800553-ae863920-2df1-4848-9163-9d51ee5354c1.jpg)

I dont know what i should yo say about it :)

**Comment by htr-tech** [comment]
Type `uname -m` & Share the Output

Also check if there is the cloudflaed binary insides `.server` folder
![image](https://user-images.githubusercontent.com/56682134/175811428-b704fd24-8fff-4b7f-999d-815329d0805c.png)

**Comment by Santy-Gz** [comment]
> Type `uname -m` & Share the Output
> 
> Also check if there is the cloudflaed binary insides `.server` folder ![image](https://user-images.githubusercontent.com/56682134/175811428-b704fd24-8fff-4b7f-999d-815329d0805c.png)


Here is umane - m
![Screenshot_20220626_091405](https://user-images.githubusercontent.com/69918140/175818500-e99e95eb-c55f-4433-a9c2-8d07a53ad69b.jpg)

And here is cloudflare
![Screenshot_20220626_091517](https://user-images.githubusercontent.com/69918140/175818542-59e14924-3601-4b82-9d4a-a66e90c7bb8b.jpg)

**Comment by Santy-Gz** [comment]
What can i do? 🥺

**Comment by htr-tech** [comment]
give executable permission to those two binary

`chmod 777 .server/cloudflared`
`chmod 777 .server/ngrok`

then try

**Comment by Santy-Gz** [comment]
> give executable permission to those two binary
> 
> `chmod 777 .server/cloudflared` `chmod 777 .server/ngrok`
> 
> then try

Nothing bro, it continue same... :(

**Comment by htr-tech** [comment]
Termux has a package called cloudflared..
install that by executing `pkg install cloudflared -y`

![Screenshot_20220627-130028_Termux](https://user-images.githubusercontent.com/56682134/175879829-d6ff64aa-b0a1-4105-be74-4846167ed2ff.jpg)

& then `cloudflared tunnel -url 127.0.0.1:8080 --logfile dat.log`

![Screenshot_20220627-130427_Termux](https://user-images.githubusercontent.com/56682134/175879890-34a0f9de-0f7e-4f4c-b6c7-050594c29cac.jpg)

Check if it gives a link (if not turn on hotspot & try again)

if it works then simply run zphisher & host on localhost & in the other tab repeat the cloudflared step

**Comment by Santy-Gz** [comment]
No, now it isn't givingme a link, the problem is so weird :((((

**Comment by htr-tech** [comment]
Can you provide the output / screenshot..

**Comment by Santy-Gz** [comment]
:0
This is now working, Thank You So Much brooo <3

**Comment by Santy-Gz** [comment]
Thx ♥️
