### ISSUE TITLE
URL #1 Not showing any value

### ISSUE THREAD

**Issue by RedFurrFox** [htr-tech/zphisher#543]
### Which environment you are using ?

Termux / Android

### Describe the bug

So I am doing a simulation for work purposes to check if my members will click the phishing link... While I am using your tool, I encounter this problem:

![Screenshot_2022_0702_231523](https://user-images.githubusercontent.com/80197308/177006495-86038ee5-3f32-43c0-b854-47d64f569f0e.png)

I wish I could find a way to send you a log while this tool run, but I don't know how to do it on your tool.

**Comment by htr-tech** [comment]
could you please run `./.server/cloudflared tunnel -url 127.0.0.1:8080 --logfile dat.log` inside zphisher directory
& Check if it provides a link ,,

![image](https://user-images.githubusercontent.com/56682134/177026007-f23b65a6-b7d2-40c9-9fa1-31caca59c857.png)

**Comment by RedFurrFox** [comment]
Opppssss... My bad 😆

Based on the log which you provide a command:
(`./.server/cloudflared tunnel -url 127.0.0.1:8080 --logfile dat.log`)

It stated that I'm just having an internet connection problem

[Screenshot_2022_0703_225212.png](https://user-images.githubusercontent.com/80197308/177045393-27e0b16f-3d13-4c24-8a5c-6a77415b5be6.png)

Sorry for the inconvenience bro

**Comment by RedFurrFox** [comment]
Thanks again tho...
