### ISSUE TITLE
grep: .cld.log: No such file or directory

### ISSUE THREAD

**Issue by severesalt** [htr-tech/zphisher#546]
Hi I'm running this on a mac if that matters. I've tried running the program in root and I've tried using a hotspot. I've also tried using replit but that ends up with an an argo tunell error 1033. I've also tried uninstalling and reinstalling.
<img width="421" alt="Screen Shot 2022-07-10 at 8 39 13 PM" src="https://user-images.githubusercontent.com/109048544/178169063-37da5c19-ce15-42ad-a2ad-95b1b2823706.png">

**Comment by htr-tech** [comment]
zphisher is now supported on linux distributions only
