### ISSUE TITLE
Not giving me link on termux

### ISSUE THREAD

**Issue by mwalla10** [htr-tech/zphisher#55]
![Screenshot_20200807_160650](https://user-images.githubusercontent.com/57600916/89648564-107e6880-d8c8-11ea-9f92-1c0984a11581.jpg)

**Comment by morenomar** [comment]
a mi tampoco me da link

**Comment by Prhm021** [comment]
Turn on your hotspot and try again

**Comment by mwalla10** [comment]
It worked thanks

**Comment by hooman-htg** [comment]
I've tried again but not worked!
What's the problem?

**Comment by htr-tech** [comment]
@hooman-htg  Turn on your hotspot and try again
