### ISSUE TITLE
[Broken Page]: 

### ISSUE THREAD

**Issue by Hxkingx** [htr-tech/zphisher#552]
### Which Page is broken ?

hi i have problem with zphisher 
![image](https://user-images.githubusercontent.com/102569737/179636778-4525217a-dd25-4625-8153-fabff5008a4d.png)
can i repair this ?

**Comment by Elcavz** [comment]
Same problem here

**Comment by htr-tech** [comment]
all the templates ?? or a specific one ?

**Comment by Hxkingx** [comment]
only traidional faceebok login

**Comment by sravan-blockchain** [comment]
for instagram traditional login page too

**Comment by htr-tech** [comment]
Update Zphisher & use the new tunneling option
