### ISSUE TITLE
How can I change the redirect website in the link

### ISSUE THREAD

**Issue by timkatta5** [htr-tech/zphisher#553]
### Is your proposal related to a problem?

The problem is that I would like to specify to which site the login button redirects, it currently uses a default website it redirects to.

### Describe the solution you'd like

Once we select the site template we want to use, your software should asks us for redirect link

**Comment by htr-tech** [comment]
You can change it by editing the `login.php` under `.sites` directory..

In future i will add an option to add custom redirect link

**Comment by sravan-blockchain** [comment]
@htr-tech  There was a big problem with the cloudfared link. After opening the link for one time.. it showing its a phishing website in the browser from second click on wards. Please fix this problem.

**Comment by htr-tech** [comment]
update zphisher & use new port forwarding option
