### ISSUE TITLE
Detected as phishing website on second click onwards

### ISSUE THREAD

**Issue by sravan-blockchain** [htr-tech/zphisher#554]
### Which environment you are using ?

Linux / Desktop

### Describe the bug

I have used cloudfared in old version many times. The link generated works fine for many clicks without any problem. But now after in updated  version from second hit on the link the browser is detecting as phishing website.
please solve the problem.
![image](https://user-images.githubusercontent.com/99798733/180613887-858be8dc-a09e-4285-bcde-0661576ab469.png)

**Comment by TriDEntApollO** [comment]
Same problem cloudflared detects it as phishing site just after second click and flags/blocks the site after the update

**Comment by awrshiia** [comment]
same problem

**Comment by htr-tech** [comment]
Update zphisher & use the new forwarding option
