### ISSUE TITLE
[Broken Page]: 

### ISSUE THREAD

**Issue by rajucs** [htr-tech/zphisher#558]
### Which Page is broken ?

when choosing insta phissing from ngrok server got this error

zphisher.sh: line 410: curl: command not found

**Comment by htr-tech** [comment]
which os are you using ? 

make sure you have requirements installed

**Comment by rajucs** [comment]
I tried with linux i had already installed php and when run your code depencies installed not sure all installed or not.i tried with link but the links not worked. ☹️

**Comment by htr-tech** [comment]
you should have curl, php & unzip installed in your system
