### ISSUE TITLE
Localhost with public IP 

### ISSUE THREAD

**Issue by Zunaira-Malik** [htr-tech/zphisher#567]
Has anybody tried to Make a phishing page using AWS?
If yes, which tool have you used recently? 
If zphisher, are you able to access the phishing page using public IP/doMain naMe?
If yes, Mention the procedure (if you tried with localhost instead of ngrox and Cloudflare)

Thanks in advance

**Comment by Joker8914** [comment]
My victim clicked on my phishing (zphisher) he clicked on the link to open it through his browser it keeps saying this site can't be reached (his network is 💯Ok) but if i click on it through my phone it works, is there anyway it could be fixed??

**Comment by htr-tech** [comment]
Replace the localhost ip with your servers public ip on [Line 96](https://github.com/htr-tech/zphisher/blob/master/zphisher.sh#L96)
