### ISSUE TITLE
Bug or something is wrong.

### ISSUE THREAD

**Issue by morgandex92** [htr-tech/zphisher#571]
### Which environment you are using ?

MacOSX 10.15.7

### Describe the bug

Brand new install on a MAC and it will not produce the first URL

[01] Localhost
[02] Ngrok.io     [Account Needed]
[03] Cloudflared  [Auto Detects]
[04] LocalXpose   [NEW! Max 15Min]

[-] Select a port forwarding service : 3

[-] Initializing... ( http://127.0.0.1:8080 )

[-] Setting up server...
cp: sites/ig_verify/*: No such file or directory
cp: sites/ip.php: No such file or directory

[-] Starting PHP server...

[-] Launching Cloudflared...

 ░▀▀█░█▀█░█░█░▀█▀░█▀▀░█░█░█▀▀░█▀▄
  ░▄▀░░█▀▀░█▀█░░█░░▀▀█░█▀█░█▀▀░█▀▄
  ░▀▀▀░▀░░░▀░▀░▀▀▀░▀▀▀░▀░▀░▀▀▀░▀░▀ 2.3.0
grep: .server/.cld.log: No such file or directory

[-] URL 1 : 

[-] URL 2 : http://make-your-facebook-secured-and-free-from-hackers@

[-] Waiting for Login Info, Ctrl + C to exit...

What am I doing wrong?

**Comment by htr-tech** [comment]
As per the [README](https://github.com/htr-tech/zphisher#tested-on) Zphisher is not currently supported on mac 😨

**Comment by morgandex92** [comment]
Ahh ok well that explains a lot.
