### ISSUE TITLE
[Broken Page]: localXpose

### ISSUE THREAD

**Issue by Ahmed9742** [htr-tech/zphisher#572]
### Which Page is broken ?

when i try to run it says
 failed Error occured while downloading loclx.
im running on kali first time it worked fine but now i got this

**Comment by htr-tech** [comment]
make sure you have active internet connection & try running using sudo

or manually download for your device architecture from [LocalXpose website](https://localxpose.io/#download) & replace the binary inside `zphisher/.server` directory
