### ISSUE TITLE
The link doesn't work on another phone

### ISSUE THREAD

**Issue by BotKi11eR** [htr-tech/zphisher#573]
### Which environment you are using ?

Termux / Android

### Describe the bug

The generated link only opens when you use it on the same device. If you use it on another device it doesn't open .. So how is this a phishing tool when it cant be use on other devices? Or m I doing something wrong . Kindly guide..

**Comment by htr-tech** [comment]
use any of the portforwarding options. (ngrok/cloudflared/localxpose)

not localhost

**Comment by BotKi11eR** [comment]
Thank you for your answer.. 
I have tried all 3  you mentioned .. 

For LocalXpose : 
It doesn't give complete URLs to share (both Url1-Url2) ..
 
CloudFlare: 
Site cannot be reached when open link , not even giving Victim's IP .. 

Ngrok : 
gives Victim IP.. 

Change ngrok server region (Dont know about this )  tried both (y/n) vut same output .. 

ERR_NGROK_6022 
Signup for a free Account .. 

 Kindly guide if there's a mistake from my side..

**Comment by htr-tech** [comment]
Run zphisher on localhost & in a new tab navigate to zphisher directory & type the following command
`termux-chroot ./.server/loclx tunnel http -t "127.0.0.1":"8080" --https-redirect`

& Can you see if the link appears or not

**Comment by BotKi11eR** [comment]
I'll try but, Is it  command need root?? I am using without root

**Comment by htr-tech** [comment]
no it doesn't

**Comment by BotKi11eR** [comment]
Bro I read somewhere before thst chroot commands are only used by rooted termux . So I am confused

**Comment by htr-tech** [comment]
ughhhh... chroot is [proot](https://wiki.termux.com/wiki/PRoot) ..

**Comment by BotKi11eR** [comment]
> Run zphisher on localhost & in a new tab navigate to zphisher directory & type the following command
> `termux-chroot ./.server/loclx tunnel http -t 127.0.0.1:8080 --https-redirect`
> 
> & Can you see if the link appears or not



~/zphisher $ termux-chroot ./.server/loclx tunnel http -t 127.0.0.1:8080 --https-redirect
New update is available (22.8.2), please update to the latest version by calling `loclx update`
Error: unauthenticated access

**Comment by htr-tech** [comment]
> the

can you reclone zphisher & try the same thing again

**Comment by htr-tech** [comment]
localxpose now needs an account..w8 for sometimes i'll update it soon

**Comment by BotKi11eR** [comment]
Alright, just to be clear  you told me to run zphisher on Localhost (Not LocalXpose) and use that command in a new tab right?

**Comment by htr-tech** [comment]
I think that is not required anymore.. Update zphisher to latest version 

Create an account on [LocalXPose](https://localxpose.io/) & copy the authtoken 
![image](https://user-images.githubusercontent.com/56682134/183411705-009ec89c-d299-44e1-aec0-a99c59ef4c7d.png)

Run zphisher & Select option 4. then paste the auth token , it should work i guess
![1](https://user-images.githubusercontent.com/56682134/183411781-0fdb50b0-04c0-440e-ae90-0fc5fc1a8c33.jpg)

![2](https://user-images.githubusercontent.com/56682134/183411875-fd1ece5c-8edc-4cfc-ac60-ddddfdf0ae10.jpg)

**Comment by htr-tech** [comment]
type `git pull origin` in the zphisher directory..or reclone 

> That was Fast

14400 seconds is a huge time lol

**Comment by BotKi11eR** [comment]
I Installed it again and now the first link working on other devices, but 2nd still not .. But its good and I appreciate your dedication to your work , Honestly I thought ok now its gonna take months for the update lol but you did it overnight 🔥 .. Thanks for your hardwork ,wish you All the best for your future :) 
Btw Sorry for too many Q's in the start 😁❤

**Comment by htr-tech** [comment]
2nd is just a mask link..both are same 🦅  you can close the issue if your problem is solved 🦅

**Comment by BotKi11eR** [comment]
Mask link? 2nd link shows this or (444 Tunnel Not Found) 

![Screenshot_20220809-023656_DuckDuckGo.jpg](https://user-images.githubusercontent.com/106982345/183639026-cf979858-5067-4ec2-aa00-21b400374d35.jpg)

**Comment by htr-tech** [comment]
ugh you have to copy the entire link.. 

> Mask link? 2nd link shows this or (444 Tunnel Not Found)
> 
Carefully look at the link ,, its the same link after the @

Link 1 : `http://**some_extremely_sus_link**`
Link 2 : `http://get-unlimited-followers-for-instagram@`**some_extremely_sus_link**

You can just use the first link.. if you can't get it iguess 🐔

**Comment by BotKi11eR** [comment]
I see .. but usually its only till that part "@" and nothing further .. but Yeah the 1st one working thats enough .. btw whats the meaning of (Max 15 mins)??

**Comment by htr-tech** [comment]
> I see .. but usually its only till that part "@" and nothing further .. but Yeah the 1st one working thats enough .. btw whats the meaning of (Max 15 mins)??

According to localxpose website the link won't be valid after 15 minutes for free plan

**Comment by BotKi11eR** [comment]
Alright man Thanks for your support, Appreciate it ❤
