### ISSUE TITLE
Zphisher

### ISSUE THREAD

**Issue by Alex2Bav** [htr-tech/zphisher#58]
What is the problem? How can I fix this?
![Screenshot_20200816_222741](https://user-images.githubusercontent.com/69767648/90342297-bab86780-e00f-11ea-8759-bfda02c58232.jpg)

**Comment by Abhsi** [comment]
> What is the problem? How can I fix this?
> ![Screenshot_20200816_222741](https://user-images.githubusercontent.com/69767648/90342297-bab86780-e00f-11ea-8759-bfda02c58232.jpg)

It is problem of localhost it should be 8080 port see it in youtube

**Comment by Abhsi** [comment]
Yes it is solved now 8080 port

**Comment by htr-tech** [comment]
Set up Port to 5555 por something .. dont use 80 or 8080

**Comment by Alex2Bav** [comment]
Now this problem
![Screenshot_20200817_145146](https://user-images.githubusercontent.com/69767648/90393381-4aeebf00-e099-11ea-9e4b-845577ba5b01.jpg)

**Comment by htr-tech** [comment]
have you closed The termux App ?? You have to Keep Termux Session Alive until  Your Job is Done

**Comment by htr-tech** [comment]
@Alex2Bav or use in Browser Link - https://bit.ly/2PHq7ft
