### ISSUE TITLE
Not lasting

### ISSUE THREAD

**Issue by MU1147-LEGEND** [htr-tech/zphisher#591]
### Which environment you are using ?

Linux / Desktop

### Describe the bug

When I create a phishing link and visit one time, then the site is listed in the suspicious link, ngrok and localxpose alerted my target that I'm phishing, the cloud is working but only one time. please fix this or bring a new method that lasts at least 24 hours or more.

**Comment by htr-tech** [comment]
Check the plans on each tunnelling websites..these are for temporary links.

if you want static then upload the files to web hosting..
