### ISSUE TITLE
LocalXpose not working again..

### ISSUE THREAD

**Issue by BotKi11eR** [htr-tech/zphisher#593]
### Which environment you are using ?

Termux / Android

### Describe the bug

![Screenshot_20220828-154601_Termux](https://user-images.githubusercontent.com/106982345/187074808-d2e15e61-84d2-4cba-871d-fb1152ff93fd.jpg)

 .. 
The links are not generating properly..

**Comment by HuzaifaKhanDeveloper** [comment]
Yes Its Not Work

**Comment by FIFTYrupees** [comment]
I have the same problem

**Comment by GH05T-HUNTER5** [comment]
> ### Which environment you are using ?
> Termux / Android
> 
> ### Describe the bug
> ![Screenshot_20220828-154601_Termux](https://user-images.githubusercontent.com/106982345/187074808-d2e15e61-84d2-4cba-871d-fb1152ff93fd.jpg)
> 
> .. The links are not generating properly..
> 
> ### Provide log output [Optional]
> _No response_

Follow this steps
1) install ngrok
2) Copy & paste Your Ngrok Token 
Then
Try again

**Comment by BotKi11eR** [comment]
Ngrok doesn't work anymore I guess? Or it works with mobile data .  Not sure .. but the Tool creator told me to use LocalXpose and it was working fine for a week .. but now its not creating complete links..

**Comment by GH05T-HUNTER5** [comment]
> 

Ok

**Comment by GH05T-HUNTER5** [comment]
> Ngrok doesn't work anymore I guess? Or it works with mobile data . Not sure .. but the Tool creator told me to use LocalXpose and it was working fine for a week .. but now its not creating complete links..


LocalXpose { error solution }
1) login https://localxpose.io/
2) copy your toten 
3) and run zphisher 
4) When zphisher asks for your token, enter it there

**Comment by mayankgamit** [comment]
![Screenshot_20221010_213104](https://user-images.githubusercontent.com/113980021/194908144-e3f2e07d-9667-45c0-bc4b-31614508dc25.jpg)

It's not create properly link

**Comment by htr-tech** [comment]
> ![Screenshot_20221010_213104](https://user-images.githubusercontent.com/113980021/194908144-e3f2e07d-9667-45c0-bc4b-31614508dc25.jpg)
> 
> It's not create properly link

Run after turning on device hotspot
