### ISSUE TITLE
Fake

### ISSUE THREAD

**Issue by S800-commits** [htr-tech/zphisher#61]
Its not working tool bcz when i did all the given things then open the link n then it shows localhost 5555 error
Plz help

**Comment by htr-tech** [comment]
@S800-commits if You re Root then try using sudo

**Comment by S800-commits** [comment]
My mobile is non rooted so i think that's why the commands didn't work by
the way plz make commands for non rooted devices . Thank you..

**Comment by htr-tech** [comment]
@S800-commits This tool works on Non Rooted Devices
Turn on hotspot & try again

**Comment by S800-commits** [comment]
Bro this is not my problem actually link generate successfully but after
that when i send the link to victim and then victim open the link then it
shows failed to connect tunnel and link doesn't open. This is my problem so
plz help..

**Comment by htr-tech** [comment]
you have to keep your termux/terminal session alive until your job is done 😄
