### ISSUE TITLE
git clone --depth=1 https://github.com/htr-tech/zphisher.git

### ISSUE THREAD

**Issue by AGROTEKRICE** [htr-tech/zphisher#611]
### Is your proposal related to a problem?

git clone --depth=1 https://github.com/htr-tech/zphisher.git

### Describe the solution you'd like

git clone --depth=1 https://github.com/htr-tech/zphisher.git

### Additional context

git clone --depth=1 https://github.com/htr-tech/zphisher.git

**Comment by htr-tech** [comment]
??
