### ISSUE TITLE
ngrok error

### ISSUE THREAD

**Issue by NishikataK** [htr-tech/zphisher#612]
### Describe the bug

ngrok doesnt work after the y/n input
environment - macos 

### Provide log output [Optional]

```shell
[-] Setting up server...

[-] Starting PHP server...

[-] Change Ngrok Server Region? [y/N]: yzphisher.sh: line 414: ${opinion,,}: bad substitution
```

**Comment by Judeaspa** [comment]
Y

**Comment by htr-tech** [comment]
Zphisher is currently supported on [linux distributions](https://github.com/htr-tech/zphisher#tested-on).

You can still use it on VM or on Termux (Android)
