### ISSUE TITLE
Site show error

### ISSUE THREAD

**Issue by AnsDark** [htr-tech/zphisher#622]
### Which environment you are using ?

Termux / Android

### Describe the bug

While we send link to victim, when victim clicks the link it show error..

**Comment by htr-tech** [comment]
What kind of error ? Provide any info or screenshot

**Comment by Sanskar-Chaudhary** [comment]
i am using ngrok method and it always says error ngrok 6022 , I have signed up on ngrok but dont know what I am doing wrong , It also says install auth token , don't know what to do please help
![image](https://user-images.githubusercontent.com/110403931/197269576-7fb2d594-a707-4b23-9469-ecc95485a124.png)

**Comment by htr-tech** [comment]
> i am using ngrok method and it always says error ngrok 6022 , I have signed up on ngrok but dont know what I am doing wrong , It also says install auth token , don't know what to do please help

- Copy the authtoken from ngrok's website
- In zphisher directory type
 `./.server/ngrok authtoken <paste your token>`
- Then you should be okay

**Comment by Sanskar-Chaudhary** [comment]
so yeah it worked this time but still website won't open lemme share screenshots steps wise , 
I chose traditional instagram login page + ngrok server and did N to custom region , custom mask , custom port , 
![image](https://user-images.githubusercontent.com/110403931/197359498-f494f05c-3710-40dc-990f-cc16052c6cd0.png)


then I tried visiting the first green link, first it showed this 
![image](https://user-images.githubusercontent.com/110403931/197359548-47905489-4de0-4b48-bc98-9428203403d9.png)


but  then when I clicked on visit link (blue button) , its showing this page isn't working
![image](https://user-images.githubusercontent.com/110403931/197359584-70ae7701-fecc-425f-b986-b663e8f8ba1e.png)

please help

**Comment by htr-tech** [comment]
> but then when I clicked on visit link (blue button) , its showing this page isn't working
I think that was server releated or your internet/firewall issue.. (cause zphisher picked up the backup url shortner in your case)

You can try another options or check your connection / filrewall (maybe)
![image](https://user-images.githubusercontent.com/56682134/197378734-de8d7e3e-0ecf-42dc-88e6-0aaae7bc0da0.png)

**Comment by Sanskar-Chaudhary** [comment]
![image](https://user-images.githubusercontent.com/110403931/197405740-92e55508-a3ca-47f9-a3e0-f5daa1bfaec2.png)
OK so , everything is fine here now also I can visit instagram page too but before visiting that page chrome gives me a dangerous page warning , and I want to remove that , any help you can do ?? posting ss below
