### ISSUE TITLE
Unable to generate links. Try after turning on hotspot

### ISSUE THREAD

**Issue by aamerF** [htr-tech/zphisher#623]
### Describe the bug

Kindly support 
In Cloudflared... the link not created ..
![Screenshot_20221021-032134_Termux](https://user-images.githubusercontent.com/48980882/197077355-1e2b7f4b-c19b-4187-a550-84c70c361db1.jpg)
![Screenshot_20221021-032121_Termux](https://user-images.githubusercontent.com/48980882/197077423-2702036a-4ab5-4384-b9f6-03cfda2b781c.jpg)

Hotspot already on

**Comment by htr-tech** [comment]
Use option 1 localhost & Host on port 5555 & Open a new tab & type

`termux-chroot ~/zphisher/.server/cloudflared tunnel -url 127.0.0.1:5555 --logfile .server/.cld.log`

& Try the url from there..sometimes the link doesn't appear due to unstable internet connection

**Comment by aamerF** [comment]
Thank u bro.. but same issue.  I think because of my Internet not stable link not created.. what about kali I can use same command.. and what I can do for that issue any solution 
Best regards

**Comment by htr-tech** [comment]
>  what about kali I can use same command..
Just follow the same instructions from the README

> but same issue. I think because of my Internet not stable
![image](https://user-images.githubusercontent.com/56682134/197186622-04da7c5e-0b8a-48a5-a2a5-93636c6faaf1.png)
& termux-chroot doesn't require hotspot ,, so you can try any fast wifi if possible

**Comment by saidehossain699** [comment]
![zphisher](https://user-images.githubusercontent.com/116615019/197672508-7ec7954b-1a84-4471-abe6-bdfc7bba0450.png)
what is the solution in kali linux

**Comment by Kazernut** [comment]
did u find the solution for kali?

**Comment by saidehossain699** [comment]
yes

[Saide Hossain - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=1wpdi5)	[1wpdi5]

On January 19, 2023 at 7:05 GMT, Kazernut ***@***.***> wrote:

did u find the solution for kali?

**Comment by brako97** [comment]
Cuál es la solución para Kali ?
