### ISSUE TITLE
Operation not permitted

### ISSUE THREAD

**Issue by irememberpain** [htr-tech/zphisher#626]
### Describe the bug

<img width="754" alt="Screenshot 2022-10-24 130517" src="https://user-images.githubusercontent.com/115160898/197521709-69be2aea-fea5-40df-8cd3-31f003ae3a00.png">

**Comment by htr-tech** [comment]
![image](https://user-images.githubusercontent.com/56682134/197674683-d9eade91-f97d-4a95-9e5a-cc82238207b4.png)
Solution is in the error msg

Type `export PROOT_NO_SECCOMP=1` each time running
or add it to the `~/.bashrc`
