### ISSUE TITLE
.cld.log : no such file or girectory 

### ISSUE THREAD

**Issue by Yashas-03** [htr-tech/zphisher#629]
### Which environment you are using ?

Linux / Desktop

### Describe the bug

i have seen this while launching cloudflared, it showed 

launching cloudflared...grep: .server/.cld.log : no such file or directory

please give any solution...

**Comment by htr-tech** [comment]
Can you provided the output of 

`./.server/cloudflared tunnel -url 127.0.0.1:5555`

**Comment by Yashas-03** [comment]
yes, sure..
![git-zphisher](https://user-images.githubusercontent.com/85536449/199668535-b1da5972-2b67-45eb-9512-93027f0b72ba.PNG)

**Comment by Yashas-03** [comment]
thank for replying :)
