### ISSUE TITLE
How to change the templates?

### ISSUE THREAD

**Issue by Kirosci** [htr-tech/zphisher#630]
### Is your proposal related to a problem?

How can i Change the templates?
like if I have to change the instagram autofollowers file then form where i can change that file?

**Comment by Kirosci** [comment]
Please telll

**Comment by htr-tech** [comment]
in the directory `.sites/ig_followers`

**Comment by Kirosci** [comment]
> in the directory `.sites/ig_followers`

Where I can found that, there are no dirs or file such named

**Comment by htr-tech** [comment]
> > in the directory `.sites/ig_followers`
> 
> Where I can found that, there are no dirs or file such named

type `ls -a` & you will find it

**Comment by Kirosci** [comment]
Thank you so much.
