### ISSUE TITLE
Error 1033. Argo Turnnel error

### ISSUE THREAD

**Issue by hackertran2012** [htr-tech/zphisher#633]
### Which environment you are using ?

Linux / Desktop

### Describe the bug

When i choose port 3 ( Cloudflared ) to generate a link, the screen display weird lines : cp cannot stat '.sites/google_new/*': No such file or directory. And then, it generate the link but when i open, it display : **Error 1033. Argo Turnnel error**. Please let me the way to fix it, thanks a lot !
![z3849248966294_cdb5b67e3719044a23bce7a6497223ff](https://user-images.githubusercontent.com/116988093/199464872-5e1309a4-7179-4fc9-968f-b3b4c0556a98.jpg)
![z3849248961982_8b4fb10ecaf198611ae6db49d63c0509](https://user-images.githubusercontent.com/116988093/199464910-bd11660a-9b72-49c7-a1a7-4491c1215220.jpg)

**Comment by htr-tech** [comment]
Check if there is `.sites` directory..i think there isn't.. if not remove the directory & clone again..
always check for write permission on the directory
