### ISSUE TITLE
Ngrok download error

### ISSUE THREAD

**Issue by kephra-sys** [htr-tech/zphisher#635]
The application fails on first run with the following error:

[+] Installing ngrok...
curl: option --retry-connrefused: is unknown
curl: try 'curl --help' or 'curl --manual' for more information

[!] Error occured while downloading ngrok.

**Comment by htr-tech** [comment]
maybe you are using a older curl version ? you must have curl newer than `7.52.0`

Or remove `--retry-connrefused` from the following lines

https://github.com/htr-tech/zphisher/blob/f1dcd4618a6cb87cdc2d7b231cb0223e12d88ce0/zphisher.sh#L176

https://github.com/htr-tech/zphisher/blob/f1dcd4618a6cb87cdc2d7b231cb0223e12d88ce0/zphisher.sh#L282

https://github.com/htr-tech/zphisher/blob/f1dcd4618a6cb87cdc2d7b231cb0223e12d88ce0/zphisher.sh#L612
