### ISSUE TITLE
Interstitial Page

### ISSUE THREAD

**Issue by MoistForehed** [htr-tech/zphisher#637]
Both working tunnels, ngrok and localxpose, have interstitial pages that require victim's verification to continue to the phishing link making the tool useless.
![Screenshot 2022-11-06 9 04 07 AM](https://user-images.githubusercontent.com/110633361/200149364-978f20b7-02da-4d40-adb7-ffcc3f2ac113.png)
![Screenshot 2022-11-06 9 02 24 AM](https://user-images.githubusercontent.com/110633361/200149365-0cc764ea-7b3f-4e46-82b6-df5645e3d3be.png)

**Comment by htr-tech** [comment]
well this tool only demonstrates phishing 

if you want "undetectable" pages then simply buy a hosting & upload there

**Comment by Agwarr** [comment]
My package are not successful
How to hack my account are needed please help me
