### ISSUE TITLE
Victim cant open the link

### ISSUE THREAD

**Issue by kaliharry3** [htr-tech/zphisher#640]
### Which environment you are using ?

Termux / Android

### Describe the bug

I did all steps and created link.
Since i use jio network
If the victim also use jio network page open and link work
 Whereas if the victim use other network the link doesnt open at all.

Plz help me to fix ive used cloudflared and localxpose both

![IMG-20221108-WA0003](https://user-images.githubusercontent.com/115978257/200620977-1be158c9-5de8-49fd-8c65-e6c6a75a1cc2.jpg)

**Comment by htr-tech** [comment]
well, that looks like a problem with url shortner... generate links without url shortner ..

localxpose & cloudflared work perfectly on other networks... it can be your internet issue

**Comment by htr-tech** [comment]
![image](https://user-images.githubusercontent.com/56682134/200637224-d1c6982e-7644-4574-9928-460803434c4b.png)
