### ISSUE TITLE
CloudFlare is always detectable. There should be an alternative that is undetectable 

### ISSUE THREAD

**Issue by George152-max** [htr-tech/zphisher#647]
### Describe the bug

Google always detect my links.

### Provide log output [Optional]

```shell
Google always detect my link from CloudFlare, I only use CloudFlare, because it turned out to be d best, after ngrok was messing up, now CloudFlare is down, locaxpose doesn't take you directly to d login page, so we need an alternative to CloudFlare since it no more works please
```

**Comment by htr-tech** [comment]
> Google always detect my link from CloudFlare, I only use CloudFlare, because it turned out to be d best, after ngrok was messing up, now CloudFlare is down, locaxpose doesn't take you directly to d login page, so we need an alternative to CloudFlare since it no more works please

Find another site & make a pr 🙄  or upload the pages to own hosting .. don't expect much from these temporary sites

**Comment by Meliodas876** [comment]
Si hay una herramienta lo leí en security developer for android

**Comment by George152-max** [comment]
@Meliodas876 what do u mean bruh

**Comment by Isaacderiv** [comment]
i have a premium account on local expose  but i still get that warning page, please can you walk me through resolving it?

**Comment by htr-tech** [comment]
Google marks frequently used phishing sites as red.
You can bypass it with a new domain
