### ISSUE TITLE
ngrok error 3208

### ISSUE THREAD

**Issue by annonymous12343** [htr-tech/zphisher#652]
### Which environment you are using ?

Termux / Android

### Describe the bug

The link is generating normally but when I'm trying to open the link it gives me an error. I don't have the acc banned.

### Provide log output [Optional]

```shell
ERR_NGROK_3208
The account associated with this hostname has been banned. We've determined this account to be in violation of ngrok's terms of service. If you are the account owner and believe this is a mistake, please contact support@ngrok.com.
```

**Comment by htr-tech** [comment]
#695
