### ISSUE TITLE
Ngrok warning page

### ISSUE THREAD

**Issue by bigharold123** [htr-tech/zphisher#656]
Anyone know how to get rid of the ngrok warning page?

**Comment by bigharold123** [comment]
Or know where to put this code: ngrok-skip-browser-warning?

**Comment by marik22354** [comment]
They started using much security becouse the ngrok app is being abused for phishing, you have to build your own phishing tool, I've already did that https://github.com/marik22354/Facebook-Sender_V2

**Comment by Rdmo2** [comment]
> Anyone know how to get rid of the ngrok warning page?

ngrok premium, use cloudflared it only gives warning if the program is bad, haven't tested it with this one

**Comment by coddiezypher** [comment]
did you got it???
