### ISSUE TITLE
zphisher.sh: line 158: pidof: command not found

### ISSUE THREAD

**Issue by Kriismaa** [htr-tech/zphisher#660]
### Which environment you are using ?

Windows (lol)

### Describe the bug

when i type: "bash zphisher.sh" it gives me this response
 $ bash zphisher.sh
zphisher.sh: line 158: pidof: command not found
zphisher.sh: line 158: pidof: command not found
zphisher.sh: line 158: pidof: command not found
zphisher.sh: line 158: pidof: command not found

[+] Installing required packages...

[+] Installing package : php

[!] Unsupported package manager, Install packages manually.

i tried reinstalling the zphisher file and it still didnt work 

im using git bash 
![git bash error zphisher](https://user-images.githubusercontent.com/121501930/210112689-c59503cb-81d3-4884-a836-1a9167d0fda8.png)

**Comment by htr-tech** [comment]
Zphisher is not supported on [Windows](https://github.com/htr-tech/zphisher#tested-on)

You have to use any linux distributions for using zphisher
