### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by Depxii** [htr-tech/zphisher#664]
When loading in cloud shell, and running docker run --rm -ti htrtech/zphisher it does the update and says updated successfully run zphisher again, what do i put because obviously im doing something wrong because it just tries to update again and says the same thing again and stays at 2.3.4

**Comment by htr-tech** [comment]
First Check the image id by typing `docker images -a`
Then remove it using `docker rmi <image id>`
Then run again.. It should pull the latest one

Or simply pull the latest version using `docker pull`
