### ISSUE TITLE
Warning page

### ISSUE THREAD

**Issue by chamod12** [htr-tech/zphisher#665]
How to fix it

**Comment by htr-tech** [comment]
Copy the pages & upload to web hosting..no solutions for free temporary tunnelling sites., Or update to their premium plans

**Comment by khun-int** [comment]
> Copy the pages & upload to web hosting..no solutions for free temporary tunnelling sites., Or update to their premium plans

Wdym by copy the pages? do we just take the link and upload to web hosting?

**Comment by khun-int** [comment]
or is it localhost and then webhost?

**Comment by htr-tech** [comment]
> Wdym by copy the pages? do we just take the link and upload to web hosting?

@khun-int pages refers to the phishing pages that are stored in the [`.sites`](https://github.com/htr-tech/zphisher/tree/master/.sites) directory

**Comment by Isaacderiv** [comment]
how do you upload them?

**Comment by htr-tech** [comment]
you have to purchase a paid hosting or use a free one

then you will find upload option there
