### ISSUE TITLE
Using LocalHost Option

### ISSUE THREAD

**Issue by Rackersd8** [htr-tech/zphisher#666]
I was wondering if you could tell me how to utilize the localhost option as the cloudflare option links arent able to get through my microsoft tenant for internal testing. I have an ubuntu web server and was wondering if I would have to somehow use the localhost option on said server? I apologize for my incompetence in advance, (still learning web-servers).

**Comment by htr-tech** [comment]
You can start php server with your servers ip address..

You can replace your servers ip on [Line 96](https://github.com/htr-tech/zphisher/blob/master/zphisher.sh#L96)

**Comment by htr-tech** [comment]
welcome.. 
is your problem solved ? then please close the issue
