### ISSUE TITLE
Phishing link doesn't working at Target device. 

### ISSUE THREAD

**Issue by Leaglizelegend** [htr-tech/zphisher#668]
**#htr-tech**
Please solve the issue given below :-
        I am using the termux application installed by (F-droid app store) and I tried so many times to grab the target credentials by using zphisher package  but I can't .
       I have read the blog (https://github.com/htr-tech/zphisher/issues/573#issuecomment-1207336959) and also tries this method using the command on another tab (termux-chroot ./.server/loclx tunnel http -t 127.0.0.1:8080 --https-redirect) but I can't.

         Please solve my issue a humble request. 🙏🙏🙏🙏

**Comment by Kari100blanco100** [comment]
Urgente

**Comment by Kari100blanco100** [comment]
Mercado pago

**Comment by htr-tech** [comment]
your link not appearing or what ?
post the screenshots off your process

@Leaglizelegend

**Comment by Leaglizelegend** [comment]
![IMG_20230111_144103](https://user-images.githubusercontent.com/116716493/211765389-a8891b3a-dc4d-4f2c-a87f-9de242fa502a.jpg)


On 1st tab of termux without root the link is generated and shared towards target system and on 2nd tab, following command is used 
       { termux-chroot ./.server/loclx tunnel http -t 127.0.0.1:8080 --https-redirect }
             Please solve the above problem

**Comment by htr-tech** [comment]
use the link generated by localxpose ..not localhost

**Comment by Leaglizelegend** [comment]
Again same page occured on the target screen.
         I think my way of generating link is wrong or I am making some mistake, please a humble request to @htr-tech the given below is my WhatsApp number send me "hi" I will share a video of my complete process.
+91-9766660490. 

           Humble request to htr-tech.

**Comment by Leaglizelegend** [comment]
Big bro @htr-tech please help us to solve the above issue....

**Comment by htr-tech** [comment]
use any other port forwarding options except localhost..It works fine
