### ISSUE TITLE
Unable to generate links. Try after turning on hotspot. Termux

### ISSUE THREAD

**Issue by dexsystem** [htr-tech/zphisher#670]
![Screenshot_2023-01-14-16-56-27-907_com termux](https://user-images.githubusercontent.com/104092253/212478171-d5eef80e-c48f-4be1-8a71-a58d8c9c6c4a.jpg)

**Comment by htr-tech** [comment]
Host on LocalHost on the first tab & in the new tab run the exact command with the port number from localhost

![image](https://user-images.githubusercontent.com/56682134/212482500-88182fec-9f43-4460-90ed-6d4fe7e16128.png)

Then you can easily use the link
