### ISSUE TITLE
Ngrok warning page

### ISSUE THREAD

**Issue by khun-int** [htr-tech/zphisher#675]
### Which environment you are using ?

Linux / Desktop

### Describe the bug

Is there any way to submit the ngrok-skip-browser-warning requester header or how do you host the website on a webhost?

**Comment by htr-tech** [comment]
ngrok premium plan will solve your first issue

& hosting own website is not a big deal.. Thounsands of tutorial are on google & youtube.. You can get the phishing pages from `.sites` directory
