### ISSUE TITLE
Not possible to install through .deb package.

### ISSUE THREAD

**Issue by AwfulNewb** [htr-tech/zphisher#677]
### Which environment you are using ?

Linux / Desktop

### Describe the bug

![error](https://user-images.githubusercontent.com/109723888/213970421-dc021eb0-596b-403c-a5bc-d5c0239054ed.png)
I'm using the lastest version of Kali. I was able to install it with the script, but I still prefer to use .deb.

**Comment by htr-tech** [comment]
I have updated them.. now try installing again

**Comment by Trojanrever** [comment]
Let them know that before going to install the package first clear all the cache and try to put their terminal in update and upgrade so that the package can run smoothly without any interruption
