### ISSUE TITLE
Browsers have recognized phishing web 

### ISSUE THREAD

**Issue by nguyenvanmanh289** [htr-tech/zphisher#686]
Browsers and even link editing tools will warn you that this is a phishing link, the user will most likely not continue to take any further steps to reach the destination page, resulting in failure. 

![Screenshot_20230129-224847_Messenger](https://user-images.githubusercontent.com/88959809/215338851-491f19c7-f7cd-4bc7-a9db-0d3750acb3e2.png)

and more

**Comment by htr-tech** [comment]
its expected with free port forwarding options.. You can bypass that by copying the pages & uploading it to a vps or webserver..

In that way you can get static urls & can bypass the blocking (most of the time)
