### ISSUE TITLE
j

### ISSUE THREAD

**Issue by hosseintaram** [htr-tech/zphisher#69]

**Comment by htr-tech** [comment]
????????

**Comment by vickyke123** [comment]
!!??

**Comment by htr-tech** [comment]
@hosseintaram @vickyke123 what happened ??

**Comment by MorganDavid4** [comment]
Hello, i need to learn how to hack Facebook, Netflix, Instagram and PayPal

**Comment by htr-tech** [comment]
@MorganDavid4 these are just phishing. tools

**Comment by siddharth27288** [comment]
How to hack Instagram & Facebook
