### ISSUE TITLE
Masked url shows kali default webpage instead of login page

### ISSUE THREAD

**Issue by KimDelien** [htr-tech/zphisher#691]
### Which environment you are using ?

Linux / Desktop

### Describe the bug

Hey
First of all, thanks for making this tool! It's a nice and easy to use tool.
I have a local kali vm with zphiser installed and using cloudflared. But every time I want to mask my url, this masked url redirects me to kali's homepage. I don't know what the problem here is?
Not sure if it's a bug or something wrong with my machine?
![image](https://user-images.githubusercontent.com/35693680/215996545-56007050-20ff-4751-8399-f6a11d3c123e.png)

The other link (url 1) works fine and gives me the result expected (victim ip, username, password,...)

I'm using everything locally, these websites won't leave my machine. It's for an security awareness training to show how easy it is to make phishing mails.

Could you help me with my issue?

Thanks in advance and all the best

**Comment by Thind66** [comment]
```
Lol
```

**Comment by htr-tech** [comment]
The url 2 & 3 is the shortened version of url1 ... its not appearing because of your firewall / internet connection maybe... 

you can still use url 1
