### ISSUE TITLE
zphisher caused ngrok hostname has been banned

### ISSUE THREAD

**Issue by soceng** [htr-tech/zphisher#695]
Hello 
when i selected the ngrok as tunling on zphisher  and open the generated link , an error messages shown as below :
hostname has been banned , ERR_NGROK 3208 . and my ngrok account  has been  stoped due to the violation .
kindly help me .

**Comment by htr-tech** [comment]
Ngrok Has Banned your account. Create a new one & remove the `~/.ngrok` directory

**Comment by soceng** [comment]
i have craeted 2 accounts and also banned , why this occur when i use zphisher ?

**Comment by soceng** [comment]
> Ngrok Has Banned your account. Create a new one & remove the `~/.ngrok` directory

i  craeted 2 accounts and also banned , why this occur when i use zphisher ? what is the wrong ? should i do somthing to avoid this issue ?
