### ISSUE TITLE
ngork and serveo options won't work.

### ISSUE THREAD

**Issue by tinshade** [htr-tech/zphisher#7]
The port forwarding options for NGROK and Serveo just don't seem to work for me. Please guide me in case I am missing any pre-requisites or just doing something wrong entirely.

The initializing never ends and with Serveo, no link is created..
![zer](https://user-images.githubusercontent.com/22311804/78754621-6e8c5500-7995-11ea-81b2-bcfcab5ff6cf.jpg)

**Comment by htr-tech** [comment]
@tinshade Bro Serveo is Currently Down & Ngrok is Working .
 If your ngrok is not working then type `uname -m` & find your device architecture 
& download the ngrok & replace it to zphishers dir .
![image](https://user-images.githubusercontent.com/56682134/78883831-d7e69380-7a7b-11ea-95db-39e6b3923d89.png)

**Comment by tinshade** [comment]
Actually the ngrok zip file was corrupt for me. I replaced that one with my own and it started working fine. Thanks for the quick responses. @htr-tech
