### ISSUE TITLE
won automatically install packages

### ISSUE THREAD

**Issue by Nfglotus666** [htr-tech/zphisher#708]
### Which environment you are using ?

Windows (lol)

### Describe the bug

im using git bash and wont automaticallly install the packages 

### Provide log output [Optional]

```shell
Unsupported package manager, Install packages manually.
```

**Comment by Oxtehteh** [comment]
its exactly what you said, i need php 

[+] Installing required packages...

[+] Installing package : php

[!] Unsupported package manager, Install packages manually.

**Comment by htr-tech** [comment]
Zphisher won't run on windows git bash..cause it requires some packages like php & binaries https://github.com/htr-tech/zphisher#tested-on

You have to use wsl (sub system for linux) or any other linux distributions or termux on android

**Comment by Oxtehteh** [comment]
okay thank you, im in amd and i disable the virtual system in the bios so i cant do a virtual box linux but i know the solution now i will look into the subject later thanks

**Comment by Nfglotus666** [comment]
ok
