### ISSUE TITLE
firefox refresh phishing page with google 

### ISSUE THREAD

**Issue by mouchezebi** [htr-tech/zphisher#71]
Hello when I launch phishing with google new and I test on firefox the page refreshes indefinitely, does anyone have a solution?
thank you

sorry for mi bad english :)

**Comment by htr-tech** [comment]
@mouchezebi  try disabling some extensions like popup blocker , cookie grabber etc

**Comment by mouchezebi** [comment]
ok thank you it's okay i will have another question?

I have a premium plan with ngrok, how can I add my url to zphisher?
I saw that it was in tunneling options but can you put the exact command if possible?
thanks
ps your tools are very good;)
nice joob

**Comment by mouchezebi** [comment]
?

**Comment by htr-tech** [comment]
@mouchezebi contact my ig

@tahmid.rayat

**Comment by anikey78** [comment]
> @mouchezebi try disabling some extensions like popup blocker , cookie grabber etc

Okk can you help

**Comment by anikey78** [comment]
> ok thank you it's okay i will have another question?
> 
> I have a premium plan with ngrok, how can I add my url to zphisher?
> I saw that it was in tunneling options but can you put the exact command if possible?
> thanks
> ps your tools are very good;)
> nice joob

Ok will give you the issue
