### ISSUE TITLE
Please remove ngrok as a tunneling option as this tool violates their terms of service

### ISSUE THREAD

**Issue by russorat** [htr-tech/zphisher#722]
### Is your proposal related to a problem?

PM for ngrok here. This tool directly violates the ngrok Terms of Service even when used for educational purposes only. We kindly request that ngrok be removed as an option in your tool.

To learn more about how ngrok combats abuse, see https://ngrok.com/abuse and https://ngrok.com/tos .

ngrok is not anonymous and cannot be used to hide your identity. ngrok directly exposes your public IP address to anyone who sees the ngrok url you send them via the url and an http header. 

ngrok will also ban your account instantly if you use this tool.

ngrok adds an interstitial page to all requests warning anyone viewing the page that the site is hosted by ngrok.

### Describe the solution you'd like

Please remove ngrok as a tunneling option.

### Additional context

There are many related issues. Basically any issue about a tunnel not found is related to a banned account:

https://github.com/htr-tech/zphisher/issues/712
https://github.com/htr-tech/zphisher/issues/656
https://github.com/htr-tech/zphisher/issues/303
https://github.com/htr-tech/zphisher/issues/299
https://github.com/htr-tech/zphisher/issues/286

**Comment by htr-tech** [comment]
Understandable..

**Comment by nagjcj1234-rgb** [comment]
Ajgj1234
