### ISSUE TITLE
Bad substitution

### ISSUE THREAD

**Issue by pr0t1gy** [htr-tech/zphisher#728]
### Which environment you are using ?

Linux / Desktop

### Describe the bug

Thanks for making this btw, it looks great. Haven't been able to use it thought, except on localhost ( So myself)
I have no Ngrok Option but I read that's another issue
CloudFlare and LocalXpose do not work for me and I don't understand why. Would love to finally use this, thanks

https://user-images.githubusercontent.com/128764363/227737829-0c154842-e9c9-4d8a-aa15-5a0b8e55e7dd.png

https://user-images.githubusercontent.com/128764363/227737891-ba7aee88-186a-4c30-9910-6f885ce983aa.png

**Comment by htr-tech** [comment]
![image](https://user-images.githubusercontent.com/56682134/227761173-bc1012bf-2d62-46f4-a270-e6a786cf0616.png)
what's the output of `uname -a`

Zphisher won't run except https://github.com/htr-tech/zphisher#tested-on

Also you can use localhost and manually forward using localhostrun or portmap

**Comment by pr0t1gy** [comment]
Thanks for responding

This is the output of `uname -a`
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/128764363/227983598-61329203-1fec-44f3-a661-24f0e3a77edc.png">

**Comment by htr-tech** [comment]
Zphisher is not Supported on Mac.

You can use it via any linux distributions
