### ISSUE TITLE
Fine

### ISSUE THREAD

**Issue by exotic-inx** [htr-tech/zphisher#744]
### 8k

**Comment by h4x3r1** [comment]
![Screenshot_20230424_104006_Chrome](https://user-images.githubusercontent.com/92029487/233901884-0c226504-bbaf-4222-aa28-0d4a42c173dd.jpg)
![Screenshot_20230424_104015_Chrome](https://user-images.githubusercontent.com/92029487/233901905-b18b52fc-80b0-49c2-809e-94541dade24b.jpg)
