### ISSUE TITLE
VIRUS! NOT FAKE!

### ISSUE THREAD

**Issue by ki-88-git** [htr-tech/zphisher#767]
### Which environment you are using ?

None

### Describe the bug

file: C:\linuxHACprogram\zphisher\zphisher\.sites\facebook\login.html  A virus was found there  Trojan:Script/Wacatac.B!ml
screenshot:
![Снимок экрана 2023-06-13 183937](https://github.com/htr-tech/zphisher/assets/128259756/d8b87fc8-b134-4dc8-9706-e09126ee90a0)
This damn Trojan sat for a very long time, only when I logged into Facebook... do you understand
Please do not download if you are already late check your PC and delete the program

**Comment by htr-tech** [comment]
>> The Wacatac. B! ml is classified as a Trojan by Windows Defender because it enters Windows operating systems by tricking users into executing a legitimate-looking file.

What do you expect a phishing template to be ?? Of course antiviruses will detect is malicious program

 & also the file is not encrypted.. so you can check the source code "just using a notepad"

***ITS A DAAMN HTML FILE BRO!!!!*** Atleast google it before submitting a Issue
