### ISSUE TITLE
Editable websites

### ISSUE THREAD

**Issue by PhilipB06** [htr-tech/zphisher#770]
### Describe the solution you'd like

Hello!
Is it possible to edit the HTML sites? I'd like to customize the SnapChat website. My idea would be that if you have entered the credentials and pressed on "Log In", it would redirect you to another phishing site, where you would need to input another passcode, like the 2FA code or my eyes only section. 

In the picture below I've added an example page that I made by editing the HTML code a bit. This is just an idea of how it may look.
![Screenshot_1](https://github.com/htr-tech/zphisher/assets/76661774/ad3a0962-627e-49fb-be7d-78a0042bcbb1)

I'm not requesting for it to be done by you guys, but if it was even possible, and if so, how? I'm new to HTML and general coding so a helping hand would be appreciated.

Other than that, I already thank you for reading this and I love this program.
Have a great rest day!

**Comment by melonenphilip** [comment]
No update....
