### ISSUE TITLE
when i run the tool with bash zphisher.sh it says to install packages manually

### ISSUE THREAD

**Issue by HealZe01** [htr-tech/zphisher#771]
### Which environment you are using ?

Windows (lol)

### Describe the bug
when i run the tool with bash zphisher.sh it says to install packages manually
[](url)
![Capture d’écran 2023-06-20 172741](https://github.com/htr-tech/zphisher/assets/137196271/1ef9de25-7b61-4d49-b8a3-98ab59624c4e)

**Comment by Sweetdevil144** [comment]
Did you provide the adequate permissions?

**Comment by aternator** [comment]
> Did you provide the adequate permissions?

Sorry if this is a bit late, I also have the same issue and I'm not sure what you mean by the adequate perms. I have given Git Bash admin rights and it still refuses to work.

**Comment by Sweetdevil144** [comment]
Package installed is not supportd by your OS

**Comment by htr-tech** [comment]
https://github.com/htr-tech/zphisher#tested-on

windows not supported
