### ISSUE TITLE
Links not working.

### ISSUE THREAD

**Issue by benthemarauder** [htr-tech/zphisher#79]
The only link that works for me is the LocalHost option and noting else.

**Comment by htr-tech** [comment]
@benthemarauder turn on hotspot & try ngrok option

**Comment by benthemarauder** [comment]
@htr-tech wdym by that

**Comment by htr-tech** [comment]
@benthemarauder  turn on your device hotspot 

then from port forwarding options select ngrok

**Comment by benthemarauder** [comment]
im on a mac how do i do that

**Comment by htr-tech** [comment]
@benthemarauder  try from this link : 
https://repl.it/repls/GaseousFormalAttributes

**Comment by TangweMarino** [comment]
#79
