### ISSUE TITLE
@userundefine try again with the commands from Readme

### ISSUE THREAD

**Issue by lNor7h** [htr-tech/zphisher#791]
@userundefine try again with the commands from Readme

_Originally posted by @htr-tech in https://github.com/htr-tech/zphisher/issues/131#issuecomment-787985659_

**Comment by lNor7h** [comment]
Says Unsupported package manager, Install packages manually
I also tried with the comands from readme over 5 times and its still not working

**Comment by Davoodzx62** [comment]
@userundefine try again with the commands from Readme

**Comment by htr-tech** [comment]
most probably you are using windows system.. you have to use the tested os from the readme..
