### ISSUE TITLE
Generated link does not work on other device/machine.

### ISSUE THREAD

**Issue by max-1020** [htr-tech/zphisher#8]
In the current wifi network, the link created on Kali or Termux only works on the machine where the link was created but clicking the link on other devices always says: "This site can't be reached". Though they are on the same network. However, in the previous wifi network, it worked. what should I do? Has it something to do with router setting?

**Comment by jrmessiah** [comment]
U need to go google whats portfwarding according to your router brand....then portforward ur router allowing it to become to connect to ur lan ip..

just google it

**Comment by max-1020** [comment]
> @max-1020 U need to go google whats portfwarding according to your router brand....then portforward ur router allowing access to the port u used. for it to connect to ur lan ip..
> 
> just google it
> 
> > In the current wifi network, the link created on Kali or Termux only works on the machine where the link was created but clicking the link on other devices always says: "This site can't be reached". Though they are on the same network. However, in the previous wifi network, it worked. what should I do? Has it something to do with router setting?

thank you so much.. can it now be used for WLAN?

**Comment by max-1020** [comment]
> @max-1020 U need to go google whats portfwarding according to your router brand....then portforward ur router allowing access to the port u used. for it to connect to ur lan ip..
> 
> just google it
> 
> > In the current wifi network, the link created on Kali or Termux only works on the machine where the link was created but clicking the link on other devices always says: "This site can't be reached". Though they are on the same network. However, in the previous wifi network, it wor

**Comment by waynebutler823** [comment]
I'M SO CONFUSED RIGHT NOW,I CLICK ON THE LINK BUT IT KEEPS DIRECTING ME TO THE SAME PAGE ON MY PHONE, I DON'T KNOW WHAT TO DO OR HOW THIS WORKS IT'S SHOWING ME NOTHING & I'M NOT UNDERSTANDING,CAN YOU PLEASE TEACH ME? I JUST SAW THIS

**Comment by waynebutler823** [comment]
Doesn't this work on phone or what?🤷 I'm so not understanding anything!can anyone pls give me his/her WhatsApp number or any social media Id so explain everything to me pls🙏

**Comment by mroy12a** [comment]
Why can't I get a link to send to my victim

**Comment by jrmessiah** [comment]
> Why can't I get a link to send to my victim

Go to Nrgok website. Sign in and make an account first. 

Next execute the zphisher

**Comment by GucciCondoms** [comment]
Do exactly what jrmessiah said

**Comment by GucciCondoms** [comment]
Do exactly what jrmessiah said

**Comment by laila656** [comment]
Generated Link is not working on other device I have tried everything I'm using termux in android I need help.

**Comment by htr-tech** [comment]
> Generated Link is not working on other device I have tried everything I'm using termux in android I need help.

clone the latest version of zphisher & create nrok link .. then send it to victim

you have to keep your termux open

**Comment by ashiqkl** [comment]
Ngrok - 2nd url not working ...what I should do.. please help

**Comment by ashiqkl** [comment]
![Uploading Screenshot_2021-03-10-21-18-49-035_com.termux.jpg…]()
2nd url not working

**Comment by ashiqkl** [comment]
My problem : Generated Link is not working on other device I have tried everything I'm using termux in android I need help.

You said : clone the latest version of zphisher & create nrok link .. then send it to victim

But ngrok link not working.. please help

**Comment by htr-tech** [comment]
@ashiqkl clone the latest zphisher version

**Comment by L1u2c3a4s5862** [comment]
the first URL not working.
<img width="329" alt="Screenshot 2021-08-22 at 3 57 24 PM" src="https://user-images.githubusercontent.com/54462476/130347085-c51977ba-ff8d-493d-9572-4286fa36eb6c.png">

**Comment by nnnmmnn31** [comment]
Sir my url 1 is not showing I have turned on Hotspot and I use wifi

**Comment by AifazX1** [comment]
> @max-1020 U need to go google whats portfwarding according to your router brand....then portforward ur router allowing access to the port u used. for it to connect to ur lan ip..
> 
> just google it
> 
> > In the current wifi network, the link created on Kali or Termux only works on the machine where the link was created but clicking the link on other devices always says: "This site can't be reached". Though they are on the same network. However, in the previous wifi network, it worked. what should I do? Has it something to do with router setting?

pls will you tell the same thing in an easeir way pls

**Comment by Sabine567uyhgyu7** [comment]
I had use androrat also in android Ubuntu but the apps link i genearated doesn't work on another device only work when i  click that link thank u

**Comment by Eddiep2022** [comment]
> 

Can I do that on termux? Please!

**Comment by Eddiep2022** [comment]
> Do exactly what jrmessiah said

Can I portfoward my router on Termux?

**Comment by Eddiep2022** [comment]
I also have the problem in which the link generated only works on my phone device but not on other devices.
I therefore got the solution which says I should port forward my router which I found difficult to do on Android device, I later got another solution which says I should go for cloudflare link on zphisher, I've already tried it but still didn't work
Please I need a genuine solution

**Comment by Technologygrape** [comment]
Haha

**Comment by Technologygrape** [comment]
I have issue generated link but not working to other device can you you fix zphisher or give a code to fix my problem

**Comment by princepalp** [comment]
My device us weak but kinda ok other's are better,
My device is( itel 16 )
But why does my device has the links specially the cloudflared
Zphisher works perfectly and properly even I am connected to wifi
connection maybe it's I turned my Bluetooth on.
And one more thing maybe the zphisher works when only one person uses it

**Comment by Johnny123sw** [comment]
Ngrok link Is not working in other devices...what to do?

**Comment by Johnny123sw** [comment]
I am using android mobile and termux for physhing......i used ngrok but the link is not working in other devices...and i sent  the link  through watsapp

**Comment by jomon777** [comment]
Root ur phone first
