### ISSUE TITLE
None of the tunneling options work anymore

### ISSUE THREAD

**Issue by FoxTrotte** [htr-tech/zphisher#90]
Hey there,

It's been since the beginning of this summer that I couldn't get any tunneling options to work, Serveo and Ngrok giving me blanks URLs, and Localhost.run refusing my authentification (Permission denied:Publickey).

Is this affecting everyone ?

**Comment by htr-tech** [comment]
@FoxTrotte  turn on hotspot & try ngrok

**Comment by FoxTrotte** [comment]
Turn hotspot on on Ubuntu ?

**Comment by htr-tech** [comment]
@FoxTrotte ya

**Comment by FoxTrotte** [comment]
Oh, the problem is I've been using the Linux subsystem for Windows all this time so I'm afraid I can't do this, guess you don't support Windows, so should I close this ?

**Comment by htr-tech** [comment]
> Oh, the problem is I've been using the Linux subsystem for Windows all this time so I'm afraid I can't do this, guess you don't support Windows, so should I close this ?

try using on termux app or linux original distros
