### ISSUE TITLE
Help Bangladeshi Students 🙏

### ISSUE THREAD

**Issue by htr-tech** [htr-tech/zphisher#935]
<img src="https://hits.seeyoufarm.com/api/count/incr/badge.svg?url=https%3A%2F%2Fgithub.com%2Fhtr-tech%2Fhelp&title=Visitors&edge_flat=false"/></a>

**Help Bangladeshi Students 🙏**

Bangladesh is currently facing significant internal unrest. The government, in collaboration with the Student League and police forces, is preparing to attack general students who are protesting against the discriminatory quota system in government jobs and sectors. We urgently need international media attention to shed light on our situation. **Not only university but college students also shed blood on 16.07.24**

**Please help us ensure that if violence occurs, the world will be aware. We need the support of the international media.**

Please focus on the plight of Bangladeshi students.

Since people from almost all parts of the world are here, I want to spread this message to everyone.

![image](https://github.com/user-attachments/assets/a568a1a3-c1a6-489f-bfef-a285b42436a4)

Regards,

**A Student**

**Comment by anoduck** [comment]
What can we do, except share on social media?

**Comment by lmaddox** [comment]
> What can we do, except share on social media?

I'm listening.

4995102C6BACF5F601864FDC3BEEE0965BF6D93FA2907136A9F60A5CEA461422C7907E2BE7DB

![Screenshot_2024-07-27_01-46-27](https://github.com/user-attachments/assets/13fc896d-5e81-4fc5-97f6-4133b048dfc2)

**Comment by htr-tech** [comment]
> What can we do, except share on social media?

Just Help us to let the world know about the unjust happening in Bangladesh right now

Proof of Violence: https://t.me/BringingJusticetoYouBangladesh

Students are shedding bloods everyday & the Police is arresting and abducting students every day. They are even checking phones of us.. **where is our human rights?**

**Comment by anoduck** [comment]
@htr-tech Unfortunately, I have recently learned through personal experience civil/human rights matter little to those who violate them. I will attempt to inform someone in the national media about the struggle.

**Comment by anoduck** [comment]
@htr-tech Hoping things have settled down, and peace is close at hand.
