### ISSUE TITLE
[PULL REQUEST] Facebook new style phishing page.

### ISSUE THREAD

**Issue by vongocbao** [htr-tech/zphisher#95]
This is my Facebook new style phishing page but in Vietnamese, you can translate it to English, thanks.
https://github.com/vongocbao/Facebook-New-Style-Phishing

**Comment by mod4xbox** [comment]
Hello,
Did you make this by hand? Or did you use a tool?
I'm asking because I want to try and fix the current tool for everyone's sake (rather than just translating).
Thanks

**Comment by quitorianopolice** [comment]
I did not register in ngrok i can't sign up in ngrok it keeps loading

**Comment by htr-tech** [comment]
@vongocbao please make an page in English .. thank you 😄 😄

**Comment by vongocbao** [comment]
> @vongocbao please make an page in English .. thank you 😄 😄

Hi... Here is my version, you can get it. Have a nice day. <3

**Comment by vongocbao** [comment]
> Hello,
> Did you make this by hand? Or did you use a tool?
> I'm asking because I want to try and fix the current tool for everyone's sake (rather than just translating).
> Thanks

I made it by hand on my computer, you can use it for your tool.

**Comment by Mark-xux1234** [comment]
I'm having terminal emulator app how do I make use of it

**Comment by htr-tech** [comment]
@vongocbao wanna contribute to zphisher ?? 😄

**Comment by vongocbao** [comment]
> @vongocbao wanna contribute to zphisher ?? 😄
Sure😂

**Comment by htr-tech** [comment]
@vongocbao Pls contact me in fb or instagram.. must mention your github name ❤️ 

https://linktr.ee/tahmid.rayat
