### ISSUE TITLE
About localhost ip binding

### ISSUE THREAD

**Issue by winqdev** [htr-tech/zphisher#965]
### Describe the solution you'd like

Make somehow to bind 0.0.0.0 instead of 127.0.0.1

**Comment by Waisb** [comment]
Hi!
I ran into the same problem when I tried to reset access to the local network. 
To set the value to 0.0.0.0, you can edit the HOST variable in zphisher.sh. To HOST='0.0.0.0'

**Comment by winqdev** [comment]
now better :)
