### ISSUE TITLE
weird intelligible characters appear

### ISSUE THREAD

**Issue by geeroovaa** [htr-tech/zphisher#99]
it works just fine for me the only problem is that i cant read the output because of these weird characters. thanks

![zzz](https://user-images.githubusercontent.com/31460390/97099602-43cbca80-1661-11eb-8c78-b9ad10a73588.PNG)

**Comment by max500-dot** [comment]
Hard to use

**Comment by htr-tech** [comment]
@geeroovaa thats your device problem use on termux or linux official distros

**Comment by geeroovaa** [comment]
hmmm weird im using debian

**Comment by htr-tech** [comment]
> hmmm weird im using debian

use termux on android then.. 😩

**Comment by quitorianopolice** [comment]
Why am i getting this kinds of problems? There is no links

**Comment by quitorianopolice** [comment]
Why am i getting problems like this the ngrok is not here
![Uploading IMG_20201027_155241.jpg…]()

**Comment by quitorianopolice** [comment]
What's wrong with this pls hehe
![Uploading IMG_20201027_155241.jpg…]()

**Comment by htr-tech** [comment]
@quitorianopolice try reinstalling the toolkit
